### ISSUE TITLE
Enrollment Connect Card page: Move sentence back to the last media item

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1004]
## Acceptance Criteria

- [ ] Add the last paragraph as a paragraph in the last media item

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3673236/193907753-cef149c1-2f5f-48a7-9ac1-3017d135c871.png">

**Comment by thekaveman** [comment]
I'll grab this and fold it into #997
