### ISSUE TITLE
Configure reCAPTCHA in test/prod

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1016]
With Courtesy Cards, we're bringing back the Eligibility Verification form for user input. Let's ensure reCAPTCHA is configured to protect this form.

## Acceptance Criteria

- [x] In `test`, the Eligibility Verification form for Courtesy Cards is protected by reCAPTCHA
- [x] In `prod`, the Eligibility Verification form for Courtesy Cards is protected by reCAPTCHA

## Additional context

[See our docs on reCAPTCHA configuration](http://docs.calitp.org/benefits/configuration/recaptcha/).

Related to #1105.

**Comment by thekaveman** [comment]
Blocked until we are ready for UAT

**Comment by machikoyasuda** [comment]
ReCaptcha has been configured on `test`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/201197653-2ab363e3-2c20-494d-bdd2-1533be0e9233.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/201197776-8ef73436-f18e-491a-8f19-32a42961c0fb.png">

**Comment by machikoyasuda** [comment]
Configuration complete
