### ISSUE TITLE
Update footer link color

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1031]
Looks like it changed again back to a blue:

On `dev` right now:

![image](https://user-images.githubusercontent.com/1783439/194643280-11123f0d-3f6b-4cf6-a9d4-47a9d5d0d55e.png)

In Figma right now:

![image](https://user-images.githubusercontent.com/1783439/194643311-f743283b-6bcd-474a-8807-bceff3596a96.png)

Figma color is `Text/Footer Link` -- `#73B3E7`

**Comment by machikoyasuda** [comment]
@thekaveman Try opening the page in a Private/Incognito window. This shows up purple b/c there's a new CSS style that sets the color as purple if you've visited the site:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/3673236/195140674-39716e1e-4976-479e-b231-575a7b6a37aa.png">

**Comment by machikoyasuda** [comment]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/3673236/195141361-1102ba7c-1dd4-4d00-a850-f81312222a07.png">
regular vs. incognito
