### ISSUE TITLE
Extract reusable infrastructure components

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1038]
_As an engineering team managing infrastructure, I want best practices baked in via repeatable patterns so that I don't have to think. (in a good way)_

In [a discussion](https://docs.google.com/document/d/1WdH75tPGYaZuqLkC4q-Uw14qde1mozchdU1clQxkQWU/edit?disco=AAAAhmj287U) around https://github.com/cal-itp/eligibility-server/issues/158, we decided it would be worth trying to componentize the infrastructure configuration to make it reusable. Benefits:

- Would enforce that the deployments truly are the same
- It’s a reversible decision: we can switch later
- Possibly reusable by CDT for the Identity Gateway as well

Downsides:

- The extra layer(s) of abstraction can be confusing to people working with them
- It might coerce applications to look the same when they would be better off being different

The means to do so (we might not use all):

- [Terraform modules](https://developer.hashicorp.com/terraform/language/modules/develop)
- [Azure Pipeline templates](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)

Timebox: 2 days?

## Acceptance Criteria

- [ ] We have demonstrated that it is/isn't useful to reuse components between deployments the Benefits team is involved with

## Ideas

- Terraform modules:
   - App Service
   - Uptime monitor
   - [IP restriction via Front Door](https://github.com/cal-itp/eligibility-server/pull/222)
- Azure Pipeline:
   - https://github.com/cal-itp/eligibility-server/issues/212
   - Deployment [template](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)

**Comment by thekaveman** [comment]
Whenever this kicks off, can @angela-tran and @afeld please pair on this work? Angela expressed some interest in doing more with IaC.

**Comment by afeld** [comment]
Another way to go about this:

1. Start with a straight-up copy of the relevant files:
   - Terraform
   - Azure Pipeline definition
   - Infrastructure docs
1. Delete/modify as necessary to get it working for the Eligibility Server
1. Do a diff and see what remained the same
1. Refactor that into reusable components

Removes the refactoring as a blocker to deployment, but also more likely to be a thing we never get around to.

**Comment by thekaveman** [comment]
I think I like your newest approach - let's hold off on the refactor/componentization and leave this ticket around for that work, which we can schedule next sprint.

**Comment by afeld** [comment]
We started https://github.com/cal-itp/eligibility-server/pull/166 by copying configuration in from Benefits: https://github.com/cal-itp/eligibility-server/pull/166/commits/c3f90d02a987568dcf3119b31e776b8bca6af372. The [diff from then](https://github.com/cal-itp/eligibility-server/pull/166/commits/c3f90d02a987568dcf3119b31e776b8bca6af372) shows what needed to be changed to work for Eligibility Server / deploying to MST. In other words, the things that _weren't_ changed are good candidates to be extracted into reusable components. [One option to find those.](https://stackoverflow.com/questions/746458/how-can-i-show-lines-in-common-reverse-diff)

**Comment by angela-tran** [comment]
eligibility-server is stable, and we aren't planning any more deployments
