### ISSUE TITLE
Enrollment Success page: Final touches

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1039]
Make the page look like the Figma mocks. 

1. Desktop: Design the last line to this. It's a 10-column wide large div that is left-aligned.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/3673236/195391617-3f48afbb-9b1a-4500-b727-087a43e5865a.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/195273016-ca031b6e-673f-4bf1-943e-2fdd8f085255.png">

2. Mobile: Design this last line. This mobile alignment is trickier. Might have to write CSS to add a margin-left and then calculate exactly how much the amount would be, based on what is the diameter of the icon plus the margin.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/3673236/195392741-aba35117-a63f-457e-a8ec-3687b5ef7f30.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/195273060-2df3fad3-045e-48ad-af27-8c4f9abb75b7.png">

3. Enrollment Success post-log out:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/3673236/195393285-3eb7e077-b56d-4d11-9e2c-9d2a8858ad8d.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/3673236/195393331-387c207b-c988-471a-9eca-ae31356ab360.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/195273236-40fe1650-f74c-4126-8559-d86bdb7811da.png">

**Comment by machikoyasuda** [comment]
@angela-tran I just noticed the Enrollment Success page still inherits from `page`. Could you change it to inherit from `base` in your PR too?

One thing I noticed immediately is that on Mobile, the text is not aligned left to the container width (b/c it's using the `page.html`'s `container content`):
<img width="613" alt="image" src="https://user-images.githubusercontent.com/3673236/195456687-04cdb57a-6513-4a92-9973-ea7daa3d4305.png">

**Comment by angela-tran** [comment]
@machikoyasuda Yep, will be making it extend `base.html`
