### ISSUE TITLE
Desktop: Previous Page Button hover color

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1040]
A clear and concise description of the task.

## Acceptance Criteria

- [ ] Hover color is blue, look at Figma

**Comment by machikoyasuda** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/3673236/195392484-bb97ef9c-6f35-457e-b7a2-145c8eb7328c.png">

**Comment by machikoyasuda** [comment]
@srhhnry Are there Desktop designs for this button?

<img width="530" alt="image" src="https://user-images.githubusercontent.com/3673236/195392565-3fc0b483-da69-4ca5-82e1-9027eac11a18.png">

**Comment by srhhnry** [comment]
Nothing other than what is in the components library 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/5394204/195401547-5a8aab7b-52ed-4b0d-a8ec-f9a301bbed1f.png">

This design is from the old designs/old version of the app. I didn't see any apparent reason to update the desktop version, but will include in testing in the future.
