### ISSUE TITLE
Eligibility verifier selection: radio button label wraps under radio button

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1046]
## To Reproduce

1. Go to `/eligibility`

## Expected behavior

The radio button label should wrap within its indented area instead of going underneath the radio button. See screenshots.

## Screenshots
| Expected | Actual |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/25497886/195441900-4e2f787f-224a-4cfd-a170-7df4be6d6be8.png" width="450"> | <img src="https://user-images.githubusercontent.com/25497886/195441788-ea80c2ec-56a5-423f-b744-1a1576b53a5d.png" width="450"> |

Tested on Windows, Firefox in dev tools responsive mode

**Comment by angela-tran** [comment]
FWIW, I just tested this on my phone, and I guess my screen is wide enough to where the label doesn't wrap

<img src="https://user-images.githubusercontent.com/25497886/195447111-9292ddbd-46c2-4e8c-8d17-e37b08849412.png" width="450">

**Comment by thekaveman** [comment]
Another (possibly related?) issue with these radio lists that I did not notice before (though we talked about this previously RE: headings):

The `<p>` are inside the `<label>` tags -- this is not allowed! 

![image](https://user-images.githubusercontent.com/1783439/195456628-d8a06f78-ffe6-4229-b978-a2df86ed2156.png)

Read more at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#technical_summary

> **Permitted content**
> [Phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content), but no descendant label elements. No [labelable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#labelable) elements other than the labeled control are allowed.

"Phrasing content" (see link) does not include paragraphs:

> Phrasing content is a subset of flow content that defines the text and the markup it contains, and can be used everywhere flow content is expected. Runs of phrasing content make up paragraphs.

**Comment by machikoyasuda** [comment]
Oh so `<span>`s are allowed right @thekaveman ?

**Comment by machikoyasuda** [comment]
@angela-tran What phone do you have?

I have the narrowest/smallest iPhone (iPhone SE) and I do actually get this bug on my phone.

**Comment by angela-tran** [comment]
@machikoyasuda Yeah, I saw this issue in devtools using `iPhone 11 Pro iOS 14.6` so that makes sense

<img src="https://user-images.githubusercontent.com/25497886/195464577-6ae97f65-a4f3-49ac-8278-de1cbab73d70.png" width="250">

I use an old Android phone, Moto E4
https://www.sizescreens.com/motorola-moto-e4-screen-specifications/

**Comment by thekaveman** [comment]
@machikoyasuda yep `<span>` is on that [list of phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content)
