### ISSUE TITLE
Process for new use cases

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1061]
…slash benefits slash discounts (cc #987). For each of these that we have launched, there have been similar considerations, such as (running list):

- Who is eligible?
- How can we determine that eligibility?
   - What will the user experience be?
- Who is going to be in charge of that eligibility verification: CDT Identity Gateway or Benefits team?
   - What data will move back and forth?
   - Where to where?
- What are the edge cases?
- What are some tradeoffs/risks?
- Comms
   - What announcements are being made, if any?
   - What are we telling people?
   - Who are we telling?
   - Who will be doing the communications?
- What does success look like?
   - How do we know? (OKRs, metrics, etc)
- What are the legal/compliance requirements? Who needs to sign off?
- What copy needs to be updated?
   - Benefits app
   - Transit operator site
- What are timeline considerations/constraints?

Also, some TODOs that come up every time:

- Design
- User research
- Implementation of front end
- Copy approval from the partner(s)
- Usability testing
- Security
   - Compliance
   - Penetration testing
- Translations
- Drafting/sending communications
   - Release notes
- Ensuring the transit agency customer service staff are aware and have the info they need
- Create/update informational pages
   - https://www.calitp.org/
   - https://docs.calitp.org/benefits/use-cases/

Would be good to think backwards on what those considerations have been in launching each, to help us prep for future ones. Not sure if this will be a "project plan" or "launch checklist" or what; there is some overlap with the [epic template](https://github.com/cal-itp/benefits/blob/dev/.github/ISSUE_TEMPLATE/epic-decision-record.md) and [use case pages](https://docs.calitp.org/benefits/use-cases/).

## Acceptance Criteria

- [ ] We are forced to think about what will be involved in launching a particular use case

## What is the definition of done?

A document / issue template / docs page template that ask/track these questions

**Comment by afeld** [comment]
[Product Spec for college discount](https://docs.google.com/document/d/1aIIcNKxu1-tZ8lZSPEdqunWB39W9pGVetbRf5m8WhY4/edit#)

**Comment by machikoyasuda** [comment]
Another TODO that comes up every time: Have the transita gency create a new LittlePay group.

**Comment by machikoyasuda** [comment]
Another TODO: Set up new Amplitude/Metabase dashboards for new use case

**Comment by machikoyasuda** [comment]
Past go-live checklists
https://github.com/cal-itp/benefits-secrets/issues/1
https://github.com/cal-itp/benefits-secrets/issues/13

Future list
https://github.com/cal-itp/benefits-secrets/issues/4

**Comment by thekaveman** [comment]
> Another TODO that comes up every time: Have the transit agency create a new LittlePay group. Details: [cal-itp/benefits-secrets#19](https://github.com/cal-itp/benefits-secrets/issues/19)

Small correction -- Agencies cannot create _groups_, but they must create _products_.

Engineers must create the group(s), and associate existing product(s) to group(s).

**Comment by vykster** [comment]
closing this/ folding work into product process updates.

**Comment by machikoyasuda** [comment]
Similar ticket: https://github.com/cal-itp/benefits/issues/309
