### ISSUE TITLE
Page titles contain extra spaces, characters

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1080]
Our page titles (the string that shows up e.g. in the browser tab) are a little funky. They contain a bunch of extra spaces and weird formatting. For example, the `dev` site has this in the HTML source:

```html
<title>
      
        Transit Benefits: Introduction |
      
      Cal-ITP
    </title>
```

In the browser this isn't really a problem; extra spaces are truncated in the tabs:

![image](https://user-images.githubusercontent.com/1783439/197638842-440629f3-1388-460a-88ef-1b35e7b7107a.png)

However in certain situations, especially where links are expanded for previews (like in Social Media sites, comms apps like Slack, etc.), this extra spacing and weird formatting is more apparent:

![image](https://user-images.githubusercontent.com/1783439/197639119-580000b0-5e3b-4935-9ad9-690d69b01eb3.png)

## To Reproduce

1. Copy a link from the public facing Benefits app, e.g. https://benefits.calitp.org
2. Paste this link into an app that can expands links for previews, like Slack
3. See the weird title formatting in the expanded preview 

## Expected behavior

* There shouldn't be any extra spaces in the titles
* We should confirm this is the pattern we want (I'm thinking...probably not?) `Transit Benefits: <Page Title> | Cal-ITP`
  * Alternate suggestion: `<Page Title> | Cal-ITP Benefits`

**Comment by machikoyasuda** [comment]
I'm checking for other government sites and government site style guides for guidance on the page titles.

https://www.usa.gov/
https://www.usa.gov/benefits
https://www.usa.gov/food-help
https://login.gov/help/
https://login.gov/help/get-started/overview/

Seems like the common pattern here is `<Page Title> | <app name or app url>` 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/3673236/197644767-710c90e4-acc7-4ae6-83a6-e2fafd8ec0f4.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/3673236/197644792-9a805a8e-d0db-4dbb-a54a-fef44bc4f922.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/3673236/197644894-4327334d-b9a3-486b-93ed-4e44698618ba.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3673236/197644911-d61b2fc5-397f-43e2-b227-f789e6a7efb2.png">

**Comment by thekaveman** [comment]
> We'd have to decide whether the app name is the same across English or Spanish or different.

Good point, and I think we need to decide this anyway since we are currently not consistent (though some of the copy has been rewritten already). 

E.g. the `/eligibility/start` page (app name consistent across languages):

| English | Spanish |
| --------| ----------|
| ![image](https://user-images.githubusercontent.com/1783439/197646470-32e2bfe5-f0ea-4c84-a888-f8f45c275698.png) | ![image](https://user-images.githubusercontent.com/1783439/197646509-1cab7dbb-4e85-478d-bbc7-20a87fedd305.png) |

Vs. the `/help` page (app name changes across languages):

| English | Spanish |
| --------| ----------|
| ![image](https://user-images.githubusercontent.com/1783439/197646613-8cfdf14a-2e32-47da-91d4-a649a5ce706f.png) | ![image](https://user-images.githubusercontent.com/1783439/197646649-62555836-e556-4760-b1df-dc3dfadd03b2.png) |

**Comment by thekaveman** [comment]
We're going to standardize page titles using the format:

* English: `<Page Title> | Cal-ITP Benefits` 
* Spanish: `<Page Title> | Beneficios de Cal-ITP`
