### ISSUE TITLE
Design the Agency selection page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1090]
Sooner than later, we will go live with a second transit agency. Like today, users will be able to get directly to the app homepage for their agency using the direct agency link, e.g. https://benefits.calitp.org/mst.

Once we have multiple agencies however, the root app homepage e.g. https://benefits.calitp.org needs to provide an interface for the user to select between the agency options.

For this task, let's focus on the use case of selecting between two transit agencies only. In further iterations we can look to expand to more flexible use cases / UX (e.g. lookup by name, location, other options).

**Comment by srhhnry** [comment]
Sync meeting scheduled for Jan 10.

**Comment by srhhnry** [comment]
Working through some ideas here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?node-id=8084%3A34817&t=7jfmLMfG5hgyibTP-1

**Comment by thekaveman** [comment]
@srhhnry India @angela-tran and @thekaveman met to discuss options for this design.

Decision:

* the generic homepage will have a single button, clicking this shows a modal with cards for each agency (and a close button)
* clicking an agency card in the modal takes the user to the _eligibility start_ page for that agency
* users can still come in via the `/agency` shortcut, showing an agency-branded (e.g. text) homepage

**Comment by srhhnry** [comment]
Designs have been finalized and can be found here, as well as incorporated into the Benefits Full App pages, under Finalized Designs: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?node-id=8084%3A34817&t=PFQBMVnL8Ju7csCx-0
