### ISSUE TITLE
October Retro Action Items

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1095]
- [x] Share the draft new copy process @vykster 
- [x] Cont on the draft outreach plan @vykster @o-ram 
- [x] #1302
- [x] Reach out to MST with link to 8.5"x11" poster for posting in the customer service office. HOLD b/c the MST team is understaffed. @o-ram 
- [x] #1303
- [x] Add customer service to list of stakeholders in the requirements doc template 
   - [x] Add to https://github.com/cal-itp/benefits/issues/1061

**Comment by machikoyasuda** [comment]
This would also be a good ticket to go through and close in December :)

**Comment by MarikoLochridge** [comment]
The following tasks have been converted to their own issues:

Cont on the draft outreach plan >> #982

**Comment by MarikoLochridge** [comment]
All tasks in this ticket have been completed and/or converted into their own issues.
