### ISSUE TITLE
Find new resources for content localization and get budget approved

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1103]
- Research vendor(s)
- Get quote(s)
- Reach out to vendor to confirm process, expectations, and turn around time for service.

**Resources:**

- PO Files: https://github.com/cal-itp/benefits/tree/dev/benefits/locale
- [Notes from copy and content localization workshop](https://docs.google.com/document/d/1ofuWeTpPjOSxltKhqFE9eTOgxNaYDasCa13-Bg10zYw/edit)
- [Cal-ITP Benefits: App copy in English and Spanish](https://docs.google.com/spreadsheets/d/15aKUPv6gl-Y_j6XV2aiFnJ2wQlQobyfjBCUaSbQHelM/edit#gid=0)

**Comment by vykster** [comment]
submitted request for service/ quote to ibabbleon.com

**Comment by vykster** [comment]
![Screenshot 2022-11-01 at 2 46 13 PM](https://user-images.githubusercontent.com/4284662/199347814-a71489b8-2c58-4d89-af30-dd7257e289ce.png)

**Comment by vykster** [comment]
> Hi Vyki,
> 
> Thank you for your message. I’d be happy to help you translate the Cal-ITP app. The app content looks standard so it’s shouldn’t pose any challenges in translation. Assuming the strings are written properly, it should be an easy job. You’ll want to make sure that your developers can export the strings correctly for translation. Generally this means whole sentences should be exported as individual strings with all variables and punctuation included. We can work with just about any file type.
> 
> As for the additional resources, we can certainly translate the Glossary beforehand so you can send that over whenever it’s ready. The Style Guide can remain in English.
> 
> In terms of cost, we charge $0.22 per word per language so ~500 words would cost about $110. For requests with fewer than 100 words, we charge a minimum fee of $22. If your glossary has less than 100 words, then I suggest waiting to translate it close to November 11, then we can add the app translation to that and waive the minimum fee. For future updates, it depends on your internal deadlines. It’s typically better to wait until you have 100 or more words, but if you have pressing deadlines, we’ll still take the job with the minimum fee.
> 
> As for turnaround times, 500 words takes about 3 days or less. Translations always require a minimum of 24 hours regardless of the volume, but that’s rarely an issue outside of rush jobs.
> 
> Let me know if you have any other questions.
> 
> Best regards,
> 
> Salim
> Babble-on Translations

I plan to follow-up and submit the glossary first. 

cc/ @machikoyasuda @MarikoLochridge @srhhnry timelines!

**Comment by machikoyasuda** [comment]
@vykster Can Babble-on directly edit and submit translations via GitHub pull requests?

**Comment by machikoyasuda** [comment]
@vykster We also have 3 untranslated strings on Benefits we need:
https://github.com/cal-itp/benefits/blob/dev/benefits/locale/es/LC_MESSAGES/django.po#L373:382
<img width="757" alt="image" src="https://user-images.githubusercontent.com/3673236/199609860-e1824adf-6965-4bd2-b67c-83b85b6e3362.png">

**Comment by vykster** [comment]
I believe they can! I'll go ahead and add you to the portal now.

**Comment by vykster** [comment]
[2023 Budget Request Drafted](https://docs.google.com/document/d/1E65ZQPoVcm2Z8WuvNF024qIPfw7aGRJ7--foWduBQfo/edit)

**Comment by vykster** [comment]
Marking this closed now that the budget request has been shared with the project management organization (Jeremy).
