### ISSUE TITLE
Configure rate limiting in test/prod

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1105]
With Courtesy Cards, we're bringing back the Eligibility Verification form for user input. Let's ensure our application-level rate limit is configured to protect this form.

## Acceptance Criteria

- [x] In `test`, the Eligibility Verification form for Courtesy Cards is protected by a rate limit
- [x] In `prod`, the Eligibility Verification form for Courtesy Cards is protected by a rate limit

## Additional context

See our docs on [rate limit configuration](https://docs.calitp.org/benefits/configuration/rate-limit/).

Related to #1016.

**Comment by thekaveman** [comment]
Blocked until we are ready for UAT

**Comment by machikoyasuda** [comment]
Rate limit has been configured on `test`

**Comment by machikoyasuda** [comment]
Rate limit has been confirmed on `test` by @angela-tran 
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/3673236/201198979-20998939-e26b-401f-a25a-e0e2b0a05deb.png">

**Comment by machikoyasuda** [comment]
Configuration complete
