### ISSUE TITLE
HTMLFormElement.requestSubmit lacks browser support

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1111]
In #1071 we introduced a programmatic reCAPTCHA challenge to ensure our HTML5 form validation was taking place.

In #1088 we added the spinner animation to certain buttons, and in doing so, worked through a problem introduced in #1071 where the Javascript `.submit()` on a form element wasn't triggering the `submit` event. The solution using `.requestSubmit()` _does_ generate the `submit` event and it all worked as expected.

However some key browsers/versions don't yet support the `.requestSubmit()` method. Specifically, iPhone Safari until version 16, which was only released in September 2022.

More on [caniuse.com](https://caniuse.com/?search=requestSubmit)

## To Reproduce

1. Using an iPhone with Safari < 16.0 (e.g. 15.6), go to the dev site
2. Navigate to the Benefit selection screen
3. Choose an option, click "Choose this Benefit"
4. Form does not submit, see error in browser console:

![image](https://user-images.githubusercontent.com/1783439/199345304-6742ca75-739b-488c-9167-915226e0b29d.png)

## Expected behavior

The form should submit on all browsers/devices.

## Desktop (please complete the following information)

- Device: MacBook Pro
- Browser: Safari
- Version: 15.6

## Smartphone (please complete the following information)

- Device: iPhone SE
- Browser: Safari
- Version: 15.6

**Comment by machikoyasuda** [comment]
Was able to reproduce on my MacBook Pro / Safari 15

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3673236/199347277-de300566-f07a-44ab-9c1b-a46416796fe0.png">
