### ISSUE TITLE
specify App Service configuration as code

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1116]
## Initial description

**Title: _Add WEBSITES_ENABLE_APP_SERVICE_STORAGE configuration in Terraform_**

This is a required setting to prevent the filesystem from being obscured by a mount in an Azure App Service.

The lack of this setting was causing problems during the [Eligibility Server terraforming](https://github.com/cal-itp/eligibility-server/pull/166), where it has now been defined in HCL.

This recalled the Benefits [downtime in July](https://github.com/cal-itp/benefits/issues/826) and how the setting was ultimately required to bring the environments back up. Yet it never made its way into HCL here.

### Expected behavior

- [ ] Benefits terraform defines the setting with a value of `false`

## Expanded description

To allow App Service instances to be recreated as needed with minimal downtime, we want to keep any values from needing to be manually set in the App Service configuration.

### Acceptance criteria

- [ ] Terraform destroying and recreating an App Service resource brings the app up without manual intervention

### Definition of done

- [ ] App Service configuration values either live in Terraform (non-secrets) or Key Vault (secrets), referenced by Terraform / App Service

**Comment by angela-tran** [comment]
To do this, we need to manage app settings in Terraform. Currently, they are [ignored](https://github.com/cal-itp/benefits/blob/chore/separate-environments/terraform/app_service.tf#L60) for Benefits since they [contain secrets](https://github.com/cal-itp/benefits/blob/chore/separate-environments/terraform/app_service.tf#L13).

#1143 might inform how we refactor this.

**Comment by afeld** [comment]
Thinking the title for this issue should actually be something more general, along the lines of:

- "Specify non-secret App Service configuration values as code"
- "Minimize number of App Service configuration values that need to be set manually"

Not sure the best way to word it.

**Comment by afeld** [comment]
Going to hold off working on this until we discuss https://github.com/cal-itp/benefits/issues/1143.

**Comment by afeld** [comment]
Determined in https://github.com/cal-itp/benefits/issues/1143#issuecomment-1352172042 that we're going to give Key Vault references a try, so this should now be doable.

**Comment by afeld** [comment]
Expanded the issue.
