### ISSUE TITLE
Make a Release for Courtesy Cards

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1124]
### Release manager

@machikoyasuda

### Release version

2022.11.1

### What type of release is this?

_Regular_

#### Dev to Test: Thursday, 11/10
- [x] Create a branch called release/version from the source branch https://github.com/cal-itp/benefits/pull/1130
- [x] Bump the application version https://github.com/cal-itp/benefits/pull/1130
- [x] ~Open a PR for the release branch into the staging target, merge~
- [x] ~(If applicable): update staging data migrations~
- [x] prep data migrations and .env file changes from benefits-secrets / get approved https://github.com/cal-itp/benefits-secrets/pull/18#issuecomment-1310688906
- [x] open another PR from `dev` to `test`: https://github.com/cal-itp/benefits/compare/test...dev
- [x] get PR approved https://github.com/cal-itp/benefits/pull/1131
- [x] merge PR from `dev` to `test`
- [x] update data migrations from this [file](https://github.com/cal-itp/benefits-secrets/blob/61b221fc17f5e13b5092832ab3e98ee29c62579c/benefits/test/0002_test_data.py) 
- [x] update test `.env` file: reCaptcha env vars, rate-limiting vars https://github.com/cal-itp/benefits/issues/1105 https://github.com/cal-itp/benefits/issues/1016
- [x] QA the app in test-benefits.calitp.org  
- [x] QA that test-benefits.calitp.org analytics events are getting sent to Amplitude
- [x] Open a PR for the `test` branch into `prod`: https://github.com/cal-itp/benefits/compare/prod...test
- [x] (If applicable): prepare production data migrations

#### Eligibility Server release
- [ ] Get confirmation of server penetration testing results
- [x] Release Eligibility Server to Production: https://github.com/cal-itp/eligibility-server/pull/192
- [x] Confirm Eligibility Server is deployed to Production, and settings are configured properly.

#### Test to Prod, Monday, 11/14
- [x] Merge the PR: https://github.com/cal-itp/benefits/pull/1132
- [x] Update data migrations, `.env` file: reCaptcha env vars, rate-limiting vars https://github.com/cal-itp/benefits/issues/1105 https://github.com/cal-itp/benefits/issues/1016
- [x] QA the app in `prod`
- [x] Tag the release on the `prod` branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed
- [ ] Communicate to MST that the app has been deployed to prod

**Comment by machikoyasuda** [comment]
@angela-tran @afeld I drafted out release notes for this version of Benefits in the comment above. I added a bullet point at the end, `Infra updates:`. Could either of you summarize the greatest hits of the major infra changes for this release and put it in the bullet? Thank you.

**Comment by angela-tran** [comment]
@machikoyasuda The infrastructure changes that I worked on were all on `eligibility-server`, so I'll include them in the release notes for `eligibility-server`.

There don't seem to be any [infrastructure changes](https://github.com/cal-itp/benefits/pulls?q=is%3Apr+is%3Aclosed+label%3Ainfrastructure+milestone%3A%22Courtesy+Cards%22) for this milestone of Benefits, so I'll go ahead and remove the "Infra updates:" section from your draft.

**Comment by thekaveman** [comment]
Let's just make sure we link to the Server release notes from these ones.

**Comment by machikoyasuda** [comment]
- https://github.com/cal-itp/benefits/pull/1131 merged
- [dev-benefits.calitp.org/](https://test-benefits.calitp.org/mst) deployed

QA list:
- Full Login.gov flow
- Full CC flow
- Recaptcha on form page
- Help page
- Spanish language

**Comment by machikoyasuda** [comment]
@angela-tran and @machikoyasuda have confirmed on test-benefits.calitp.org:
- Full Login.gov flow @machikoyasuda
- Full CC flow @angela-tran
- Recaptcha on form page @machikoyasuda
- Help page @machikoyasuda
- Spanish language @machikoyasuda
- Confirmed recaptcha, rate limiting env vars are on Test

**Comment by machikoyasuda** [comment]
@angela-tran and I finished deploying: benefits.calitp.org/
