### ISSUE TITLE
Remove punctuation from headers

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1125]
Per the[ Cal-ITP Editorial Style Guide](https://docs.google.com/document/d/1yG2jc_aMPSGc2wqvazKGgFIeV-aDDDsJIuONhUg0MOI/edit?usp=sharing)

"Header text (headlines, subheads, and other typically boldface “display type”) should not use end punctuation, even when written in full sentences."

We need to remove all end punctuation from H1 copy

- [ ] In Figma
- [ ] On live site

**Comment by machikoyasuda** [comment]
There are several screens with 2-sentence H1 copy, that use a mix of `!` and `.`:

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/3673236/200965831-9687c2ab-2fad-4b0a-b6f8-6584467e969f.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200965958-49f2373d-317c-492f-9cb6-440c8b38ce07.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200966060-c78e7f96-6a08-44a3-aedf-f3ccd4948044.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200966122-419006a0-329c-4a84-b805-f1d2e5a19a2d.png">


This is how it could look without punctuation:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/3673236/200966540-acec0838-bdf6-4e71-8a14-6e6d4f7c34fb.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/3673236/200966561-220db627-1a12-4dc0-b197-1f76e8badf2d.png">

**Comment by machikoyasuda** [comment]
Login.gov does a mix:

- Punctuation for sentence with subject and predicate:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200971069-71df0b5a-6e29-4223-9d45-dd4fb31234d5.png">

- No punctuation for short sentence with a command (no subject):
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200971081-7497e756-01ed-41c9-a2ac-4b73d433ee9c.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/200971306-802e99a2-e51a-487d-b2c0-ea60212499df.png">
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/3673236/200971430-f7d1aa99-8a85-419d-8617-b6c0b4ce62d3.png">

**Comment by srhhnry** [comment]
All very good points.  The screens with exclamatory sentences def look odd unpunctuated (and prob would punctuated but paired with unpunctuated sentences). 

We can also override the Cal-ITP Editorial guide, but I want to make sure we're conscious of that decision.

**Comment by srhhnry** [comment]
Closing this issue as we don't need to change the punctuation. I added that we're overriding the Editorial Guide to the[ Cal-ITP Team Services Handbook]([https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit?usp=sharing)])
