### ISSUE TITLE
Revisit design of error pages

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1137]
- [ ] Review all potential errors that a user can face when going through various flows, and at various drop off points of flows 
- [x] Work with CDT team to understand what information we can get about _why_ the user received an error from Login.gov
- [ ] Rewrite current error screens, if necessary, to address all potential errors a user might face 
- [ ] Add more error screens, if necessary, to address all potential errors a user might face

**Comment by machikoyasuda** [comment]
This seems like the same as https://github.com/cal-itp/benefits/issues/842

**Comment by srhhnry** [comment]
> This seems like the same as #978

Sorry! I've been using the backlog for quick notes to myself regarding design fixes. I'll be more descriptive in the future. These two tickets refer to different error types: this one is for error screens when a user fails at some point in the flow, and the other refers to inputs when a user enters incorrect information in a form, but hasn't failed to verify/validate.

**Comment by srhhnry** [comment]
May need to finish this before translation

**Comment by srhhnry** [comment]
@machikoyasuda or @angela-tran I just wanted to verify error screens from the Benefits side. So far we have 404, 500, and a User Redirect Error. We also have a payment error coming out of Littlepay. Coming out of the IdG there's a potential identity verification error. 

I'm checking with John about any other errors that can come from the IdG, but other than the errors I mentioned here, are there any others we need to account for?

**Comment by srhhnry** [comment]
Bumping this thread @machikoyasuda @angela-tran If there are no more error screens to consider (I'm guessing there aren't) then I'll go ahead and close this issue

**Comment by machikoyasuda** [comment]
<img width="356" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/e81f2dae-6ef0-477f-9b04-4aca04cc93fa">
If a user is able to log into Login.gov properly - but they are under age 65 - they should get this screen, and the screen should have a `Sign out of Login.gov` link. The Production app and the Figma designs do not have this link.

**Comment by machikoyasuda** [comment]
<img width="698" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7cddc008-8029-4898-8c46-c90493c96d62">
This page could also have a `Sign out of Login.gov` link. I have not tested on Production whether this is the case on Prod or not.

**Comment by machikoyasuda** [comment]
This is a comment to merely document this discrepancy between Figma and Production as it is now, for the 500 page:

This is what the 500 page looks like in Production
<img width="1505" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/2746d864-34c8-4350-9861-ccefeedb1ed6">


This is what it looks like on Figma:
<img width="663" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/407ef165-7369-4190-9d1d-1f30a819effa">

**Comment by machikoyasuda** [comment]
Aside from these 3 design discrepancies, the list of error pages on this issue and on the Figma (Benefits Sample Agency) look good to me 👍

**Comment by srhhnry** [comment]
Thanks @machikoyasuda! I've updated the [developer full app board](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5766%3A22626&t=w58kxu3smXZ6F1kD-1) to note that if a user has gone through Login.gov they should see a signout on those error screens. With the VA API, a user could go through the IdG and not go through Login.gov, so I made a second screen showing the difference. 

For the discrepancy in 500 pages--looks like prod has a longer line length (which is an older design).

**Comment by machikoyasuda** [comment]
@srhhnry got it! And the copy for Return Home vs. Start Here is different too.

**Comment by srhhnry** [comment]
Ack. Yeah, that would (my) user error in automating the copy. I accidentally pulled in copy from the 404 error. Should all be corrected/consistent now.

**Comment by machikoyasuda** [comment]
Actually - @srhhnry -  I just realized there is an error page missing from this big Figma view:
<img width="1275" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/14914455-3fff-4cab-882a-1b12eb1e322a">
https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=8945-47279&mode=design&t=G9vGBHD6lYBWh89t-0

The page you get if you enter invalid Courtesy Card credentials. There should be a dotted arrow from the CC form page to this one:
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/c8cb69e2-4702-40b2-baac-be9e06daa55e">

At _some_ point we had copy that said this: 
<img width="588" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/3de7df34-72bc-4348-a5a4-f1b96eee3405">

However.. that copy looks like it's somehow not being used on the site at the moment (could be a bug)

cc @angela-tran
