### ISSUE TITLE
fix college discount prototype

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1138]
I'm looking to embed [the Figma prototype](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Identity-Verification-Login.gov)?node-id=7741%3A33063&scaling=scale-down&page-id=7741%3A32852&starting-point-node-id=7741%3A33063) on [the use case page](https://docs.calitp.org/benefits/use-cases/students/), but need a couple things updated:

- [x] Unable to click "Continue" on [the eligibility start page](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Identity-Verification-Login.gov)?node-id=7741%3A33153&scaling=scale-down&page-id=7741%3A32852&starting-point-node-id=7741%3A33063)
- [x] "Student" ➡️ "College"

Thanks!

**Comment by srhhnry** [comment]
Updated the prototype, which can be viewed here: https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Identity-Verification-Login.gov)?node-id=7742%3A35091&scaling=scale-down&page-id=7742%3A35066&starting-point-node-id=7742%3A35091

**Comment by afeld** [comment]
Thanks so much! Mind updating the title, just for consistency?

**Comment by srhhnry** [comment]
No problem--I updated the page name to College Flow, which I think will affect the prototype name, but just let me know if it's not and I'll see if where else it can be changed.

**Comment by afeld** [comment]
Perfect, thanks!
