### ISSUE TITLE
downgrade App Service plan

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1142]
## Acceptance Criteria

- [ ] We are using an appropriate plan for our use case

## Additional context

See https://github.com/cal-itp/eligibility-server/issues/200.

**Comment by thekaveman** [comment]
This can/will go as part of separating environments (this month), right @afeld?

**Comment by afeld** [comment]
We can wait for that to test in isolation, but don't have to wait if we don't want to. My expectation is that there will be 30-60 seconds of downtime while the app is re-provisioned.

**Comment by thekaveman** [comment]
OK, I think let's wait until we have more isolation. But otherwise just wanted to confirm we could do this this month.

**Comment by afeld** [comment]
I certainly hope we are done with the separate environments soon!

**Comment by angela-tran** [comment]
Note that when we change the App Service plan, this [changes the IP addresses of our app services](https://learn.microsoft.com/en-us/azure/app-service/overview-inbound-outbound-ips#when-outbound-ips-change)

> The set of outbound IP addresses for your app changes when you perform one of the following actions:
> ...
> * Scale your app between the lower tiers (Basic, Standard, and Premium), the PremiumV2, and the PremiumV3 tier (IP addresses may be added to or subtracted from the set).

Let's make sure we update `eligibility-server`'s IP address whitelists as a part of working on this issue.

I recommend holding off on this until after the holidays.
