### ISSUE TITLE
determine how we want to manage secrets

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1143]
We currently have secrets managed a number of ways, without a source of truth, which has led to confusion about what the values are intended to be in a given environment, missing secrets when deploying new features, and longer recovery time when we've needed to replace them.

## Acceptance Criteria

- [x] We have a plan to manage secrets in a consistent and well-understood way

## What is the definition of done?

- [ ] We have a documented process for how to update secrets
- [x] We have consensus on said process

**Comment by afeld** [comment]
Places we have/do store secrets:

- Azure
    - [App Service configuration](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal)
    - Key Vault
       - Secrets
       - Certificates
    - Pipeline variables
    - Storage blobs
- GitHub
    - [Actions secrets](https://github.com/cal-itp/benefits/settings/secrets/actions) - cc https://github.com/cal-itp/benefits/issues/1150
    - [benefits-secrets](https://github.com/cal-itp/benefits-secrets/tree/main/benefits)

We don't necessarily need to reconcile _all_ of these, but having fewer sources of truth might be good.

**Comment by angela-tran** [comment]
Notes from a meeting earlier today:

### App secrets
 - Move things that are secret out of data migration files, and retrieve from environment variables instead
 - Store environment variable values as secrets in Azure Key Vaults (one per-environment), and use [Key Vault references](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#source-application-settings-from-key-vault) to populate App Service [app settings](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-app-settings)
 - Move the data migration files into Benefits repo

### Pipeline and Infrastructure secrets
 - Azure DevOps lets you [link variable groups](https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#link-secrets-from-an-azure-key-vault) to Azure Key Vaults
 - In Terraform files, we've been using a secret for the [benefits-notify email address](https://github.com/cal-itp/benefits/blob/dev/terraform/monitor.tf#L62) and can continue using this pattern if any new secret values are needed

**Comment by thekaveman** [comment]
So are we thinking we need 3 different (extra) migrations files, one each for `dev`, `test`, and `prod` in addition to the sample? As we know, Django will run all migrations in there, so we would need to add logic to skip loading data based on environment...and they are all so similar, the only difference really being the secret values themselves, right?

I was imagining we'd edit/rename the *single* sample data migration to encompass both sample data / default values, and reading from environment for the specific secret values. 

My question about "picking" the environment keys to use was under this assumption, and it sounds like if we have 3 separate Key Vaults, we can reuse the same keys in each, so we don't actually have to "pick". The same code/migration runs in all 3 environments, where the values are just different.

**Comment by angela-tran** [comment]
I think you're right. We can use a single migration file. I had some fuzzy idea in my head about data-migration changes meant only for `dev` getting inadvertently applied to `test` and `prod` as well, but since it'll be a file in the actual Benefits repo, that's not going to happen (unless we're doing a real deploy, in which case it's not inadvertent!).

**Comment by afeld** [comment]
This issue was kinda written to be about the decision-making rather than the implementation; see linked issues for the follow-up tasks.

> In Terraform files, we've been using a secret for the [benefits-notify email address](https://github.com/cal-itp/benefits/blob/dev/terraform/monitor.tf#L62) and can continue using this pattern

That pattern is actually not ideal, as the secrets get read by Terraform, stored in its state, etc. Preferable to use references where possible.

**Comment by angela-tran** [comment]
> That pattern is actually not ideal, as the secrets get read by Terraform, stored in its state, etc. Preferable to use references where possible.

Ah I see. Thanks for noting this!

**Comment by afeld** [comment]
That said, we haven't tried references yet so there may be gotchas like [caching](https://learn.microsoft.com/en-us/azure/app-service/app-service-key-vault-references?tabs=azure-cli#rotation) we will hit.
