### ISSUE TITLE
Change Help to FAQ

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1149]
Update: 
- [ ] Workshop on how Benefits is conveying detailed information to users
- [ ] Redesign of Help page as needed
- [ ] TBD

**Comment by thekaveman** [comment]
Are we sure on this? See [this highlighted section in our Services Team Handbook](https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit#heading=h.uqsgbc9bpf6n) -- the general advice out there is to _not_ present content as FAQs.

**Comment by srhhnry** [comment]
Yup--so the advice from those resources is to not have a Help page/FAQ _at all_, but rather to write copy throughout the site as clearly as possible (so the user doesn't have to go to a Help page). 

There is a potential question about whether we want a Help page at all (e.g. we could use modals for Login information, and add more explanatory copy to each page). I'm definitely up for that conversation, and maybe we should have that before the Help page redesign? 

That all said, this ticket is to change the term "Help" to "FAQ" on relevant pages because as we're redesigning the Help page the headline "Frequently Asked Questions" is making a lot more sense than "Help."

**Comment by vykster** [comment]
Ok, we need to talk. Absolutely no FAQs.

**Comment by machikoyasuda** [comment]
To be discussed in January 2023.

**Comment by srhhnry** [comment]
Workshop scheduled for January 24th

**Comment by srhhnry** [comment]
Closing issue as we're developing a different, more informed approach to the Help page
