### ISSUE TITLE
Rename main to prod

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#116]
We aren't using `main` as the default branch. Let's rename it to `prod` to more closely align with the deployment environment it corresponds with.

Let's also rename the GitHub environment to `prod` to match.

**Comment by thekaveman** [comment]
Done.

**Comment by machikoyasuda** [comment]
@thekaveman https://docs.calitp.org/benefits/getting-started/development/ - should update this doc: https://github.com/cal-itp/benefits/blob/dev/docs/getting-started/development.md
