### ISSUE TITLE
Make a Release: 2023.01.1

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1167]
### Release manager

@afeld

### Release version

2023.01.1

### What type of release is this?

Regular

### Release checklist

- [x] Create a branch called release/version from the source branch
- [x] Bump the application version
- [x] Open a PR for the release branch into the staging target, merge ~~https://github.com/cal-itp/benefits/pull/1168~~ https://github.com/cal-itp/benefits/pull/1177
- [x] (If applicable): update staging data migrations
- [x] (If applicable): open another PR from dev to test - ~~https://github.com/cal-itp/benefits/pull/1169~~ https://github.com/cal-itp/benefits/pull/1178
- [x] (If applicable): update data migrations
- [x] QA the app in test
- [ ] ~(If applicable): prepare production data migrations~
- [x] Open a PR to for the test branch into prod, merge - https://github.com/cal-itp/benefits/pull/1170
- [x] QA the app in prod
- [x] Tag the release on the prod branch, push the tag to GitHub
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
Release version should be updated: `2023.01.1`

**Comment by afeld** [comment]
On it. Repurposing this issue.

**Comment by angela-tran** [comment]
2023.01.1 has been released
