### ISSUE TITLE
Use an Amplitude Data Destination for GCS

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1183]
## Background

In cal-itp/data-infra#960 we used the `data-infra` Airflow pipeline to build and schedule an ingestion DAG using Amplitude's export API.

This works to get the data into the BigQuery warehouse (where it can be made available to Metabase), but this approach also has a number of drawbacks:

* Code changes are needed to accurately capture changes to the underlying event structure in Amplitude, see:
  * cal-itp/data-infra#1432
  * cal-itp/data-infra#1461
* The data services team has been moving more towards `dbt`-based workflows, and away from the legacy Airflow/gusty flows like for Amplitude, e.g. their work towards cal-itp/data-infra#2109
* The ingestion job results in an additional load on data infra compute resources
* The ingestion job produces duplicate data stored in both GCS buckets and the BigQuery warehouse

## The task

Amplitude's new Data Management experience allows for any number of "data destination" connections, of which ~BigQuery~ GCS is an option. Read more about [Amplitude data destinations](https://help.amplitude.com/hc/en-us/articles/360044835531-Sources-and-destinations-Ingest-and-export-your-data). 

Data is imported as follows (see screenshot below):

> **Raw Event File & Data Format**
>
> Data is exported hourly as zipped archive JSON files, partitioned by hour with one or multiple files per hour. Each file contains one event JSON object per line.
>
> File names will have the following syntax, where the time represents when the data was uploaded to Amplitude servers in UTC (ie. [`server_upload_time`](https://help.amplitude.com/hc/en-us/articles/229313067#event-time)):
> ```
> projectID_yyyy-MM-dd_H#partitionInteger.json.gz
> ```
> For example, the first partition of data uploaded to this project, on Jan 25, 2020 between 5pm-6pm UTC will be in the file:
> ```
> 304110_2020-01-25_17#1.json.gz
> ```

The Event JSON objects have the following schema:

```
{
  "server_received_time": UTC ISO-8601 timestamp,
  "app": int,
  "device_carrier": string,
  "$schema": int,
  "city": string,
  "user_id": string,
  "uuid": UUID,
  "event_time": UTC ISO-8601 timestamp,
  "platform": string,
  "os_version": string,
  "amplitude_id": long,
  "processed_time": UTC ISO-8601 timestamp,
  "user_creation_time": UTC ISO-8601 timestamp,
  "version_name": string,
  "ip_address": string,
  "paying": boolean,
  "dma": string,
  "group_properties": dict,
  "user_properties": dict,
  "client_upload_time": UTC ISO-8601 timestamp,
  "$insert_id": string,
  "event_type": string,
  "library": string,
  "amplitude_attribution_ids": string,
  "device_type": string,
  "device_manufacturer": string,
  "start_version": string,
  "location_lng": float,
  "server_upload_time": UTC ISO-8601 timestamp,
  "event_id": int,
  "location_lat": float,
  "os_name": string,
  "amplitude_event_type": string,
  "device_brand": string,
  "groups": dict,
  "event_properties": dict,
  "data": dict,
  "device_id": string,
  "language": string,
  "device_model": string,
  "country": string,
  "region": string,
  "is_attribution_event": bool,
  "adid": string,
  "session_id": long,
  "device_family": string,
  "sample_rate": null,
  "idfa": string,
  "client_event_time": UTC ISO-8601 timestamp,
 }
```

In order to establish the connection, we'll need a Bucket and a Service Account in GCP. See the following article for setup details: https://www.docs.developers.amplitude.com/data/destinations/google-cloud-storage/

## Acceptance Criteria

- [x] Benefits event data from Amplitude is automatically sent to a GCS bucket via an Amplitude data destination connection
- [ ] The existing Airflow DAG for querying the Amplitude API is shut down / deleted
- [x] Metabase has all Amplitude data from August 30, 2022 forward

## Additional context

* [Analytics work in `benefits`](https://github.com/cal-itp/benefits/issues?q=label%3Aanalytics+)
* [Benefits Amplitude work in `data-infra`](https://github.com/cal-itp/data-infra/issues?q=label%3Aproject-benefits)

_Initial configuration of the Amplitude GCS data destination:_

<img width="946" alt="Initial configuration of the Amplitude BigQuery data destination" src="https://user-images.githubusercontent.com/1783439/226680267-19423589-429f-49b0-9589-59ce038b509c.png">

_GCS credentials settings:_

<img width="941" alt="Service Account connection settings for the Amplitude GCS data destination"  src="https://user-images.githubusercontent.com/1783439/226680435-64112c9b-ce3b-4e36-922f-f23c2695dbff.png">

**Comment by machikoyasuda** [comment]
First task:
- [ ] Set up Connector from Amplitude to GCS

**Comment by machikoyasuda** [comment]
Today:
- [ ] Created a service account for Amplitude within Google Cloud, `cal-itp-data-infra-staging` account, with the name: `amplitude-dev`. Downloaded JSON key.
- [ ] Gave `amplitude-dev` service account the storage admin role. Followed these [instructions](https://www.docs.developers.amplitude.com/data/destinations/google-cloud-storage/#create-a-gcs-service-account-and-set-permissions).
- [ ] Created `amplitude-benefits-dev` bucket in `cal-itp-data-infra-staging` GCS account.
- [ ] [Set up recurring data export to GCS](https://www.docs.developers.amplitude.com/data/destinations/google-cloud-storage/#set-up-a-recurring-data-export-to-gcs), from Amplitude to `amplitude-benefits-dev` bucket in `cal-itp-data-infra-staging` GCS account. Unchecked merged Amplitude ID box, so that is not exported. Did not specify a specific folder, just the bucket name.

<img width="1512" alt="Screen Shot 2023-04-04 at 1 45 48 PM" src="https://user-images.githubusercontent.com/3673236/229917485-ce99a092-8b4a-48d5-b419-8ba130ff663b.png">

**Comment by machikoyasuda** [comment]
@thekaveman What date should the backfilled data start from?

**Comment by thekaveman** [comment]
@machikoyasuda Let's start with August 12, 2022 when we relaunched with CDT and Login.gov

**Comment by machikoyasuda** [comment]
[x] Backfill from Aug 12, 2022-April 3, 2023 started today, April 5, 2023

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/3673236/230210738-f3e5cf55-6f06-473e-8164-804c49697a68.png">

**Comment by machikoyasuda** [comment]
- [x] Backfill done:
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/3673236/230532457-f176f62b-32c1-4521-92e0-0fdd472c7f3c.png">

**Comment by machikoyasuda** [comment]
## To be discussed
- [ ] Ask @o-ram what exact charts/tables of Benefits data is desired
- [ ] So that the dev team can create Fact Tables of _just_ the desired data fields

**Comment by machikoyasuda** [comment]
The two main Amplitude to GCS to Metabase tickets have now been completed and merged: https://github.com/cal-itp/data-infra/pull/2514 https://github.com/cal-itp/data-infra/pull/2525

- Metabase should now be getting data from the new, `mart_benefits` fact table. 
- The _staging_ Amplitude data destination has been turned off, in favor of the *production* Amplitude data destination. 
- The backfill job to the *production* bucket has also been completed.
- The previous existing Airflow jobs are now labeled _legacy_

Next steps:
- Make sure the Metabase dashboard charts are still good.
- Discuss with Olivia/Mariko what new charts are needed, desired.
- Possible further improvements to the data warehouse pipeline: Adding DBT data validation tests, add JSON lookups for `events_properties`, `user_properties`, refactor the Benefits fact table into multiple tables for faster lookups
