### ISSUE TITLE
Comms for SacRT Launch

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1192]
Assigning Olivia to lead tracking this issue, but expect support from Erika. 

- [x] [Maintain Gantt chart](https://docs.google.com/spreadsheets/d/1DV_nN8cI2Odp0xTIjPihqVObhdQ_-Ii7/edit#gid=1422500350) for SacRT team
- [x] Draft rider-facing launch comms

**Comment by o-ram** [comment]
Draft Gantt chart and marketing materials shared with SacRT on 1/12/23

**Comment by o-ram** [comment]
Draft rider-facing launch comms can be found [here](https://drive.google.com/drive/folders/1Vnve30fl-kIWjJHR3spppRxUMi_n3t5z) and include:

- agency generic materials as PDFs
- agency generic materials in their native file (Figma)
- Old SacRT draft of a Benefits rack card 

SacRT has a robust marketing staff and will likely use the native files of the generic materials to create their own version. Erika and Olivia will help as requested. 

Other items we plan to eventually share with them include:
- Generic version of website text
- Generic version of social posts
- Customer service documentation

As stated above, SacRT may wish to use generic materials to do their own things with. Erika and Olivia will support as much as they desire with comms.

cc @esquared415

**Comment by o-ram** [comment]
update: As of Feb. 3, SacRT staff has all available Cal-ITP marketing/comms/customer service materials. Standing by to support them as they go through the materials and have questions and/or need other materials.
