### ISSUE TITLE
Implement Agency Selection page

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1197]
This task is to implement the agency selection based off the notes from https://github.com/cal-itp/benefits/issues/1090#issuecomment-1377922860 and the designs in Figma (once they are finalized).

The backend code will need to change to support this - **see the approach outlined in https://github.com/cal-itp/benefits/issues/1197#issuecomment-1380873661**

<details><summary>Other ideas that we considered</summary>

> @thekaveman and I paired a bit to talk through ideas for implementation. Those ideas were:
>  - a form-based approach, where each card is actually a submit button for a form with a hidden input - the form would need to be handled by `/eligibility`
>  - a link-based approach, where each card links to a new URL whose view function simply sets the session agency and forwards to `/eligibility`
>  - a link-based approach, where each card links to the existing `agency_index` URL but with the addition of a [query parameter](https://docs.djangoproject.com/en/4.1/ref/request-response/#django.http.QueryDict) so that `agency_index` can know to forward to `/eligibility` - can be something like `?select=true`

</details>

## Acceptance Criteria
- [ ] Agency Selection page matches finalized design in Figma
- [ ] The user can enter the site from either the index (`/`) or an agency's index page (e.g. `/mst`)

**Comment by thekaveman** [comment]
@angela-tran your comment got me thinking about the approach we landed on, and I have yet another idea that is kind of a variation on the second and third options:

`/eligibility` currently has middleware that requires an agency in the session. The idea is to remove that requirement, and update the URL pattern to allow an (optional) agency slug parameter. So we could have both of these URLs:

* `/eligibility`
* `/eligibility/mst`

The former would assume agency is in the session (and throw an exception if not, just like now); the latter would get the agency as an argument to the view function. 

This option is similar to how we do e.g. agency selection via URLs already, and avoids the use of the querystring. Thoughts?

**Comment by angela-tran** [comment]
> This option is similar to how we do e.g. agency selection via URLs already, and avoids the use of the querystring. Thoughts?

I like that the cards would be more directly linking to the page they want, that this doesn't add a new URL (just builds upon an existing one), and that it's more consistent with how we're selecting agencies. I think this is better!

**Comment by thekaveman** [comment]
Final designs provided: https://cal-itp.slack.com/archives/C013W8RUAMU/p1673631693341459
