### ISSUE TITLE
Create exhaustive user flow of all frictions associated with Older Adult user experience

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1207]
An outline of each step of the journey an Older Adult will take to get a transit benefit through Cal-ITP Benefits. In this document we have exhaustively listed each step and any potential frictions.

[Document found here](https://docs.google.com/document/d/1YVIP47F98WohNHnPj9osghPcJjtO0LYCFdOWiZxrWs0/edit?usp=sharing)

**Comment by srhhnry** [comment]
@vykster Hey.....this has fallen deep into the cracks. I've totally forgotten the context for this ask and just wanted to check in to see if we still needed this or if there's a preferred format, etc etc. Sorry and thanks!

**Comment by vykster** [comment]
I've forgotten the context too! Let's close it -- if it's a problem it'll come up again.
