### ISSUE TITLE
Improve placement of mobile CTA

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1213]
> The mobile CTA and header (within the white box) looks a little low--the hero image feels like it's taking up a lot of real estate, causing the user to have to scroll to see the full context for the page. In the Figma boards the white box starts about midway up the Visa CC (instead of at the bottom)    
>
> <img width="207" alt="image" src="https://user-images.githubusercontent.com/5394204/213538780-00e5b6c4-9b54-4b50-bb3f-abe2fdb290a9.png">   
>
> Possible to move the box/header/CTA up? Expected behavior would be the user can see the CTA button without having to scroll.

_Originally posted by @srhhnry in https://github.com/cal-itp/benefits/issues/1206#issuecomment-1397482902_

**Comment by thekaveman** [comment]
Removing from the SacRT milestone so we aren't blocked there, this was an existing bug.

**Comment by machikoyasuda** [comment]
@srhhnry What kind of parameters or logic should there be for the height of the home page on Mobile?

Here are some proposals of design logic options:

1. Set the vertical height of the home page to _never_ scroll. The whole page (the top nav, main content section and footer) should all fit in the vertical height of the mobile browser at all times.

iPhone 12 mini, iPhone SE vertical
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/3673236/215598316-0c701c48-5aac-4b6b-90ea-62d64812c716.png">


2. Another option: set the vertical height of the home page to scroll only for the footer links. Parts of the whole page (top nav and main content section) should be set to the vertical height of the mobile browser, and then the footer will scroll. 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/215599408-1fdee56b-8627-4d65-933c-d005a3c99b34.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/215599447-dd0ab6d4-0a52-4687-9270-e863c314ad55.png">

**Comment by thekaveman** [comment]
@machikoyasuda do you have some time to follow up on this one? Maybe it's a simple fix we can it in for the SacRT release?

**Comment by srhhnry** [comment]
Sorry everyone! I just got a notification and realized I hadn't responded. If there's a time crunch either of those two options is fine. My preference would be option 2--scroll to the footer (based on the smaller screens having more of the hero image available). Both of those options work though, so this preference is not a blocker.
