### ISSUE TITLE
Set up security scanning of application

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1235]
To ensure we don't have vulnerabilities in our code, it may be helpful to implement automated scanning of the application.

cc https://github.com/cal-itp/benefits/issues/1234

## Acceptance Criteria

- [ ] The team is alerted when a vulnerable code path is introduced

## Additional context

This can be done through:

- Static analysis
  - [Bandit](https://bandit.readthedocs.io/)
  - [PYRE](https://pyre-check.org/docs/pysa-basics/)
- Scanning of a running app, as has been done in past security assessments
  - [OWASP ZAP](https://www.zaproxy.org/)
  - (many other options)

**Comment by thekaveman** [comment]
Just a note that we do run [Bandit as part of pre-commit](https://github.com/cal-itp/benefits/blob/dev/.pre-commit-config.yaml#L50), both locally and as a required check for `dev`, `test`, and `prod`.

I would think the [CodeQL workflow](https://github.com/cal-itp/benefits/actions/workflows/codeql.yml) covers this as well?

**Comment by afeld** [comment]
Nice, thanks! I guess I should've looked first 😛
