### ISSUE TITLE
Complete Acceptance Testing

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1239]
Related to #1193. 

This task tracks the completion and sign-off of Acceptance Testing.

## Acceptance Criteria

- [ ] @MarikoLochridge accepts the changes on `test-benefits.calitp.org` for SacRT + senior/Login.gov validation

**Comment by MarikoLochridge** [comment]
Acceptance Testing (AT) took place over three days January 30th - February 1st

Day One (January 30): [Littlepay confirmed they broke something in their QA environment, and rolled it back.  ](https://cal-itp.slack.com/archives/C013W8RUAMU/p1675181940289769?thread_ts=1675113154.991099&cid=C013W8RUAMU)
Day Two (January 31): [Login . gov confirms issues with their verification service](https://cal-itp.slack.com/archives/CG64NU5C7/p1675184991493199)
Day Three (February 1): Success! See below for feedback. Full AT testing data available on the Resource Doc below. 

Feedback for AT (Acceptance Testing): SacRT + senior benefits/Login.gov integration in Benefits
 
@srhhnry Please Check the Resource Doc for some design feedback from @afeld
When creating an account on Login. gov the confirmation email goes to spam 

Resource: [AT (Acceptance Testing): SacRT + senior benefits/Login.gov integration in Benefits](https://docs.google.com/spreadsheets/d/1DT7x84i89ccvN_fxd84E7toy9Rn-VgwJUAKD0v1ovME/edit?usp=sharing)

**Comment by thekaveman** [comment]
Thanks for the notes @MarikoLochridge!!
