### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1253]
While [the Benefits release process](https://docs.calitp.org/benefits/deployment/release/) _works_, it requires a decent number of steps (and thus time) to get a change/fix out to production. Moving towards [continuous deployment](https://www.atlassian.com/continuous-delivery/principles/continuous-integration-vs-delivery-vs-deployment) could reduce that time/friction.

## Acceptance Criteria

- [ ] Changes are deployed to production automatically, though not necessarily visible to the public

## Additional context

Getting to continuous deployment would likely require feature flagging. ([A funny intro to feature flags, starring a former coworker.](https://www.youtube.com/watch?v=B0IsCicYMsg)) A benefit here is that features can be decoupled, and thus no longer block releases by virtue of being on the `dev`/`test` branches.

While we do have a number of features/integrations that can be enabled/disabled without a deploy (through environment variables or modifying the migration file), these are all binary state: on or off for everyone. Using a more sophisticated tool for feature flagging could allow features to be shown for _some_ users, but not others.

**Comment by afeld** [comment]
[Thread showing some of the challenges of having a linear release process (`dev`->`test`->`prod`).](https://compilerla.slack.com/archives/C02GQ7AJXQE/p1676579098819679)

**Comment by thekaveman** [comment]
One possible option for feature flagging: https://github.com/cfpb/django-flags (see [Usage and more docs](https://cfpb.github.io/django-flags/usage/))

**Comment by thekaveman** [comment]
Also: https://github.com/django-waffle/django-waffle ([docs](https://waffle.readthedocs.io/en/stable/))

**Comment by thekaveman** [comment]
Closing this in favor of the tag-based / deploy on release model, which has been working well in `eligibility-server`. 

See #1527
