### ISSUE TITLE
Sentry: associate commits with releases

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#1266]
Follow-up to #1258.

Sentry releases are meant to help diagnose when errors were introduced. To trace those back to the underlying code changes, [commits need to be associated with releases](https://docs.sentry.io/product/releases/associate-commits/).

## Acceptance Criteria

- [ ] Clicking a stack trace in Sentry takes you to the correct line/revision in GitHub

## Additional context

The easiest way to do this is likely the [GitHub Action](https://github.com/marketplace/actions/sentry-release).

**Comment by thekaveman** [comment]
Follow along @atvaccaro work in cal-itp/data-infra#2502 - he is putting together a nice pattern for how to do this.

cc @machikoyasuda @angela-tran

**Comment by angela-tran** [comment]
This feels shaped enough, just not sure if we need to do it soon

**Comment by thekaveman** [comment]
We decided there aren't really enough releases right now where it is difficult to trace Sentry errors to the version of the code.
