### ISSUE TITLE
Don't send events for healthchecks

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1276]
We use Amplitude to gather event analytics for specific user events in the app, like visiting a page and clicking a button. 

Amplitude recently announced a change in their billing model, away from straight per-event to a "Monthly Tracked Users" (MTU) metric. Read more on their blog post: https://help.amplitude.com/hc/en-us/articles/12217810210331

This presents a problem for us, because every time the various healthchecks (`AlwaysOn`, `Edge Health Probe`, maybe others?) ping the app, a pageview event is sent to Amplitude, and each of these pings is counted as a distinct MTU. 

## Expected behavior

- [ ] Amplitude does not receive events for views from the various healthchecks.

## Options

1. Reconfigure all the healthchecks to hit our `/healthcheck` endpoint, which already bypasses Amplitude events
2. Amend the Amplitude event sending logic to skip when e.g. certain user agents are present
3. Something else?

## Additional context

Right now within Amplitude, we filter events from certain User Agents so these don't show up in our charts etc. But they are still counted towards our plan's MTU metric:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1783439/219169446-902e8b62-efae-44c0-81ed-d0154966c8ed.png">

Unfortunately the "Block" filters available in our plan don't allow blocking events based on anything other than event name or IP address.

**Comment by angela-tran** [comment]
From Azure docs on [Configure apps](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-general-settings), it appears we cannot reconfigure the endpoint for `AlwaysOn`.

> - **Always On**: Keeps the app loaded even when there's no traffic. When Always On is not turned on (default), the app is unloaded after 20 minutes without any incoming requests. The unloaded app can cause high latency for new requests because of its warm-up time. _When Always On is turned on, the front-end load balancer sends a GET request to the application root every five minutes_. The continuous ping prevents the app from being unloaded.
