### ISSUE TITLE
Update Benefits slide deck

### ISSUE THREAD

**Issue by o-ram** [cal-itp/benefits#1288]
## Acceptance Criteria

- [x] Multiple decks exist in the external resources folder - pick one to be the "main" deck
- [x] Deck is updated

## Additional context
Multiple tickets look to exist about content updates, many of which are old. Therefore, this ticket may be somewhat duplicative but is meant to serve the immediate purpose of just updating the main slide deck for Cal-ITP usage. Scope of ticket does not include other content assets. As part of this process, @MarikoLochridge and I will take a look at the other tickets and see what we may be able to close or better clarify for other content updates moving forward.

Resources:
[Slide deck 1](https://docs.google.com/presentation/d/1Vawi8d70jtKfL-u5lwM05CcDyQ5zB764/edit#slide=id.gcec9a6eb8b_0_773)
[Slide deck 2](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.p1) - looks duplicative of the other deck; both live in the same folder

We are working in : [WIP: Cal-ITP Transit Benefits Slide Deck for External Communications](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.gcd07a00814_0_16)

Tickets:
#857 
#896 

## What is the definition of done?
Deck is updated and able to be found within the external resources folder for Cal-ITP for external sharing needs.

**Comment by o-ram** [comment]
@MarikoLochridge let's go with [this deck](https://docs.google.com/presentation/d/1Vawi8d70jtKfL-u5lwM05CcDyQ5zB764/edit#slide=id.gd6f15bd237_0_58) - it was updated more recently than the other. I've flagged places that need updates. I'll add some more detail when I get a chance, but if you could get started with the more straightforward ones, that would be great!

Could you please mark [this deck](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.gcecff84dcb_0_5) as "archived" in the title - I think it can stay in the same location for now but at least the title should let people know this is old.

**Comment by MarikoLochridge** [comment]
Ticket #857 has been closed and the deck indicated in that ticket has been archived.  https://github.com/cal-itp/benefits/issues/857

Moving forward this is the deck that will be updated. 

Updates needed:
Remove images and language around the DMV

**Comment by MarikoLochridge** [comment]
Once the Benefits Deck is complete @MarikoLochridge to ask for dev team support (likely @angela-tran or @machikoyasuda ) to publish to docs site : https://docs.calitp.org/benefits/

This idea was presented [at the February Retro](https://compiler.teamretro.com/meetings/3DfhEQsHWfg94C53qVentX)! Thank you team!

**Comment by MarikoLochridge** [comment]
Notes from[ March 6th Sprint Planning](Cal-ITP Benefits Sprint Planning & Retro Notes) 

Include speaker notes information
- Intended audience 
- Intended use

Add slides
- How to reach out to us
- Onboarding Process Checklist for agencies 

++ There is also a policy slide deck for Benefits that is different in content and use than this deck ++

**Comment by MarikoLochridge** [comment]
We are updated this slide deck
[Slide deck 2](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.p1)

- Added directions to the top of the slide deck
- Removed all references to the DMV
- Added in some links to the speaker notes
- Changed images to reflect latest designs 
- Added a 'contact us' slide at the end. 

Questions: 
Do we need a resources section?
Do we need more details or additional images for fare types?

Need to:
Add in mobile GIF @MarikoLochridge 
Make sure all slides that have been requested are included in this deck @o-ram

**Comment by MarikoLochridge** [comment]
Updated the slide deck with a GIF of the Benefits sign up flow on mobile for 'Older adult' 

Was able to pull recently updated images from [Figma](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5766-22626&t=wJ3GK83D8uZa4YYI-0) to update the slide deck. 

NB: Dev team is working on the calitp.org redesign and @thekaveman  flagged that a Benefits deck is on the list of resources - @o-ram provided an abbreviated version that can be public facing but will update with this version once completed.

**Comment by machikoyasuda** [comment]
@o-ram @MarikoLochridge 

The code for the Benefits deck on the calitp.org page is here:

https://github.com/cal-itp/calitp.org/blob/staging/src/_resources/slide-deck-benefits-overview.md
The page so far, without full styling, looks like this: https://deploy-preview-120--cal-itp-website.netlify.app/resources

**Note**:  ⚠️ This is still only on Staging (https://deploy-preview-120--cal-itp-website.netlify.app/), not on Production. This is not live yet. ⚠️ 

<img width="565" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7f7029da-c803-4291-a853-3d630a3e3ef3">

To get the Google Drive link (currently set to [this](https://docs.google.com/presentation/d/1Vawi8d70jtKfL-u5lwM05CcDyQ5zB764/edit?usp=share_link&ouid=107888682452903153368&rtpof=true&sd=true)) and the title on the page (currently set to `Cal-ITP Transit Benefits Overview Presentation`) changed, create an Issue here: https://github.com/cal-itp/calitp.org/issues

**Comment by o-ram** [comment]
Thank you @machikoyasuda! I opened an issue over in the calitp.org repo.

@MarikoLochridge the updated deck is (I think) done! I officially renamed it and it is in the External Resource folder. When we next chat, let's see if we feel ready to close this issue!

- [Google slide version](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.g1f5d42eaf8e_0_0)
- [PDF version ](https://drive.google.com/file/d/1UhNTnJAEABnCOFFZ-1xBHDoTYe322t-G/view?usp=share_link)(that is for the website)

**Comment by MarikoLochridge** [comment]
Updated slide deck completed and handed off to @thekaveman for resources page on Cal ITP website 

The slide deck is also available as a template in the CAL ITP Benefits External Resources folder as '[Cal-ITP Transit Benefits [External deck]](https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit#slide=id.g2449c40ca56_1_18)'
