### ISSUE TITLE
Update fact sheet with login.gov information: Cal-ITP Benefits Fact Sheet

### ISSUE THREAD

**Issue by MarikoLochridge** [cal-itp/benefits#1298]

**Comment by srhhnry** [comment]
@MarikoLochridge I think I need more context here. I'm having trouble finding the fact sheet or seeing what needs to be updated

**Comment by thekaveman** [comment]
We think this is the current fact sheet doc: https://drive.google.com/file/d/1BLHkI47xtRIPJlBJx5wNlifwqrFPU83I/view

Still looking for the editable source.

**Comment by MarikoLochridge** [comment]
@srhhnry Following up on this, I thought that you may have the original file but @o-ram shared that it pre-dates you. We are trying to update this sheet because it still has references to DMV. I'll remove you from this ticket and re-assign myself and @o-ram as we continue to update all external facing comms materials.

**Comment by o-ram** [comment]
@srhhnry question for you: is it possible to upload a PDF into Figma and edit it? I think Chris Arvin, a previous designer, made this, but we don't seem to have the editable source. I can reach out to them and see if they have it, but wanted to ask you this Q just in case. (cc @MarikoLochridge)

**Comment by indexing** [comment]
@MarikoLochridge I believe the editable source for this document is here in the one-pagers project in Figma: https://www.figma.com/file/vcAt9yOFu05Oa8IOaeyWUj/Automated-Transit-Discounts?type=design&node-id=0%3A1&t=kQUKjwOkzxH6Qwar-1

**Comment by srhhnry** [comment]
Just following up: @MarikoLochridge do you want me to change your figma permissions again so you can edit? I'm also happy to make the necessary changes if that's simpler.

**Comment by thekaveman** [comment]
@srhhnry if you have the bandwidth, can you please make the changes in Figma?

**Comment by srhhnry** [comment]
No prob. Here's the current copy that needs to be updated: 

1. Enter CA DMV–issued driver’s license or state ID number and last name to verify that a rider is at least 65 years old and eligible for a senior discount
2. Enter contactless bank card details to link discount eligibility status to a valid bank card through a portal provided by your transit agency

There are also a few instances of discount/discounted that I'll update to "transit benefit" and "reduced fare."

Lastly, do we want to update this to reflect new user types? It currently only mentions older adult riders

**Comment by srhhnry** [comment]
[ATD-1.pdf](https://github.com/cal-itp/benefits/files/11518781/ATD-1.pdf)
[ATD-2.pdf](https://github.com/cal-itp/benefits/files/11518782/ATD-2.pdf)

Updated copy and docs attached--send me your edits and suggestions and I'll make those changes!

**Comment by MarikoLochridge** [comment]
@srhhnry Thanks for your quick work on this (and also shout out to @indexing for finding the edit-able version), took a look at the updated version with @o-ram this morning and from our end it looks great. 

Unless @thekaveman or @indexing has anything else on these two fact sheets they'd like to update I believe we can close this ticket!

**Comment by MarikoLochridge** [comment]
This fact sheet has been updated with the following changes:

- Enter CA DMV–issued driver’s license or state ID number and last name to verify that a rider is at least 65 years old and eligible for a senior discount
- Enter contactless bank card details to link discount eligibility status to a valid bank card through a portal provided by your transit agency
- Update instances of "discount" to "transit benefit" and "reduced fare."

In the future this document will require updates to indicate new user types as those options become available through Benefits. (FYI - @indexing )
