### ISSUE TITLE
Follow-up with CDT to ask about how they are communicating asks to Login.gov

### ISSUE THREAD

**Issue by MarikoLochridge** [cal-itp/benefits#1303]

**Comment by MarikoLochridge** [comment]
@vykster I made this it's own issue from the #1095 ticket but unsure who to assign to this or if it's already been completed. 

The goal was to close the October Retro items ticket so I separated incomplete tasks into their own issues.

**Comment by machikoyasuda** [comment]
#1207

**Comment by jarrettkrumrei** [comment]
We use the @login-partner-support channel in Slack for technical assistance questions. For product questions, suggestions and/or recommendations we (typically through @srhhnry) engage their product and design team. For more strategic needs/questions we generally communicate directly with the Login partnerships team and have others pulled in as needed, depending on the ask (i.e. technical, contract/legal, etc).

This conversation was prompted and discussed over Slack. Here is a link to the thread for additional discussion and reference: https://cal-itp.slack.com/archives/C037Y3UE71P/p1678133215762179
