### ISSUE TITLE
Add enrollment/ridership data to Metabase

### ISSUE THREAD

**Issue by MarikoLochridge** [cal-itp/benefits#1309]
## Additional context

- [x]  Complete this ticket #1246 

- [x]  Currently blocked by this ticket #1183 

## What is the definition of done?

Metabase Benefits Dashboard has updated enrollment/ridership data for all agencies participating in Benefits

**Comment by indexing** [comment]
@MarikoLochridge Issue #1183 is marked closed. Are we now able to move forward on a resolution for this issue?

**Comment by MarikoLochridge** [comment]
@indexing Yes, and let's schedule a meeting so I can walk you through the current status of Metabase that @o-ram worked on and thoughts on next steps.

**Comment by machikoyasuda** [comment]
@MarikoLochridge @indexing @o-ram 

All of the Benefits/Metabase/Amplitude work is complete as of last month (https://github.com/cal-itp/data-infra/milestone/24, https://github.com/cal-itp/data-infra/pull/2514, https://github.com/cal-itp/data-infra/pull/2525, https://github.com/cal-itp/data-infra/pull/2599, https://github.com/cal-itp/data-infra/pull/2614, https://github.com/cal-itp/data-infra/pull/2614, https://github.com/cal-itp/data-infra/pull/2620), so Metabase should have all the new data fields.
