### ISSUE TITLE
Evaluate Littlepay Back Office API to replace Customer API

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1317]
The Littlepay Back Office API now supports registering users into Concession Groups! This is a more modern API from Littlepay that does not use Client Certificate authentication so would be simpler to manage from a code perspective.

Docs:

* https://docs.littlepay.io/back-office/
* https://docs.littlepay.io/back-office/security-basics/
* https://docs.littlepay.io/back-office/hosted-card-tokenisation/
* https://docs.littlepay.io/reference/backoffice/tag/Products/

## Acceptance Criteria

- [ ] Issue write-up with a proposed plan to refactor the enrollment app to use this newer API

## Additional context

[Slack thread with info about accessing Littlepay docs](https://cal-itp.slack.com/archives/C013W8RUAMU/p1678895938686919?thread_ts=1678895875.333369&cid=C013W8RUAMU).

**Comment by thekaveman** [comment]
I sent a request to Littlepay support for credentials to access this API today.

**Comment by indexing** [comment]
@thekaveman Are we still waiting for a response from Littlepay support?!

**Comment by thekaveman** [comment]
@indexing no, we just haven't had a chance to try out the new APIs / credentials that we received.

**Comment by thekaveman** [comment]
Exploring this over here: https://github.com/cal-itp/littlepay

**Comment by thekaveman** [comment]
Closing this as work is well underway. Final two items:

- https://github.com/cal-itp/littlepay/issues/10
- https://github.com/cal-itp/littlepay/issues/9
