### ISSUE TITLE
Update Copy

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1319]
Problem: Some our copy is getting out of date as the program matures and we add new features. Update copy to be accurate and simplify where possible.

Tasks:
- [x] Review all copy, line by line
- [x] pair with engineering
- [x] pair with customer service too

*Resources*

- [Benefit Content Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1cKQCAt3OTg40KeLWwjl1FE86kJfGEcEHbnyg7AWAAM8/edit#gid=0)

**Comment by srhhnry** [comment]
Working meetings scheduled with Angela and Olivia

**Comment by srhhnry** [comment]
Copy has been updated!
