### ISSUE TITLE
Simplify copy on Help page

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1320]
Problem: Some our copy is getting out of date as the program matures and we add new features. Update copy to be accurate and simplify where possible.

## What is the definition of done?
Copy if ready for engineering team

Tasks:
- [x] Simplify the help page page copy, removing excessive verbiage, outdated text, "DRY" the copy (Don't Repeat Yourself.”)
- [x] Create a pared-down version that accounts for moving info into modals
- [x] Review for multiple agencies

*Resources*

- [Benefit Content Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1cKQCAt3OTg40KeLWwjl1FE86kJfGEcEHbnyg7AWAAM8/edit#gid=0)

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/232150612-eacda287-902b-417a-a0b9-6ca85f21df05.png)



![Image](https://user-images.githubusercontent.com/5394204/232150627-20425f07-f619-4ec9-a4e4-ed0fa704ff44.png)

**Comment by srhhnry** [comment]
We decided not to pare down the Help page, and to duplicate what is in the modals instead. So the Help page with revamped copy is now complete.
