### ISSUE TITLE
Document key phrases in Copy

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1321]
Problem: Some our copy is getting out of date as the program matures and we add new features. Update copy to be accurate and simplify where possible. Likely this involves an interview with vyki and olivia. 

- [ ] Define the shared repository

## What is the definition of done?
Key phrases are documented with context on decisions behind in a shared repository.

**Comment by thekaveman** [comment]
Review / additional context: https://docs.google.com/spreadsheets/d/15aKUPv6gl-Y_j6XV2aiFnJ2wQlQobyfjBCUaSbQHelM/edit

**Comment by srhhnry** [comment]
Where are we on the phrase "Tap to ride"

**Comment by vykster** [comment]
This is great, thank you for the concise summary. previously we spent a lot of time work shopping bank card but that was because contactless was as available as it is now and was generally just confusing to users. 

Ship it all.

**Comment by srhhnry** [comment]
Amazing! @vykster I just want to double check on that last point (and clarify). For Courtesy Cards, this is the revamped Help page section: 

![Image](https://user-images.githubusercontent.com/5394204/232835714-f7525833-e3ad-48ed-a473-65b883ee7302.png)

I've cut the line about Benefits being a demonstration tool (confusing for users) and based on conversation with @o-ram and an understanding of MST's database, softly described an expiration date (e.g. using the word 'may'). I could also see cutting that line entirely. 

Lastly, on the success page for the CC flow, I think we should cut this line: "You may need to reapply for transit benefits at a later date" and this line: "In the future you may need to re-register for Benefits to continue using contactless payment cards."

Again, these cuts are all pointing to not using vague language or hedging in favor of changes from MST, but rather transitioning to letting agencies take responsibility to any updates on their programs.

**Comment by srhhnry** [comment]
I've documented all changes and key phrases in the Services handbook: https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit?usp=sharing and will close this comment pending Vyki's updates on CC card language
