### ISSUE TITLE
evaluate and update agency specific copy process

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1322]
Problem: As complexity of application increases our copy is becoming stale and depends on an increasing number of inputs and people to be accurate. 

We need to close existing gaps and implement new lightweight process to make better scale our ability to keep copy accurate. 

An MVP might be to look at an agency onboarding “tool” for copy that can be agency-configurable
Work with engineering to figure out what is agency configurable
If not, can that be part of agency onboarding checklist

Review copy to simplify column looking for ways to abstract out and scale back (less agency-owned business logic), as well as reduce verbiage and write more straightforward sentences

- [x] Meet with Engineering to figure out all strings that are configurable per agency now
- [x] Map those strings to the content audit
- [x] Design to review and suggest where we can simplify, abstract text to remove agency specific business logic 
- [x] Identify gaps where the content audit shows the business logic is defined by an agency but it is not marked as a configurable string
- [x] Handoff of change -- where things need to be added as configurable strings
- [x] Add all final agency configurable strings to the onboarding list. (Work with Olivia)

Resources 
 - [Benefits Onboarding Template](https://docs.google.com/document/d/1D6li-i8ScY3D1-P-0qyh_9-UHwD6JGRyvf77V7LZncM/edit)

**Comment by thekaveman** [comment]
This sprint, @srhhnry to schedule meeting with engineers to talk about per-agency strings.

**Comment by srhhnry** [comment]
- @machikoyasuda to review content audit and suggest github tickets/how to structure changes into releases
- @srhhnry to organize changes into onboarding questions to give to @o-ram

**Comment by srhhnry** [comment]
Onboarding agency questions we need for configurable strings [can be found here](https://docs.google.com/document/d/1LGZ4_5sPSH6aB0FviOXh4EzeguYdasSXtTyRMt6KJQk/edit?usp=sharing).

**Comment by machikoyasuda** [comment]
## Variables the app already has and uses
These are the agency-specific variables the app already has and uses in `django.po`:
- `agency_short_name`: derived from `agency.short_name` - `MST`

These are the agency-specific variables the app already has in its models, available to use:
- `long_name`: `Monterey-Salinas Transit`
- `info_url`: `https://mst.org/benefits`
- `phone`: `xxx-xxx-xxxx`

These are proposed agency and verifier-specific variables and strings the app should have, based on this ticket: 

## Proposed variables
### Agency-specific: Needed for every agency
- `transit_type`: `public transportation` (MST) or `light rail` (SacRT)
- `fare_action`: `reduce fare`
- `rate`: `50%`
- `service_type`: `fixed route`
- `card_functionality`: `tap this card when you get on and off` (some agencies might not require tap off)

### Verifier-specific variables: Needed for every agency that has Agency Card verifier 
- `agency_card_name`: `Courtesy Card` [Cardholder is the assumed default name of person who has a card]
- `agency_card_id_type`: `number` (Could be `id` for some agencies...?)

### Verifier-specific strings: 
- `optional_verifier_eligibility_qualifier`*: `or an MST RIDES Paratransit Eligibility card`
- `verifier_requirement`*: `, but you will need to know the number.`
- `verifier_number_field_help`: `The number starts with a number sign (#) followed by five digits.`

## Proposed work strategy

_In order of least to most complex and priority:_
0. Variable-ize copy on the landing page/transit landing page. Ship this alongside changes to copy on these 2 pages.
1. Go through and double-check if the Copy Refactor (which is mostly cutting lots of sentences) can happen without the 2 stories below. If so, do the Copy Refactor first.
2. SBMTD-prep: Variable-ize agency card verifier variables and strings. Involves taking out the hard-coded `Courtesy Card` and variable-izing it.
3. SacRT-related: Variable-ize everything related to this sentence, the most complex sentence on the Eligibility page: `All [short name] transit benefits [action -e.g. reduce fare] by [standard rate of discount - e.g. 50%] for [affected service - e.g. fixed routes] on [transit options- e.g. public transportation].`

_Still thinking through all the details about the above, but this is where I've thought through so far_

**Comment by srhhnry** [comment]
@machikoyasuda can i close this or do you need access to the above^

**Comment by machikoyasuda** [comment]
@srhhnry Closing! Thank you 🤝
