### ISSUE TITLE
Improve copy for login flow

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1323]
- [ ] Break out as a small milestone
- [x] Update copy (simplify, check for accuracy)
- [x] Add UI features where helpful to improve user ability to understand Login
- [x] Think through buttons (have a create account versus login an A/B test in UserZoom)
- [x] Think about how we can pull info from the Help page into this page to help users
- [x] Follow up on Amplitude to see if we can set up a way to track that CTA event (even if we have to hack around the amplitude features)
- [x] Test: Are Seniors getting through the login--Are they clicking the right button to begin with? Do we need to create two different buttons: Sign in and Create account?

**Comment by srhhnry** [comment]
Chart tracking CTA: https://analytics.amplitude.com/compiler/chart/5l6g8zum

**Comment by vykster** [comment]
sounds great. let's close this issue.
