### ISSUE TITLE
improve informative actionable last page

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1324]
Think through illustrations that capture the process of tapping on and off the bus
(having fun with the solution!)
How can we change the last page–success–to be informative and fun

**Comment by thekaveman** [comment]
@srhhnry to join dev workshop next Weds 4/12 to discuss this idea in more detail.

**Comment by srhhnry** [comment]
Ended up working with a Cal-ITP illustration for now, and will revisit when we identify more illustration needs
