### ISSUE TITLE
Investigate Sentry error logging for form submission errors

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1334]
While testing #1332, we had a misconfigured setting that caused an error on a form submission (the Courtesy Card form) in the test environment.

This error was logged in Sentry, and included the full body of the request - because it was a form submission, this included the courtesy card number and last name fields.

If an error occurs on form submissions in production, the Sentry event could inadvertently contain user PII. Let's look into Sentry configuration to see about dropping this data from the event logs if possible.

## Acceptance Criteria

- [ ] Sentry receives no user-submitted form data in its error events

**Comment by thekaveman** [comment]
Follow up may be to look at if this is possible to define via code or configuration in this repository.

**Comment by angela-tran** [comment]
Looks like we can configure a `denylist` on `EventScrubber` when calling `sentry_sdk.init`: https://docs.sentry.io/platforms/python/data-management/sensitive-data/

Another more general approach to modifying events is by configuring a `before_send` function: https://docs.sentry.io/platforms/python/configuration/filtering/
