### ISSUE TITLE
Home & Agency Index - Update homepage copy + Create Agency text variables

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1386]
Update home page copy to be more concise for users.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/3673236/235732379-38c3534d-7010-4bb7-82b8-db328bcb7844.png">

## Acceptance criteria

- [x] Draft English Copy written
- [x] Copy ready for translation vendor 
- [x] Spanish copy added to app
- [x] Execute/ test new process for updating copy and working with content localization vendor

## Definition of "Done"

- [x] New homepage copy published in English
- [x] New homepage copy published in Spanish

## Links to user research, designs and resources

- [Finalized Figma file Desktop](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application))
- [Finalized Figma file Mobile](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application))

**Comment by vykster** [comment]
See details on: https://github.com/cal-itp/benefits/issues/1121

**Comment by machikoyasuda** [comment]
Update: 

Today, I sent a request to iBabbleOn for the homepage and agency homepage text.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/3673236/235814744-dfb731b2-59bf-4194-a244-60bbe832e6af.png">

These are the strings I sent in the request: 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/3673236/235814775-e0a8f73f-88d1-432a-b579-394fd84c958a.png">

And sent these screenshots and links for context:

The redesigned pages -
<img width="696" alt="image" src="https://user-images.githubusercontent.com/3673236/235814799-af08acd1-c2c0-49ed-98ed-c53709bb09f8.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/3673236/235814813-0ac6e95b-98fb-4bd7-8ceb-65dba0d3a9e7.png">
  
Just for context, I sent the current Spanish translations as well - 
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/3673236/235814827-520178b1-a27e-4106-a8ae-658911223fdd.png">

And I sent these links for more context: https://benefits.calitp.org/help and https://docs.calitp.org/benefits/.

**Comment by machikoyasuda** [comment]
This morning, I received an email from Salim at iBabbleOn.

- He updated my spreadsheet format to what they need:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/3673236/236045057-8b42efcc-43cc-4137-a6b9-b72cdeba34e8.png">

- Feedback on the inclusion of screenshots: ```The screenshots you sent look great and give us the context we need to translate these correctly. ```

And he sent a link to an Invoice with this note:

```
I estimate it will take 2 business days from time of payment. Payment can be made securely online with any major credit/debit card, e-Check, Apple Pay, or PayPal. Just press the green Pay button. It even works from your phone.
```

Payment options look like this:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/3673236/236045469-2cb33b3e-be35-46ba-964f-bee9de39d1e5.png">


Now, I will either need to pay the invoice myself, or have @indexing or @vykster or @thekaveman or someone else do it. I am not sure what credit card to use or how to pay for things for Benefits.

**Comment by machikoyasuda** [comment]
Status: Invoice is paid. Receipt was sent to my email and I forwarded to Vyki

Now, awaiting response of the translated strings from iBabbleOn.

**Comment by machikoyasuda** [comment]
Update: Thursday, May 4th - 11AM, received results:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/3673236/236334933-19894e0b-6eba-40e3-8e47-030bcb42c41a.png">


English | Spanish
-- | --
Get reduced fare on public transportation when you tap to ride | Obtenga una tarifa reducida en el transporte público cuando toque para viajar
Cal-ITP Benefits connects your transit benefit to your contactless card | Cal-ITP Benefits conecta su beneficio de tránsito con su tarjeta sin contacto
Get reduced fare on MST public transportation when you tap to ride | Obtenga una tarifa reducida en el transporte público MST cuando toque para viajar
Get reduced fare on SacRT light rail when you tap to ride | Obtenga una tarifa reducida en el tren ligero SacRT cuando toque para viajar
Choose your provider | Elija su proveedor

**Comment by indexing** [comment]
@srhhnry I propose we use this initial set of translated strings as the basis for the copy master for Spanish. When I request the full translation from our translation service in #1410 , I will exclude these strings. 

@machikoyasuda Product will take over the work of getting copy translated by our vendor going forward. Once we finalize some additional copy this month, I will submit as complete a set of strings as possible. Do you want to add the translated copy in this issue to the app and close it or wait until we have all changes and do them as a batch?

**Comment by indexing** [comment]
Thanks for the suggestion @machikoyasuda. Having "stretch" work in every sprint is a great idea, as well as always including some small, user-focused fix. In addition to adding this issue to the sprint, I also included #1432 as part of implementation of the veterans enrollment flow.

**Comment by machikoyasuda** [comment]
Started working on this and realized that we do not have a programmatic way to determine if an agency needs copy that specifies transit mode (e.g. `light rail` vs. `public transportation`).

**Comment by srhhnry** [comment]
I added that question to [this google doc ](https://docs.google.com/document/d/1LGZ4_5sPSH6aB0FviOXh4EzeguYdasSXtTyRMt6KJQk/edit?usp=sharing) of agency onboarding questions we need for configurable string copy. I think it makes total sense to default to "public transportation" unless an agency specifies (i.e. SacRT and light rail). 

My hope is that a future iteration of the admin interface (which is either agency or customer service facing) would be the place to capture/update that information (e.g. if SacRT adds transit bonuses to buses, then they are responsible for that information being updated on Benefits).

**Comment by indexing** [comment]
@srhhnry Thanks for noting this gap AND for adding a question to our documentation. @o-ram and I are now working to create a single document to guide agency onboarding: [Cal-ITP Benefits Transit Provider Onboarding](https://docs.google.com/document/d/1D6li-i8ScY3D1-P-0qyh_9-UHwD6JGRyvf77V7LZncM/edit?usp=sharing)

After a quick review, it appears the questions in the doc you link to above and the questions in the document above are similar or the same. Can I ask a favor? Please add the new question to the official onboarding doc and deprecate (or preferably delete) the separate doc.

**Comment by srhhnry** [comment]
No prob! On second read my comment was totally not clear. That question HAD been added back in April as part of a broader process to onboard new agencies. The new doc is certainly more up to date, as [this doc](https://docs.google.com/document/d/1LGZ4_5sPSH6aB0FviOXh4EzeguYdasSXtTyRMt6KJQk/edit?usp=sharing) was never meant to be client facing and was only to document our needs (and is part of [this issue](https://github.com/cal-itp/benefits/issues/1322))

I'll go ahead and delete it.

**Comment by machikoyasuda** [comment]
Full list of fields to add to Transit Agency:
- [transit type || transit options] - public transportation, light rail
- [action] - reduces
- [rate of discount] - 50%
- [affected service] - fixed route
- [transportation type] - bus, light rail
- [card functionality] - tap this card

Fields for Eligibility Verifier for Agency Card:
- [agency card] - Courtesy Card
- [optional qualifier] - "Courtesy Card or an MST RIDES Eligibility card"
- [qualifier] - "you will need to know the number"
- [qualifier] - "The number starts with a number sign (#) followed by five digits."
- [ID number type] - "number"
- [identity marker] - "last name"
- [qualifer] - "This is a 5-digit number on the front and back of your card."

**Comment by machikoyasuda** [comment]
Separating this out into 3 tickets:
- Creating variables
- Using variables in _new_ copy (for Home and Agency Index)
- Using variables in _existing_ copy (currently awaiting Spanish translation)

**Comment by machikoyasuda** [comment]
Validating on dev-benefits.calitp.org



![Image](https://github.com/cal-itp/benefits/assets/3673236/8a292e6e-ad44-4f72-89c1-bf01d5df527e)



![Image](https://github.com/cal-itp/benefits/assets/3673236/d0e619d4-bf93-4b46-bd73-f7ce487659fb)



![Image](https://github.com/cal-itp/benefits/assets/3673236/27cb1d1c-e066-4538-8ece-293ae918e4fb)
