### ISSUE TITLE
Scope SBMTD Older Adults Deployment

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#1395]
## Acceptance Criteria

- [ ] Stories published for SBMTD with the senior discount / Login.gov integration

## Resources

- [SBMTD Onboarding Interview Doc](https://docs.google.com/document/d/1gslfEV_TjWdRmMNdOe90pDUWbm8xyDZC/edit#heading=h.gjdgxs)

**Comment by machikoyasuda** [comment]
- Back-end for new agency: #1588  #1631 
- Front-end for new agency: #1444 #1634 #1223

**Comment by thekaveman** [comment]
I think we can call this closed @indexing?
