### ISSUE TITLE
Update english alt text for bank icon

### ISSUE THREAD

**Issue by calexity** [cal-itp/benefits#14]
- Line 227 Alt text can be: "Bank card with contactless symbol and checkmark"

https://github.com/cal-itp/benefits/blob/1304855d1dcd50562d7a2645a7179c1fdd824d54/benefits/locale/en/LC_MESSAGES/django.po#L227

- Line 201 Alt text can be: "Bank card with contactless symbol"

https://github.com/cal-itp/benefits/blob/1304855d1dcd50562d7a2645a7179c1fdd824d54/benefits/locale/en/LC_MESSAGES/django.po#L201

- I can't find the error one but error icon alt text can be "Bank card with contactless symbol and question mark"

**Comment by thekaveman** [comment]
I pushed 53c5448 with a bunch of updates for the icons.

We still need alt text for the `msgid "discounts.success.image"` - the final sucess / call to action image on the last page (not the icon).

**Comment by thekaveman** [comment]
#11 is merged.
