### ISSUE TITLE
Design and Development to work together to ensure .po files are synced with Google Sheets and Figma

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1404]

**Comment by srhhnry** [comment]
@indexing adding you to this ticket--feel free to close or adjust based on the process you've outlined in Miro

**Comment by indexing** [comment]
I spoke with @machikoyasuda about this topic this morning. 

Our near-term to goal is to establish a source of truth for copy in the Benefits application. Using [this process](https://miro.com/app/board/uXjVMEkbxdM=/?moveToWidget=3458764555469810279&cot=14), we can now all point to the Google Sheet as that source of truth. The trade-off, for now, is that a dev must manually keep the copy in the code aligned with the copy Google Sheet. Machiko is on-board and okay with this approach.

**Comment by srhhnry** [comment]
Wahoo! Awesome! Thanks @indexing and @machikoyasuda
