### ISSUE TITLE
User Test: Are Seniors getting through the login--Are they clicking the right button to begin with? Do we need to create two different buttons: Sign in and Create account?

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1405]
Adding this user test to backlog for testing later in our UserZoom account billing year

**Comment by srhhnry** [comment]
Login.gov has updated their sign in page (per [this Slack comment](https://compilerla.slack.com/archives/C02GQ7AJXQE/p1686598131732519))

**Comment by indexing** [comment]
@srhhnry Can we close this issue or is do we still want to run tests using the new Login.gov layout?

**Comment by srhhnry** [comment]
My instinct is that we don't need two buttons, and I think it might be confusing. Creating an A/b test feels very low priority to me and I could see delaying this till later in the year (if conducting it at all). Otherwise, I would close this.

**Comment by thekaveman** [comment]
The other thing here is we may not be able to control this experience from Benefits. We pass the user through the IdG, which connects them with Login.gov. I don't know if there is a way to pass them through in one or the other mode of "create account" or "sign in".
