### ISSUE TITLE
Add layers of auto-layout to Full Benefits board to emulate developer approaches

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1412]
[Developer Benefits Full App Board](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5766%3A22626&t=ImMxFI3ceP11P5dl-1)

As time permits, Design will add in layers of autolayout to components and UI elements to better emulate screen resizing and match developer techniques. This helps screens to better match real-world scenarios and creates clarity for developers.

**Comment by srhhnry** [comment]
Add autolayout to 
Components
- [ ] Agency Selection Cards
- [ ] Logos
- [ ] Icons
- [ ] Navigation
- [ ] Form inputs
- [ ] Buttons
- [ ] Modals

**Comment by indexing** [comment]
Sufficient work is complete on this issue. More refactoring will take place in future design efforts.
