### ISSUE TITLE
Adjust Style Guide and Library for Benefits

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1415]
Double check the colors on the Style Guide and ensure they match in the library and then rename the colors to be more explicit and to work with the new dev process of CSS variable naming (also fyi, devs are using rgb)

**Comment by machikoyasuda** [comment]
https://github.com/cal-itp/benefits/issues/1389#issuecomment-1593876685

The colors in this GitHub issue (https://github.com/cal-itp/benefits/issues/1389) are different from what is on Figma:
<img width="453" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/a3c52b8f-1ccd-453a-a7ce-a3bc74ef58ad">
<img width="1096" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/e1044b9c-92bb-4bc2-ac86-1a1d4f07a5fe">

And the colors in the Typography section on Figma don't match with the Color section on Figma:
<img width="714" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7754fbb5-b47b-4e21-9cda-11d3512cc095">

**Comment by machikoyasuda** [comment]
Is this ticket a duplicate of https://github.com/cal-itp/benefits/issues/1423?

**Comment by indexing** [comment]
@srhhnry Can we close this issue?

**Comment by srhhnry** [comment]
Yup!
