### ISSUE TITLE
Color Workshop on Cal-ITP Blue

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1423]
@segacy1 and @srhhnry met to work on improving accessibility for Cal-ITP properties by increasing contrast on the primary blue used on these sites (known as Cal-ITP blue). We also adjusted the hover color to match the new blue. And for Benefits, the text link color was shifted to the new blue as well.

**Comment by srhhnry** [comment]
Scheduled for June 21st

**Comment by srhhnry** [comment]
@angela-tran @machikoyasuda 

The new Action Primary (Cal-ITP blue) color for Benefits, MobiMart, and Cal-ITP.org is: rgba(4, 91, 134, 1) or #045B86
The new Hover color for Benefits, MobiMart, and Cal-ITP.org is: rgba(4, 72, 105, 1) or #044869
The new Text Link color for Benefits is: rgba(4, 91, 134, 1) or #045B86
The new Hover link color for Benefits is:  rgba(4, 72, 105, 1) or #044869

Those colors have been updated in Benefits and MobiMart/Cal-ITP and can be seen in the Benefits Style Guide [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=4890%3A17182&t=w58kxu3smXZ6F1kD-1)

**Comment by machikoyasuda** [comment]
@srhhnry Thanks for this update!

GitHub ProTip™️ - When typing in colors, if you wrap the color code in backticks (`), then a color chip will appear next to it. I went ahead and did that for your comment above, so we can see the colors!

**Comment by machikoyasuda** [comment]
Can this ticket (https://github.com/cal-itp/benefits/issues/1389) be closed, in favor of this most current one?

**Comment by srhhnry** [comment]
That protip is very cool. And yeah, I went ahead and closed #1389 after updating the typography page in figma

**Comment by srhhnry** [comment]
@machikoyasuda checking in on whether I can close this ticket

**Comment by machikoyasuda** [comment]
@srhhnry Yes! Once dev is ready to make this color change, we'll make a ticket to track it.
