### ISSUE TITLE
Define EligibilityType for veterans

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1426]
Starting with MST for launch. Link to Payment Enrollment group.

**Comment by machikoyasuda** [comment]
- Done: Set `mst-veteran-group-id` in KeyVault - Development
- Done: Set `mst-veteran-group-id` in KeyVault - Test
- Done: Set `mst-veteran-verifier-name` in KeyVault - Development
- Done: Set `mst-veteran-verifier-name` in KeyVault - Test
