### ISSUE TITLE
Veteran eligibility enrollments are tracked in the Amplitude enrollment metric

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1429]
Depends on #1450

**Comment by machikoyasuda** [comment]
## Flows to test
- User chooses Veteran
- User goes thru Veteran flow and returns enrollment, success
- User goes thru Veteran flow and returns enrollment, failure

**Comment by machikoyasuda** [comment]
This ticket is to be completed _after_ the rest of the tickets from this sprint are deployed.

**Comment by thekaveman** [comment]
Still blocked, see note https://github.com/cal-itp/benefits/issues/1450#issuecomment-1615194260

**Comment by machikoyasuda** [comment]
Tested one event on test-benefits.calitp.org: Able to successfully track `selected eligibility verifier` event and get the VA data back ---

<img width="579" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/eb4b876a-6064-4a79-9e1a-7fead0b6be35">

<img width="893" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/b944a6c5-7f0c-464f-8d64-f9abd6548db0">

**Comment by angela-tran** [comment]
John let me know that the IdG changes have been pushed to UAT. I tested the Login.gov flow and the veteran flow, and they worked! I'm having trouble finding my events in Amplitude though. Does someone else want to try it out?

**Comment by angela-tran** [comment]
When I try to look at our usual charts but for `(Test) Benefits` instead of `(Prod) Benefits`, Amplitude shows me this:
![image](https://github.com/cal-itp/benefits/assets/25497886/c2f72448-5e33-49c9-9b44-a10eb34010d0)

**Comment by machikoyasuda** [comment]
@angela-tran I made a chart in Amplitude to track the following events on (Test) Benefits: https://app.amplitude.com/analytics/compiler/chart/ff2lp8az - Start sign in, Finish sign in and Enroll, all filtered by users who select to verify with VA.gov



![Image](https://github.com/cal-itp/benefits/assets/3673236/c9a1aa0b-ac64-432e-a510-43b7082ebfad)

I can see in the chart that you were able to go through all 3 events. I was able to start sign in, and I tried the test credentials with ID.me, went thru the fake phone auth part, but wasn't able to successfully get back to the Benefits app. So you can see my uncomplete attempt as one of the blue events on the chart.

**Comment by thekaveman** [comment]
Closing this as complete, we can see Veterans events coming through to Amplitude.
