### ISSUE TITLE
Enrollment Success - Add illustration, update copy

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1432]
Update the confirmation view a rider sees after successfully completing an enrollment pathway (senior, veteran, agency card).

- [x] Add illustration
- [x] Update copy
- [x] Remove expiration date copy/strings

<img width="640" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7f5f45d2-f8cd-4d2b-b7f9-e7630db6c560">

## Definition of Done

Implementation matches the mockups below on both mobile and desktop browsers.

- [Mockup (Desktop)](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=8945%3A47138&t=83o3CUb7RP3oO5Hb-1)
- [Mockup (Mobile)](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=9277%3A64438&t=83o3CUb7RP3oO5Hb-1)

**Comment by machikoyasuda** [comment]
Spanish translation not ready.

**Comment by machikoyasuda** [comment]
@srhhnry 

![Image](https://github.com/cal-itp/benefits/assets/3673236/52dedbc7-1f07-47b4-8bab-45f3385c40c3)

This is what Enrollment Success for the Agency Card flow looks like on Production. Is this Figma design intending to delete the entire **You may need to reapply for transit benefits at a later date** / **In the future, you may need to re-register for Benefits to continue using contactless payment cards. You will also need to reapply if you choose to change the bank card you use to pay for transit service.** part?

**Comment by srhhnry** [comment]
Yup! That copy has all been consolidated into one section. The original intent was to hedge against future changes from MST regarding the courtesy card, but it's convoluted for the user and, with the ongoing/evolving shifting of copy responsibilities to agencies, not something we should be accounting for right now. 

So, all flows* now get the same success page, with the distinction of flows that user Login.gov having a sign out reminder. 

(*The copy will change slightly with the introduction of the CalFresh flow, but formatting will be very similar)
