### ISSUE TITLE
Design modal on the [home indirect entry] view to accommodate 4 agencies

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1444]
Ensure the indirect entry modal can accommodate up to 4 agencies (depending on evaluation of this approach). We need to accommodate at least three agencies by the end of the year, but four is a better target.

**Comment by srhhnry** [comment]
Rough draft completed today. Can be [seen here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=9799%3A52593&mode=design&t=tmnfTqohN6GLSQtu-1).

**Comment by srhhnry** [comment]
@indexing these screens are now ready for review

**Comment by indexing** [comment]
@srhhnry I reviewed the design. Overall it works! When we take the layout from rough draft to final design, I'd like to added the following as acceptance criteria. For some reason, I don't see and thus cannot edit the body for this issue.

# Acceptance criteria

- [ ] Create a component in Figma for the transit card to standardize the layout. (Use auto layout if possible.)
- [ ] Specify a uniform size for the agency image asset in the component using dimensions with a common denominator of 4, e.g. 64 x 128. (This will ensure we ask agencies for an asset will work with our design.)
- [ ] Specify a max character length for agency name. (Ensures we ask for a name that will work with the design.)
- [ ] Specify default sort order for the list of agencies.

**Comment by srhhnry** [comment]
A note about the acceptance criteria:

1. Gov agencies are not the most most reliable sources of their own graphics. Files can be from years ago with no updates (e.g. .indd) have been copied over in weird ways (e.g. using a degraded .jpg), or the agency might not have a visual person on staff who can confidently hand over the right file. Our general approach has been to ask for the largest logo file size they have, and adjust from there. This approach works currently because we aren't onboarding an agency every month. 

I very much think asking for a uniform size or fidelity will be necessary at scale, but also anticipate we'll be shifting the design for agency selection (and benefit selection) before then. That ALL said, sizes for different types of icons listed in the next comment.

**Comment by srhhnry** [comment]
Card components can be found [here in the components library](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=2-11&mode=design)

Working on adding autolayout and updating all designs to include these components

**Comment by srhhnry** [comment]
Desktop autolayout update is almost complete--still working out a bug wherein I can swap logos seamlessly in the master component but not in an instance of the component.

**Comment by srhhnry** [comment]
I've created two components that can be found in [the component library](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=2-11&mode=design): a desktop agency selector card and a mobile agency selector card. Both components make use of autolayout. There's a Figma glitch when swapping out logos that are not the same dimensions on an instance of a component (the logo swap works perfectly on the master component). But I feel this quirk can be handled manually in the example/prototype flows.

**Comment by srhhnry** [comment]
Created mobile and desktop logo components (based off @indexing's helpful work) and now the Agency Selector cards (both desktop and mobile) are complete and added to the [Dev board](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5766-22626&mode=design). 

[Agency Logo component ](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=2-11&mode=design)sizes are:
Desktop: 148 x 72
Mobile: 52 x 36

Layout instructions for agency selector modals can be found in the[ styleguide](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=4890-17182&mode=design) in Layout Notes

**Comment by indexing** [comment]
@srhhnry When I was reviewing the base component for the mobile agency selector, I noted the the current version of the agency image in the component doesn't match the spec you note above  (52 x 36). https://share.getcloudapp.com/GGu5eRGd

**Comment by srhhnry** [comment]
Yeah, I can't figure out a way to make that component adjustable to differently sized icons and text that wraps to the second line without using hug, which shifts the dimension. Open to suggestions there. 

The mobile logo components all fall within 52 x 36 however:


![Image](https://github.com/cal-itp/benefits/assets/5394204/4781aa2a-2d74-4888-84e2-bb1bbd2b493a)

**Comment by machikoyasuda** [comment]
Closing / dev implementation ticket is now here #1634

**Comment by indexing** [comment]
@segacy1 I'm reopening this issue to address the refinements we discussed to the agency card desktop and mobile components in Figma.

- [ ] Mobile component: Relocate agency logo to the left side of the component to match design conventions for image placement in lists
- [ ] Mobile component: Ensure mobile agency logo spec dimensions noted in comments above work at 1x (320 x 568).
- [ ] Mobile component: Ensure agency name fits on two lines. (We can ensure it fits by limiting character count or via font size. I'd propose we aim to support 36 – 40 characters for max length comfortably on two lines using the mobile agency asset dimensions. That length needs to work for desktop as well.)
- [ ] Desktop component: Ensure agency name fits on two lines. (We can ensure it fits by limiting character count or increasing the width of the card component. I'd propose we aim to support 36 – 40 characters for max length comfortably on two lines using the desktop agency asset dimensions. That length needs to work for mobile as well.)
- [ ] Modal supports four transit agency cards, three agency cards, two agency cards, and one agency card.

**Comment by segacy1** [comment]
I've created a new component for desktop and mobile. You can see it in the mockups [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=9290-79490&mode=design&t=UavIcbmGFB9IeHzt-4) or in this [new library](https://www.figma.com/file/IuVNsLccmvumsUzW7IC5BF/Cal-ITP-Benefits-Component-Library?type=design&node-id=20-100&mode=design&t=5X2iCpUp9VJ2K20s-4). As discussed, we'll focus on making it work for three agencies since we don't foresee a fourth being added immediately.  

A few additional notes:

- I've removed the "ready for dev" status so we can review with the team
- We discussed transitioning benefits screens to match the 8pt grid/12 column layout we use for mobimart and calitp.org. I've created the modals based on the new screen sizes, which means the margin is slightly off on benefits mock ups. For example, this [mobile modal](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=8191-37187&mode=design&t=UavIcbmGFB9IeHzt-4) on an updated screen size would have 16px on either side, but on the current benefit mockups it has an uneven 20/19px. Not sure how we'd want to address this, but I could definitely prioritize updating all the final mocks in the app this month if we'd like?

**Comment by segacy1** [comment]
Just a note that while this ticket is in review, I've reverted to the original modal design on the Developer Full App page in Figma, which is marked as `ready for dev`,  and added the proposed design to our new library project [here](https://www.figma.com/file/IuVNsLccmvumsUzW7IC5BF/Cal-ITP-Benefits-Component-Library?type=design&node-id=20-100&mode=design&t=I5dytp7HkId3zHHy-4)

**Comment by segacy1** [comment]
Proposed design has been updated and lives in the new [Benefits library project](https://www.figma.com/file/IuVNsLccmvumsUzW7IC5BF/Cal-ITP-Benefits-Component-Library?type=design&node-id=20-100&mode=design&t=hqWK0FxGZEuMfoZS-4).
