### ISSUE TITLE
Run user testing on CalFresh clickable prototype

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1469]
Similar to the veteran flow test, we should run a test of the desktop prototype of the CalFresh flow. 

- 6 participants
- Screener includes whether or not participant has ever qualified for CalFresh
- Possible to run the test before presenting to the CalFresh team (aiming for week of July 10)

To Do Items
- [x] Create desktop prototype
- [x] Create user testing plan and submit for approval
- [x] Create UserZoom test based on user testing plan
- [x] Upon approval launch test to 5 qualified participants 
- [x] Review test (disqualify participants if necessary)
- [x] Evaluate results
- [x] Write summary
- [x] Add changes to flow as needed

**Comment by srhhnry** [comment]
@vykster does this seem useful?

**Comment by vykster** [comment]
YES

**Comment by srhhnry** [comment]
Prototype can be [found here](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?page-id=5281%3A19859&type=design&node-id=9889-91957&viewport=-952%2C-153%2C0.06&t=Gz5CQYewZYD41BUe-8&scaling=scale-down&starting-point-node-id=9889%3A91957&show-proto-sidebar=1&hotspot-hints=0&hide-ui=1)

**Comment by srhhnry** [comment]
User Testing Summary can [be found here](https://docs.google.com/document/d/1WFGf4-HtSfMJ4A43rROer7rvMfqh-NSriGv5mGxkmlc/edit?usp=sharing)

**Comment by srhhnry** [comment]
Test is completed! It took a day or two longer than expected but looks good. Working on the summary results now.

**Comment by srhhnry** [comment]
Summary needs one more additional pass and then will be considered complete.

**Comment by srhhnry** [comment]
Summary results can [be found here](https://docs.google.com/document/d/1g-a_5AeU_T4a6Ar2Rj65_cxwjdSn52-lyS4Bb84xytE/edit?usp=sharing).

Updates to Figma include: 
1. Find a location for information about how Benefits relates to the CalFresh account
2. Figure out how to warn users not to enter their CalFresh card information in Littlepay
