### ISSUE TITLE
Eligibility Confirm - Update copy (CC flow)

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1482]
DELETION remove 2 sentences

![Image](https://github.com/cal-itp/benefits/assets/3673236/1947acbe-1d88-4ba9-9a29-1accb4fc39cb)

![Image](https://github.com/cal-itp/benefits/assets/3673236/56e89527-9a07-471f-bc9d-05d5ea569a59)

Remove the highlighted sentences

**Comment by machikoyasuda** [comment]
confirming on dev
<img width="1506" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/79567a6e-29d6-41d2-8986-3182b91510f0">

noticed a small typo, will fix
