### ISSUE TITLE
Buttons: Lowercase pronoun in all Buttons

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1483]
Choose Your Provider -> Choose your Provider
Choose This Benefit -> Choose this Benefit
Connect Your Card -> Connect your Card
Check Status -> Check status

**Comment by machikoyasuda** [comment]
Confirmed on dev: https://dev-benefits.calitp.org/



![Image](https://github.com/cal-itp/benefits/assets/3673236/24c672f7-d8cf-47f2-9b8e-8152b86f445f)


![Image](https://github.com/cal-itp/benefits/assets/3673236/3a802da2-c71a-4b14-bdb6-391d5e026b03)




![Image](https://github.com/cal-itp/benefits/assets/3673236/faf438f5-871a-41b2-a215-fe2f8d1e75ae)



![Image](https://github.com/cal-itp/benefits/assets/3673236/457eb6c4-80a9-4fd8-b33b-70313cbd2c0b)



![Image](https://github.com/cal-itp/benefits/assets/3673236/bf87f259-032a-4adb-a5a2-b91bc2d0ecd6)



![Image](https://github.com/cal-itp/benefits/assets/3673236/7231a74f-e9de-48c0-a4fd-b62044f6fcd6)



![Image](https://github.com/cal-itp/benefits/assets/3673236/303b9b14-da2a-4e0a-99e1-5ba47aa52372)
