### ISSUE TITLE
Evaluate MST configuration to support veterans (product codes)

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1485]
## Todo

- [x] Create a group for MST Veterans in production
- [x] Link group to products as specified below

**Comment by o-ram** [comment]
MST has created the discount product for the veterans group! I only have the product code. If ID is needed, let me know and  I'll go back to MST for that as soon as I'm able.
**Product code = VETDISC**

![image001 (10)](https://github.com/cal-itp/benefits/assets/92001064/88cb0d5d-4486-47ac-b58a-2aaab5f906c5)

The veteran group should have this product associated with it along with the existing discount caps. Discount caps listed below by their product code and ID, if known.

- 2 Hour Cap Discount (Product ID: 4f945c2e-7aad-4e1e-a3b0-043e92c055e9)
- Day Cap Discount (Product ID: 380991bd-70d2-42ff-9219-cb105818bdde)
- 7 Day Cap Discount (Product ID: 1b82328e-a308-4f8e-bb93-0a1a13e6c849)
- 31 Day Cap Discount (Product ID: ?. This has never been hit, so I can't easily look it up)

**Comment by thekaveman** [comment]
We'll use the new functionality in the [`cal-it/littlepay`](/cal-itp/littlepay) tool to link these groups <> products.

**Comment by thekaveman** [comment]
See also https://github.com/cal-itp/benefits-secrets/pull/36

**Comment by thekaveman** [comment]
Note we won't be using `cal-itp/littlepay` until we find out if there are more differences between Groups created and managed under the different APIs.

**Comment by angela-tran** [comment]
@o-ram Thank you for the IDs in https://github.com/cal-itp/benefits/issues/1485#issuecomment-1690864286! 

I took a look at MST's products today using the Customer API, and I'm seeing that there are 2 products with `VETDISC` as their `product_code`. 

Can you ask MST for the ID of the product they'd like us to use for veterans?

**Comment by o-ram** [comment]
@angela-tran the ID that should be used is dcff72c9-a8e3-493b-895d-ef95dbff5152

**Comment by angela-tran** [comment]
@indexing @thekaveman @machikoyasuda @o-ram --

I've finished creating a group for veterans and linking those 5 products to it.

Documentation of the current assignments can be seen in the pull request that's linked to this issue - https://github.com/cal-itp/benefits-secrets/pull/40/files

**Comment by angela-tran** [comment]
I don't think there's more to do for this ticket, so I'm gonna close it ✔️
