### ISSUE TITLE
Disabled Riders Research: Analysis and Presentation

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1497]
Rough draft of analysis including:
- [x] Interviews with SBMTD 
- [x] Interview with MST
- [x] @segacy1 to write summaries from secondary research
- [x] @srhhnry to write summaries from primary research
- [x] Finish writing Design Directions
- [x] Finish writing Policy Recommendations

Google Slides presentation outlining: 
- [x] 1-2 standardized operational definitions of disability that can be digitally verified
- [x] 2-3 methods of verifying status of disabled riders
- [x] Overview of interviews (who we interviewed, etc)
- [x] Quotes 
- [x] Design Directions
- [x] Examples of 3 design directions in Figma
- [x] Policy Recommendations
- [x] Pointing to methods or products we can integrate into Benefits
- [x] Resources section (with links to notes/videos)

Presentation will be scheduled for late November or early December

- [x] Present research to internal team and gather feedback.
- [x] Incorporate feedback and create a final draft of the presentation. 

More info [here](https://docs.google.com/document/d/1xAIT8YicUx3CAvVVvaNbU1jBcT6ySrrRB2r07jX7RDg/edit?usp=sharing)

**Comment by srhhnry** [comment]
Analysis document can be found [here](https://docs.google.com/document/d/1_c0QdfqR9rm8lDWMq81GaVhaolTpWSDwIvuGc5-u11Q/edit?usp=sharing)

**Comment by srhhnry** [comment]
Anticipating analysis will be complete and written by Friday, Aug 11th. The presentation will be created the week of August 14th.

**Comment by indexing** [comment]
@srhhnry Can you leave one final update on this effort be your leave?

**Comment by srhhnry** [comment]
Research is complete and a draft presentation is currently in progress [here](https://docs.google.com/presentation/d/1cVbbiIURwP87wOCiaSu1KGhXfwzebcPMxjpRvyKJKNE/edit?usp=sharing). @segacy1 has taken over as lead for this project and will be finishing the project, as well as presenting in the Fall.

**Comment by segacy1** [comment]
Update: Vyki, Andy, and I will review this presentation on 10/25.

**Comment by indexing** [comment]
@segacy1, @vykster and @indexing met on 10/25. We provided feedback. Segacy is refining the presentation and will meet with Vyki to discuss further refinement. 

@segacy1 When you have a moment, please review and update the checklist above regarding presentation content.

**Comment by indexing** [comment]
@segacy1 Bump. Please see above.

**Comment by segacy1** [comment]
@indexing I don't have edit access for Sarah's comment, but everything is complete except the 'Design Directions' section revision incorporating the team's recent feedback.

**Comment by indexing** [comment]
@segacy1 Thanks for the update! I know we are close, so I want to set a path for you to be able to close this issue ahead of the holidaze. I added three new checkbox items to capture the work you are doing now. Let me know if there are any additional items to add. Otherwise, I believe we can consider this our path to DONE.

**Comment by segacy1** [comment]
@indexing I can't check off the last item, but we're all set to mark it as done!

**Comment by indexing** [comment]
@segacy1 I checked off the last item in the list. For reference, please provide a link to the finished presentation here in the issue and mark it done! Thanks.

**Comment by segacy1** [comment]
Adding here: [Disabled Riders Presentation](https://docs.google.com/presentation/d/1cVbbiIURwP87wOCiaSu1KGhXfwzebcPMxjpRvyKJKNE/edit?usp=sharing)

Just a note that Sarah will be giving the final presentation. She and I will review when she's back from mat leave.
