### ISSUE TITLE
Split language files across Django apps

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1525]
Once the language strings are fully refactored into the templates per #1442, we should be able to improve how `.po` files are managed.

Our [current settings](https://github.com/cal-itp/benefits/blob/dev/benefits/settings.py#L186) override the location Django looks for `.po` files, to the `locale/` folder in the top-level app directory:

```python
LOCALE_PATHS = [os.path.join(BASE_DIR, "benefits", "locale")]
```

But we don't need this override; Django's default is to look in a `locale/` folder under _each app directory_, such as `benefits/core`.

This means we can separate `core` strings from `eligibility` strings from `enrollment` strings and have each live in their own files.

Splitting the files like this should streamline updates, especially when multiple engineers are working on them at the same time. By representing different parts of the app in different files, we should be able to reduce merge conflicts by staying more focused. And smaller files with fewer `msgid` are probably easier to manage.

## Acceptance Criteria

- [ ] The `LOCALE_PATHS` setting override is removed
- [ ] Each app `core`, `eligibility` and `enrollment` has its own `locale/` directory
- [ ] Language strings for each app are represented in the app's `.po` files
- [ ] `msgid` for each string in each app starts with the app's name, e.g. `core.`, `eligibility.`, `enrollment.`
- [ ] `bin/makemessages.sh` still works
- [ ] `bin/init.sh` still works

**Comment by angela-tran** [comment]
At the time, it seemed like this would improve developer experience, but it's become more apparent that many message strings are shared across apps, so closing as not planned.
