### ISSUE TITLE
Modal dialog link in radio button has inconsistent select behavior

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1526]
There's some inconsistent behavior with closing the modal and what happens to the radio button.

See this GIF where I close the modal by:
 - clicking the X
 - pressing the Esc key
 - clicking off the modal

In the last case, the radio button gets selected.
![benefits-login-gov-help-modal](https://github.com/cal-itp/benefits/assets/25497886/4dc56b2a-ee86-4014-991a-9429e2aaf30f)

_Originally posted by @angela-tran in https://github.com/cal-itp/benefits/issues/1524#issuecomment-1633250362_
            
### Additional context
An attempt to fix this was made in #1524 by consuming the click event, but because the modal content has clickable elements, we can't use that solution.

**Comment by indexing** [comment]
@machikoyasuda Are we addressing this issue as part of our work to optimize the modal component?

**Comment by machikoyasuda** [comment]
@indexing No. The modal component optimization is purely all CSS. There's nothing CSS can do to change this behavior. I believe this bug would require digging into Bootstrap JS and writing some custom JS to change the behavior.

**Comment by machikoyasuda** [comment]
I think I figured out the issue: https://codepen.io/machikoyasuda/pen/vYqENKx

Clicking on the backdrop part of the modal div also triggers clicking on the radio button. The default event bubbling from this click needs to be prevented manually. But also, clicking on the Login.gov text link in the modal shouldn't be deleted. So I came up with this code so far:

```
$("#modal--login-gov").on('click', function(event) {
    console.log("clicked modal 1");
    console.log(event.target);
    if (!(event.target instanceof HTMLAnchorElement)) {
       event.preventDefault();
       event.stopPropagation();
   }
});
```
