### ISSUE TITLE
Update copy for Help page

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1544]
## Acceptance Criteria

- [x] Help page has copy that matches what is shown in Figma (Developer Benefits Full App)
- [x] For Spanish translations, just put TODOs for now

## Additional context
The Help page was updated to match copy shown in the help modal dialogs.

**Comment by angela-tran** [comment]
Not sure if this is ready to be worked on. There are several comments in Figma on the Help Page screen in "Developer Benefits Full App" from 2 months ago that say "WIP" and "Fix".

Also, the punctuation on links is not consistent (some have a period, some don't) so that is an open question right now.

**Comment by srhhnry** [comment]
Took care of the comment that said WIP (it was from way before we shifted to the new copy process), but don't see any other comments on those screens that are ambiguous (just tag me if you find any). 

Regarding the punctuation I've noted this in the Style Guide in the Text Layout section, but I can see that page not getting a lot of traffic. Essentially all sentences in body copy should receive punctuation, including sentences that end in icons. Unfortunately, the Google Sheets sync we use doesn't allow for adding extra spaces that would be consistent between desktop and mobile (with space added to account for the Figma component of the external link button). It's totally a pain, and I'm sorry it's not clear. I'll try to figure out a way to work around that limitation, but in the meantime, yes, punctuation on links.

**Comment by angela-tran** [comment]
Thank you @srhhnry !

**Comment by srhhnry** [comment]
lol, @angela-tran I just saw all of those comments on the mobile help page (they weren't loading or I was zoomed out or something crazy was happening). I think they primarily relate to that issue with Google sheets and punctuation, but if any of them don't I'll let you know.

**Comment by angela-tran** [comment]
Question for @thekaveman and @machikoyasuda: since certain sections of the Help page are supposed to be the exact same copy as what's in the Help modals, should we use the same PO file entries? Or have separate, duplicate entries (one set for the modal, one set for the Help page)?

Here is the Login.gov help modal (in the app) and help page section (from Figma) for example:
![image](https://github.com/cal-itp/benefits/assets/25497886/3eb7cf9b-fd6a-491f-8031-02eb88e11dbb)

![image](https://github.com/cal-itp/benefits/assets/25497886/6a1c5f55-c4c4-4e17-a302-b6c34866f8f6)

**Comment by machikoyasuda** [comment]
@angela-tran I'd be okay with that, but, I think for https://github.com/cal-itp/benefits/issues/1525 to work, we'd have to have them separate.

**Comment by srhhnry** [comment]
I am generally in favor of removing things from the Help page (and putting them into context--eg. modals) but we agreed to maintain the Help as a repository of all potential user questions (this was at either a standup or handoff several weeks back). 

So yes, reusing makes sense. That's how I've approached it in the designs (that the modals and the help page are exactly the same where there's overlap).

**Comment by angela-tran** [comment]
Thanks all - this was a question on the technical detail of using the same `msgid` or having separate `msgid`s with duplicate content. I will go with the same `msgid` since it sounds like we want to reuse content.

**Comment by machikoyasuda** [comment]
Figma doesn't have the GitHub/Free & Open Source software line anymore. Are we keeping it regardless? 
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/80fc9fc6-c77d-49d5-abeb-6310c3c55813">

@srhhnry @angela-tran
