### ISSUE TITLE
Rework copy on developer-facing Figma screens to use sample copy instead of configurable strings

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#1567]
See [notes from July 24th](https://docs.google.com/document/d/1vActZALSbRwO0HxDvm-YQK37p22SPbL4XuMdcRx-BI8/edit?usp=sharing)

- [ ] Sync using the ~~Sample Copy Master Sheet~~ [Cal-ITP Benefits Application Copy (Configurable Strings)](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=0)
- [ ] Review all screens for issues

**Comment by srhhnry** [comment]
See [notes from July 24th](https://docs.google.com/document/d/1vActZALSbRwO0HxDvm-YQK37p22SPbL4XuMdcRx-BI8/edit?usp=sharing)

- [ ] Sync the Sample Copy Master Sheet 
- [ ] Review all screens for issues

**Comment by srhhnry** [comment]
Hey! I won't be able to get to this, but have looped in @segacy1.

**Comment by indexing** [comment]
Since we are moving away from Google Sheets Sync, I am closing this issue.
