### ISSUE TITLE
Add Spanish copy

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1572]
We want to do this in one giant PR to get it all in at once and reduce the number of merge conflicts on the PO files we have to deal with.

Ideally we wait for [#1571](https://github.com/cal-itp/benefits/issues/1571) to be complete.

**Comment by machikoyasuda** [comment]
@indexing Once https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=536435981 is updated with the latest approved translations from iBabbleOn, devs can start this issue.

**Comment by indexing** [comment]
@machikoyasuda I added Spanish translations to all strings on the _All agencies_ tab in master spreadsheet linked above.
