### ISSUE TITLE
Fix line-height for headlines

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1573]
1.5 is now 1.3

> https://github.com/cal-itp/benefits/issues/1556#issue-1816156909

Double check that the line heights didn't change for other elements.

**Comment by machikoyasuda** [comment]
Summary of the line-height changes --

  | Mobile | Desktop
-- | -- | --
H1 | 1.3 | 1.3
H2 | 1.3 | 1.3
H3 | - | 1.3
H4 | - | 1.5
Body | 1.5 | 1.5

As of today (July 31, 2023), the Typography page on the Style Guide is misleading. 
<img width="1275" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/db659d84-4465-4fef-919a-3040161dc8cf">

Make sure to go with the values in the Figma sidebar, not the written text in the guide itself b/c some of the values are wrong.

**Comment by machikoyasuda** [comment]
Sidenote: The way I got these values - make sure you're in Dev-mode on Figma. Look at the line-height percentage (like 130%) and convert that to a decimal. Do not use the pixel value, or convert that pixel value into a rem. Line-height is best as a unitless percent or decimal: 
<img width="795" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/1746812f-848a-4305-bd9f-80cab03baba3">
https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

**Comment by machikoyasuda** [comment]
Got it! I will assign myself to reflect that I'm assigned to figure out the exact ticket requirements. Thank you.
