### ISSUE TITLE
Fix "Get started with Login.gov" button on Tablet widths

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1574]
It should not go into 2 lines if we can avoid it cleanly.

https://github.com/cal-itp/benefits/issues/1556#issuecomment-1646036491

**Comment by machikoyasuda** [comment]
Go with these designs from Figma for the 2-line button:

<img width="389" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/4dbc11f8-9a21-4e88-a8d3-3c4813c94d6a">
