### ISSUE TITLE
Fix left-align on Index, Agency Index

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1580]
Index, Agency index - left-align is off. No padding/margin-left necessary.

https://github.com/cal-itp/benefits/issues/1556#issuecomment-1654022218

**Comment by machikoyasuda** [comment]
For this ticket, also correct the left-align on Mobile. It's also off by a few pixels. (Basically the `px-4 py-3` should become `p-3 p-md-0`, to reflect that padding should be 16px on Mobile and 0 on Desktop).

**Comment by machikoyasuda** [comment]
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/0912e64a-9ccb-4e2a-9e37-6e1253b1ec11">
On desktop, also increase spacing between h1 and h2 to 48px

**Comment by thekaveman** [comment]
@machikoyasuda I bailed on this ticket, feel free to grab it since you've been all over these alignment and size details.
