### ISSUE TITLE
Replace English placeholder text with final text

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1581]
E.g. on `eligibility/index` we have:

> Cal-ITP doesn’t save any of your information. All MST transit benefits [action] by [rate of discount] for [affected service] on [transit options].

We need the full complete sentences without `[action]`, `[rate of discount]` etc. placeholders.

We need a version of each sentence for each transit agency:

* MST
* SacRT
* SBMTD

Sentences that _only use the agency short name_ do not need to be refactored -- the app will continue to use the agency short name replacement.

**Comment by indexing** [comment]
@thekaveman @machikoyasuda 

Using our master copy spreadsheet, I identified the following variables present in our copy.
1. Please confirm no variables are missing.
2. Please confirm all variables are accurate.
3. Are there any variables with a different name that are actually the same? For example, what is the difference between [agency] and [agency name]? What is the difference between [long name] and [agency name]?
4. Please confirm the variables we will keep.

I will continue finding sample values so we can begin generating agency-specific copy.

# Copy variables

| variable name | sample value  | keep? |
|:--|:--|:--|
| [short name] | SBMTD | Y |
| [long name] | Santa Barbara Municipal Transit District | ??? |
| [agency] | ??? | ??? |
| [agency name] | Monterey-Salinas Transit | ??? |
| [agency help link] | https://mst.org/benefits | Y |
| [agency telephone] | 888-678-2871 | Y |
| [agency card] | ??? | N |
| [qualifier] | The number starts with a number sign(#) followed by five digits. | N |
| [ID number type]| ??? | N |
| [ID type]| ??? | N |
| [identity marker] | ??? | N |
| [transportation type] | rail | N |
| [card functionality] | tap this card when you get on and off the bus | N |
| [action] | ??? | N |
| [rate of discount] | 50% | N |
| [affected service] | ??? | N |
| [transit options] | ??? | N |
| [optional qualifier] | ??? | N |

**Comment by machikoyasuda** [comment]
@thekaveman @indexing 

Variables on Transit Agency model we always had and will continue to have:

```
{
  "slug": "mst",
  "short_name": "MST (sample)",
  "long_name": "Monterey-Salinas Transit (sample)",
  "agency_id": "mst",
  "merchant_id": "mst",
  "info_url": "https://mst.org/benefits",
  "phone": "888-678-2871"
}
```

`agency_name` should be either the `short_name` or `long_name`, depending on what that sentence needs.

**Comment by machikoyasuda** [comment]
@indexing 

The agency-specific copy should make sure it reflects these differences:
- MST / only buses / fixed route / don't need to tap off / 50% / reduction
- SacRT / only light rail NOT buses / don't need to tap off / 50% / reduction

Note the difference we already have in copy on Dev on the Agency Index pages:

https://dev-benefits.calitp.org/mst
<img width="683" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/30527eb6-a43f-41de-999a-99d31507ef0d">

https://dev-benefits.calitp.org/sacrt
<img width="606" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/91d14181-40d8-4425-a975-471617439f8f">

**Comment by thekaveman** [comment]
@indexing also need #1607

**Comment by indexing** [comment]
@machikoyasuda @thekaveman I submitted a CSV to the translation service this afternoon that will cover English custom strings for:

- Our sample agency
- MST
- SacRT
- SBMTD

@o-ram and I iterated through the SBMTD-specific copy this week—including comfirming certain language with Hilary. I believe the English is complete for all agencies.

The current state of all application copy is here: https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing

- I removed the configurable strings tab. The base copy now = our sample agency (CST). 

Additionally, I deleted or deprecated all working spreadsheets we've used for copy on both the Compiler drive and the Cal-ITP drive. Thus, the above spreadsheet is now our definitive source of truth for Benefits app copy.

I anticipate we will have translated copy by early next week.

**Comment by indexing** [comment]
@vykster We have a new invoice with iBabbleon to translate the agency-specific strings in the Benefits app. Please complete payment when you have a moment:  www.ibabbleon.com . We're planning to complete our initial round of copy updates during the current sprint.

**Comment by vykster** [comment]
paid.
