### ISSUE TITLE
Design QA on dev-benefits.calitp.org

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1582]
Confirm design on dev-benefits.calitp.org matches Figma designs.

**Comment by thekaveman** [comment]
@thekaveman to schedule a quick check-in with @srhhnry

**Comment by srhhnry** [comment]
Created[ a new issue](https://github.com/cal-itp/benefits/issues/1609) per yesterday's [slack convo](https://compilerla.slack.com/archives/C02GQ7AJXQE/p1690909867570869) for this.

**Comment by srhhnry** [comment]
QA complete with [checklist here](https://docs.google.com/document/d/1PlcoyMNSkwT2VJpPfmuS-cun4snYV5Bvse5zrYKWG08/edit?usp=sharing)

Let me know if anything needs additional explanation!

**Comment by machikoyasuda** [comment]
Thanks @srhhnry 

Gonna start making tickets for these day and will ping you for more details on some of them!
