### ISSUE TITLE
Update docs site with Veteran use case

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1587]
Add a new page under the _Use Cases_ section: https://docs.calitp.org/benefits/use-cases/

**Comment by angela-tran** [comment]
@indexing The draft you wrote in ClickUp looks good to me, and I see there are no more comments to resolve. What are the next steps on this? Maybe one next step is to get the contents of your draft into GitHub as a pull request.

**Comment by angela-tran** [comment]
Maybe we should also discuss if we want to incorporate anything from pull request #1731

**Comment by indexing** [comment]
@angela-tran I am ready to move the draft in ClickUp to the docs site. I'd like to pair up with a dev to complete the workflow since this won't be a minor update to existing copy. I also have updated Mermaid code for the flow diagram.

**Comment by angela-tran** [comment]
@indexing Sure, I'd be happy to pair with you to go through the workflow. Let me know if you'd like to do that today or next week
