### ISSUE TITLE
Create app configuration for SBMTD+Senior

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1588]
- [x] Define `EligibilityType` for senior flow, placeholder payment group
- [x] Define `EligiblityVerifier`, `AuthProvider` using MST/SacRT as examples
- [x] Define `TransitAgency`
  - [x] Pull phone, website from links in the below [comment](https://github.com/cal-itp/benefits/issues/1588#issuecomment-1662552009)
  - [x] Get normalized logo from design
  - [x] `Santa Barbara MTD` for Long Name

**Comment by machikoyasuda** [comment]
- Cal-ITP Benefits Transit Provider Onboarding: SBMTD x Seniors doc from Feb/March 2023
    https://docs.google.com/document/d/1gslfEV_TjWdRmMNdOe90pDUWbm8xyDZC/edit

- SBMTD full color logo PNG, from the onboarding doc
    https://drive.google.com/file/d/1YG7SU7YObpOEWqYSBcOHPO1I79byPhjd/view
