### ISSUE TITLE
Scope SBMTD Agency Card deployment

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1589]
## Acceptance Criteria

- [ ] Stories published for SBMTD with the agency card discount / Eligibility Server integration

## Resources

- [MST eligibility server deployment notes](https://docs.google.com/document/d/12uzuKyvyabHAOaeQc6k2jQIG5pQprdEyBpfST_dY2ME/edit)

**Comment by machikoyasuda** [comment]
- Add SBMTD-specific English copy. English copy is ready. https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=0
- Spanish translations are ready. https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit#gid=0

**Comment by thekaveman** [comment]
This work is now scoped across:

* #1664 
* cal-itp/eligibility-server#295

**Comment by thekaveman** [comment]
FYI @indexing
