### ISSUE TITLE
Fix letter-spacing for certain type elements

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1600]
- Mobile H1 is now 3%
- Desktop H2 is now 3%
- Mobile H2 is now 3% (Modal titles)
- Mobile H3 is now 3% , modal subtitles

**Comment by machikoyasuda** [comment]
- Mobile H3 is now 3% 

![Image](https://github.com/cal-itp/benefits/assets/3673236/1d2ecbc1-7bbd-43b7-ba18-d7df95a70bb1)

**Comment by machikoyasuda** [comment]
- Mobile H2 is now 3% (Modal titles)

**Comment by machikoyasuda** [comment]
Actually a bit more complex:
<img width="1393" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/770c1662-2ad9-4a72-adc6-94f8682da5cd">

**Comment by angela-tran** [comment]
@machikoyasuda Based on what you have in that spreadsheet, it seems like the table in https://github.com/cal-itp/benefits/issues/1573#issuecomment-1659432516 is not accurate?

**Comment by machikoyasuda** [comment]
Updated this monster sheet and added some notes/observations as comments:
https://docs.google.com/spreadsheets/d/1xmmjX94ApSn4sosvbcVztL1xBOU7JDpia-T0Lix5rSk/edit#gid=309456615

<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/edddc778-5840-4ecf-8deb-3cc298d231f3">
- The sheet is easier to understand when each line is the same font size (rather than each line is the same H1/H2 etc name), and the types with the same font-size are grouped together.
- There is no coherent "all line-height/letter-spacing decreases as font-size increases" or any whole pattern like that. There are, however, consistencies across font-sizes and some consistent one-off exceptions (if that makes sense..).

### Line-height
- H1 (Desktop/Mobile), H2 (Desktop/Mobile), H3 (Desktop) all have line-height of 130%. They are the only types with line-height of 130%.
- H4 is a very one-off outlier. It is only used once in the app, on Desktop, on the Agency Selector modal for the transit agency name. That box is small and has to fit long names. The line-height is 120% (the smallest on the whole app). No other type uses 120% line-height.
- The rest of the app is 150%.
- Line-height must be a unitless measurement, either % or decimal.

### Letter-spacing

### Headlines
- H1 (D) - 5%.
- H2/H1(M) - 24px type (H2 Desktop and H1 Mobile) are the only type with 3%.
- H4, again, one-off outlier, has a letter-spacing is 2% (the 2nd smallest on the whole app).

### Button
- Button is also 2%. (Think of it as clickable items like buttons and the H4 - which is used in a card button - has having tighter letter-spacing).
- On Desktop, Previous Page button and Sign Out of Login.gov are 5%.
- On Mobile, Previous Page button is 5%, while _another outlier_, Sign Out of Login.gov is 2% (because the shape turns into a bordered button and it needs to be tighter). 

### Body
- Body is 5%. 

### Navigation
- Español is mysteriously without any letter-spacing. The only button in the app with 0 letter-spacing.
- Footer Link is 5%.

## Courtesy Card Forms
- Label is 5%, while the form helper is 0. The only text on the app with 0 letter-spacing.

**Comment by srhhnry** [comment]
Other than aligning the app with what we have in Figma right now I urge that any additional letter-spacing work not be tied to the Veterans milestone, but be scoped as a stand-alone project (cc @indexing). I can see this as research project for later this year or as part of the design work that will happen next year as we start to consider scaling the site for complexity.  

An additional note for release: 

1) Agency Selector isn't finalized. At best I was hoping to finalize by Friday but I haven't had a chance to fix some basic elements (icon component), so just a heads up on that H4 (which shouldn't change from the Finalized design, but heads up nonetheless). 

On the analysis: 

2) We've never done a typography overhaul or initiative to implement a cohesive type system. Again, this is usually in the domain of a visual designer, or it should be considered a standalone project for an interaction designer (requires research/context/planning). I did bring our type weight and size more closely into a system that adheres to a high contrast scale (for readability/accessibility). However, for letter spacing and line height I've only implemented changes over the last year on an ad-hoc basis mostly where they are useful. For example, if a piece of type only exists in one, short line (e.g. sign out of login, español button) then it doesn't really make a difference in the design or to the user and I likely have not changed anything from the work done by the previous designer (which I believe is 5% letter spacing and 150% line height). Essentially, there's not a lot of pay-off for refining letter spacing, and line spacing should be in a readable range, but beyond that is generally constrained by spacing/aesthetics (or a type system). 

3) There's a lot of (_very good!_) work here that can serve as the basis for defining a full typography system, but my instinct is that it's not a high priority for Benefits right now. At the very least, there are two fundamental question we need to answer first: A) Why Roboto and not either Poppins (to be in line with Cal-ITP branding) or Public Sans (to be in line with gov)? and B) Should we create our own type system or align with Material Design or USWDS (they function differently, but alignment would be much simpler).

**Comment by machikoyasuda** [comment]
@srhhnry Got it! This next PR I started on #1613 is all about this: "aligning the app with what we have in Figma right now". So there's nothing else new happening. We're just trying to get the app aligned with what is on Figma right now. Because it's not correct on Dev or Test or Production right now.

**Comment by srhhnry** [comment]
Spreadsheet confirmed! All notes are in.
