### ISSUE TITLE
Make all modal triggers anchor elements

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1605]
We want each of the modal triggers to be a represented as an anchor element `<a>`.

There are two instances of a modal trigger as a `<button>`:

* the Index "Choose your Provider" modal button
* the Eligibility Index "Login.gov" mode

## Acceptance Criteria

- [ ] All modal triggers use the `core/includes/modal-trigger-link.html` or implement a custom `<a>` element
- [ ] The `core/includes/modal-trigger.html` is removed
- [ ] `core/includes/modal-trigger-link.html` is renamed to `core/includes/modal-trigger.html`

**Comment by machikoyasuda** [comment]
When completing this PR, please watch out for extra whitespace being created between the modal icon and the period.

I believe there's a regression on dev right now, where there is an extra space between the Login.gov modal icon and the period (top window in screenshot). It should look like the bottom window in the screenshot. I believe this extra space can be rendered when there's extra white space or line breaks in the template code.
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/2cbd200f-b930-43a3-a56a-f0a353e32973">

**Comment by thekaveman** [comment]
@machikoyasuda I did notice this reformatting in my ID PR😞 https://github.com/cal-itp/benefits/pull/1612/files#diff-cb91e6639dcdc4ed11d637fe0faf0c45cd62e18bf75e28ee8a875318a4f56e4eR15

This change was from djLint, maybe we need to wrap some of these sections with a comment to turn it off? I don't think this is the specific example in your screenshot though.

**Comment by machikoyasuda** [comment]
@thekaveman Ooo yea it's this line 15 on the radio input selection label for senior. https://github.com/cal-itp/benefits/pull/1612/files#diff-cb91e6639dcdc4ed11d637fe0faf0c45cd62e18bf75e28ee8a875318a4f56e4eR15 

Since all modal triggers are at the end of the sentence, this PR could add the period to the trigger includes. That way we only have to override the djLint rule in one place.

**Comment by machikoyasuda** [comment]
Would be good to test if this issue still arises after this refactor: https://github.com/cal-itp/benefits/issues/1526
