### ISSUE TITLE
Bug: Help Page - MST/CC answer is different

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1628]
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/6de8ded2-1141-4878-a077-891ce7177786">

font size should be changed to match the rest of the page too

**Comment by indexing** [comment]
@machikoyasuda I pondered noting that help views have content specific to each agency. Since SBMTD has a unique name for their proprietary card, their help page will be have agency-specific content as well.
