### ISSUE TITLE
Bug: Home Page/Agency Home Page - Title/button vertical spacing

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1637]
Currently, on Desktop's Home Page/Agency Index page, the whole container with the title, subtitle and button are vertically-centered, like this:

<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/ea8f2141-613b-4791-b238-186ca38281f4">

However, the text needs to start a bit lower.

**Comment by machikoyasuda** [comment]
So question for @srhhnry: Should the margin-top be set by percentage (like 60% page height, for example) or a set pixel? Or we could do a mix like "Center the whole container vertically, and then add a cusion of an extra 16px, 32px, 48px (or preferably a margin that is divisible by 4 or 8).

Here's how it looks with "vertically centered plus 64px total padding and margin top":

<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/aade57bd-70a8-4c03-8ae3-d08aee08fe35">
<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/7203f9ba-b81b-4d12-ac52-a0feff6579f1">

**Comment by machikoyasuda** [comment]
Gonna go with 72px + centered, to match Figma as close as possible. The other visual factor is how close the 2nd line of the header gets to the contactless symbol.

**Comment by srhhnry** [comment]
"vertically centered plus 64px total padding and margin top" looks great--the extra padding reduces the block-y feel of the previous iteration (more rectangular, less square). The headline also reads more nicely. We still have that line length issue (e.g. on Figma the second line is the longest; this is to create phrases).....buuuuuuut I think this more rectangular spacing is a fine solution and I'm good with this approach.

**Comment by srhhnry** [comment]
Just saw your new comment on 72px. Sounds fine.

**Comment by machikoyasuda** [comment]
@srhhnry Re: line-length issue for any page - We can't really change that. Plus it wouldn't really work with Spanish translation. If I added a forced, hard-coded line-break, it would then create 4-line headlines at narrower widths. Plus it's.. not even possible to render what's on Figma to the browser at most widths. This is what happens when I: 

1. Widen the container to allow the line to get longer, 
2. Manually hard-code a line break after `when`

<img width="859" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/b7b000ce-b4cd-4247-8285-6525ad0c2e2b">

3. I can manually add another line break after `on`, which achieves the Figma line breaks at this exact browser width. 
<img width="1387" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/0174b035-eea7-4672-9a8f-0086cfdcb3d1">
But at narrower widths, it'll break into 4 lines:
<img width="1039" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/598ab8ee-f797-4082-8f74-57d5a4c4eee5">





If this was calitp.org with only 1 language, I'd be more willing to add and test hard-coded line-break hacks, but with this site, we can't really do it.

**Comment by srhhnry** [comment]
Yup, that totally makes sense and I think the more rectangular space for text is a nice solution.
