### ISSUE TITLE
Bug: Enrollment Success - Desktop: Image spacing is off

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1638]
Image should be 16px away from the text.

<img width="652" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/6ff5918a-9733-47a8-93dd-e80eab29afda">

**Comment by machikoyasuda** [comment]
@srhhnry How is this:

<img width="1512" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/24490d47-227a-4ded-bc25-78a4828d0148">

Should the image width be dynamic (widens to take up 4-column widths at all times), or static (set to 345px and never changes)?

**Comment by srhhnry** [comment]
First screenshot looks like the body + image pairing is off-center to me--like it's pulling to the left side of the screen. Maybe centering to the headline? 

As for the second question....I think static, as the image is round and at a certain width it will look too tall for the page.

**Comment by machikoyasuda** [comment]
This ticket comes from @srhhnry's design qa results https://docs.google.com/document/d/1PlcoyMNSkwT2VJpPfmuS-cun4snYV5Bvse5zrYKWG08/edit
