### ISSUE TITLE
Add docs page describing the Copy Style Guide

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1653]
E.g. to capture best practices and decisions around:

* When to title case vs. when to sentence case
* Punctuation and links
* Alt text guidance
* Etc...

## Acceptance Criteria

- [x] The page should live in the same file structure as the new Copy Process docs from #1447

**Comment by machikoyasuda** [comment]
Some suggested topics:

- English: Which buttons get title-case vs. sentence-case and why
- Spanish: All buttons sentence-case
- Proper nouns: `Littlepay` not `LittlePay`
- Spanish style guide: List of important proper nouns `Cal-ITP Benefits`, `Cal-ITP`, `Caltrans`, Login.gov, NIST, MST Courtesy Card
- Word choice: Benefit (as the noun, vs. discount). Reduce as a verb (over discount). Contactless card. `Older Adult`. Transit provider vs. transit agency.
- Pluralization: Older Adult benefit overview vs. Veterans benefit overview
- Verbs the app does: `connect`, `enroll`, `verify [your identity]`

**Comment by machikoyasuda** [comment]
Existing Cal-ITP-wide docs, not necessarily Benefits app-specific: https://drive.google.com/drive/folders/1v-d5yjTdEN5M4TVzS6EwHPGyHO5Fp7SV

Prior discussions #987

**Comment by machikoyasuda** [comment]
More info here https://docs.google.com/document/d/1Vb4JFb4UwRqqjeQXrkwqQDOvR-vJJceMi4S1_JbnehM/edit#heading=h.44ycts7cio3u

**Comment by machikoyasuda** [comment]
Spanish: Formal/usted tense for all copy

**Comment by machikoyasuda** [comment]
Document styles around numbers and numerals (fifty percent, 50%, 3-digit, three-digit) etc.

**Comment by machikoyasuda** [comment]
Use | English | Spanish | Do not use | Usage
 :---         |    :---     |         :---  |         :--- |         :--- |
agency card | agency card | tarjeta de agencia | Agency Card (don't capitalize both words) |  
benefit option | benefit option | opción de beneficio |   |  
Cal-ITP | California Integrated Travel Project | California Integrated Travel Project (Proyecto Integrado de Viaje de California, o Cal-ITP por sus siglas en inglés) |   |  
Cal-ITP Benefits | Cal-ITP Benefits | Cal-ITP Benefits | Do not translate Cal-ITP Benefits |  
California Department of Transportation | California Department of Transportation | Departamento de Transporte de California |   |  
California Department of Technology | California Department of Technology | Departamento de Tecnología de California |   |  
connects | connects | conecta |   |  
contactless card | contactless card | tarjeta sin contacto | payment card, cashless, tap-to-pay, touchless |  
enroll | enroll | inscribirse | apply |  
enrollment process | enrollment process | proceso de inscripción |   |  
GitHub | GitHub | GitHub | Github |  
Littlepay | Littlepay | Littlepay | LittlePay |  
Older Adult | Older Adult | adultos mayores | Senior |  
public transportation | public transportation | transporte público |   |  
reduced fare | reduced fare | tarifa reducida | discounted |  
Social Security number | Social Security number | número de Seguro Social | social security number |  
state-issued ID card | state-issued ID card | tarjeta de identificación emitida por el estado | Driver's license |  
tap to ride | tap to ride | toque para viajar |   |  
transit agency | transit agency | agencia de tránsito | bus agency, light rail agency, transit authority | Refer to Language Matters: Cal-ITP Terminology
transit benefit | transit benefit | beneficio de tránsito | discount, fare discounts, reduced-fare | "Older adult transit benefit", "Veteran transit benefit"
transit provider | transit provider | proveedor de transporte |   |  
US Veteran | US Veteran | Veterano de EE. UU. | U.S. Veteran, US veteran | This currently goes against Cal-ITP Editorial Style Guide
verify | verify | verifique |   |

**Comment by machikoyasuda** [comment]
| Rule | Examples |  
:--- | :--- | :--- | :---
Capitalization | Always sentence-case body text, headlines, questions on Help page. Do not use punctuation. | Unable to confirm eligibility \| Cal-ITP Benefits |  
  | In English, names of pages are capitalized. | Return Home | Previous Page
  | In Spanish, names of pages are not capitalized. | Volver al inicio | Página anterior
  | Refer to Cal-ITP Editorial Style Guide |   |  
Images, illustrations | Always write an alt tag, unless Design determines the visual is purely decorative and has no substantive meaning. |   |  
Links | Never link to "here". Use a descriptive title for the page. |   |  
Tense | For Spanish, use usted/formal case for all copy. |   |  
Numbers | Refer to [Cal-ITP Editorial Style Guide](https://docs.google.com/document/d/1yG2jc_aMPSGc2wqvazKGgFIeV-aDDDsJIuONhUg0MOI/edit) |   |  
Spacing | Refer to [Cal-ITP Editorial Style Guide](https://docs.google.com/document/d/1yG2jc_aMPSGc2wqvazKGgFIeV-aDDDsJIuONhUg0MOI/edit) |   |  
Punctuation | Refer to [Cal-ITP Editorial Style Guide](https://docs.google.com/document/d/1yG2jc_aMPSGc2wqvazKGgFIeV-aDDDsJIuONhUg0MOI/edit) |   |
