### ISSUE TITLE
Incorporate coverage diff reporting

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1668]
We use the [`coverage`](https://coverage.readthedocs.io/) package (indirectly via [`pytest-cov`](https://pytest-cov.readthedocs.io/en/latest/readme.html)) to calculate Python unit test coverage of the codebase.

The [test runner generates a _coverage report_](https://github.com/cal-itp/benefits/blob/dev/tests/pytest/run.sh#L8), the latest always available on our docs site at: https://docs.calitp.org/benefits/tests/coverage

However, within a given PR or set of changes we don't get much insight of the impact on test coverage -- without manually reviewing coverage reports and eyeballing differences.

The [Python Coverage Comment](https://github.com/marketplace/actions/python-coverage-comment) GitHub Action can be used in a workflow to provide _coverage diffs_ for our pytests. The action uses existing coverage metadata generated by the test runner to create a PR comment with information about the change. The comment is updated as the PR changes and new test runs are produced.

_Example: comment on a first-time setup PR_
![image](https://github.com/cal-itp/benefits/assets/1783439/165c369d-d99c-4ddf-a093-3718496e149d)

## Acceptance Criteria

- [ ] Use `coverage` directly rather than via `pytest-cov`
- [ ] Use `pyproject.toml` to configure `coverage`
  - [ ] See note about [running with `relative_files = true`](https://github.com/marketplace/actions/python-coverage-comment#why-do-we-need-relative_files--true-)
- [ ] Update `pytest` actions workflow to use `Python Coverage Comment` to provide coverage diff reporting, [example](https://github.com/marketplace/actions/python-coverage-comment#basic-usage-without-external-contributors)

## Additional context

[Example of this setup](https://github.com/compilerla/compiler-admin/pull/9)

**Comment by machikoyasuda** [comment]
This was completed with https://github.com/cal-itp/benefits/pull/1745 right?
