### ISSUE TITLE
Add automated Lighthouse accessibility testing for PRs

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#167]
- Add GitHub action that runs LH on the app built for the PR
- Require Accessibility, Best Practices to pass
- Do the Performance test but don't require it

GitHub Action:
- Run on PRs that touch any `benefits/**` files
- Build Docker image
- Start app w/ Docker at specific port
- Run lighthouse at that specific port

**Comment by thekaveman** [comment]
If this makes sense to you @machikoyasuda, (maybe?) this could be added as a step in the [`tests-ui` workflow](https://github.com/cal-itp/benefits/blob/dev/.github/workflows/tests-ui.yml)?

**Comment by machikoyasuda** [comment]
@thekaveman Ooooh..yes!
