### ISSUE TITLE
[DESIGN] Low-income rider enrollment pathway

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1677]
## User story
_As a public transit rider living in California, I want to verify my low-income status with my transit agency, so I receive a reduced fare when I use my contactless credit or debit card to pay for rides on public transit._

## Assumptions

- We are using participation in CalFresh to qualify participants for reduced transit fares in the program as low income Californians. Participation in CalFresh qualifies transit riders to a reduced fare.
- We will communicate the expiration in the confirmation copy in the app, but we will not notify the enrollee that their benefit will expire soon in the initial implementation.
- When the rider reaches end of their 365-day enrollment period, they will need to repeat the same workflow they used to enroll initially: 1)ID verification (Login.gov), 2) eligibility check (Idg<->CalFresh Confirm API), funding source enrollment (Littlepay).
- We will utilize the Older Adult enrollment pathway as a foundation to implement this eligibility check.
- We will utilize [Login.gov](https://github.com/cal-itp/benefits/issues/Login.gov) to share transit rider identity information with CalFresh Confirm.
- [Login.gov](https://github.com/cal-itp/benefits/issues/Login.gov) contains all data points required by CalFresh to verify eligibility.
- We will continue to ask the transit rider to choose one benefit that best matches who they are. We will defer the implementation of checkboxes that allow a transit rider to choose multiple options.

## Specifications

- The Benefits app will verify an individual's low income eligibility based on whether they have received CalFresh benefits in one of the preceding three months from the date the system checks eligibility.
	- The month in which the person is checking eligibility is the current month.
	- The two months preceding the current month constitute "the preceding three months."
- If eligible, the CalFresh cardholder will receive a reduced fare on transit when paying by contactless bank card for 365 days from the date of successful enrollment.
- After 365 days from the date of successful enrollment, the low-income transit benefit expires and the rider will no longer receive a reduce fare. They will, however, be able to continue to pay for transit using their contactless card, but will be charged full fare until they re-enroll via the Benefits app.
- After a rider successfully enrolls their card for a low-income benefit, they will be able to re-enroll for the same benefit beginning 14 days preceding the date when their benefit ends. The app will not allow re-enrollment in the first 351 days following enrollment. 
- The low income enrollment pathway can be enabled on a transit agency-by-transit agency basis. By default, this pathway is not enabled.

## Design issue list
- [x] #1678
- [x] #1679
- [x] #1680
- [x] #1681
- [x] #1682
- [x] #1684
- [x] #1865 

## Acceptance criteria
- [x] All views to build this feature are presented in Figma at the Desktop breakpoint.
- [x] All views to build this feature are presented in Figma at the Mobile breakpoint. 
- [x] English copy has been approved using the [Copy delivery process](https://docs.calitp.org/benefits/product-and-design/copy-delivery/).
- [x] The design of all component used in the above views are complete: all component states are present.
- [x] All views have been reviewed using the accessibility checklist.
- [x] Element spacing and type styling use app standards.

## Definition of "Done"

- [x] All acceptance criteria above are met.
- [x] Product and development teams have done an initial review of the design in a Design Review meeting and have had the opportunity to ask clarifying questions prior to handoff.

## Links to user research, designs and resources
#1469

**Comment by indexing** [comment]
While contracting isn't complete, updates from CDT over the last couple weeks indicate we are very close to resolution. Thus, we will begin at-risk work in the design phase in order to keep us on track to deliver this pathway in Q1 2024. 

@srhhnry I've changed the status of this issue to _In Progress_ and assigned it to you.

**Comment by srhhnry** [comment]
[Accessibility guide here](https://docs.google.com/document/d/1KR-xnKGWNTjGvgc1MmSgj0hh4AT8dHmYljTtmUkwRO0/edit?usp=sharing)

**Comment by indexing** [comment]
Product, design, and dev had a design review of this new enrollment pathway yesterday afternoon. We came away from a few actions items to resolve before hand-off that are captured in this doc: https://docs.google.com/document/d/1EZX2EJ2et6tcirAwQ9_WAQt04jMsZZ4to8Dz7zzS6tc/edit?usp=sharing

Once those are resolved, we will be ready for handoff and this issue can be closed.

**Comment by indexing** [comment]
We had a meeting today to rough out the issues for this pathway, so we can consider hand-off complete.

Follow implementation here: #1878 

cc// @thekaveman
