### ISSUE TITLE
Add benefit option to `Eligibility view` for low-income riders to select.

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1678]
- [x] Review naming and copy that describe option. 
- [x] Review logic behind the order of Benefit options.

**Comment by srhhnry** [comment]
New screens here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281-19859&mode=design

**Comment by srhhnry** [comment]
Current logic for order of pathways is by number of potential people served, which is:
- Older adults (~over 5.4 million)
- CalFresh (~almost 5 million)
- Veterans (~over 1.8 million)
- Agency cardholder (probably not in the millions)

I think it makes sense to have older adults at the top, to reduce the amount of text that group has to read through (citing MST staff opinion here that the app was already a bit overwhelming for their customers), and I also think it makes sense to have agency cards at the bottom as we work to deprecate those in their respective systems. I don't think the user cares what order we're releasing these pathways in (i.e. Older Adult, Agency card, Veteran, CalFresh), and I can't think of an ordering schema that would have veterans listed as second. 

I do think it makes sense to revisit the order of pathways when we have a good sense of our average ratio of users (veterans vs calfresh vs older adult) but keep the current order till then.

**Comment by srhhnry** [comment]
Screens here 
<img width="652" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/f9173aae-1af5-4f77-b207-24e28efb3b5b">

**Comment by srhhnry** [comment]
Final screens: 

![Image](https://github.com/cal-itp/benefits/assets/5394204/00352bd6-2803-4e60-8dd1-d7b551ac2ba4)

Boards[ here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=13761%3A6517&mode=design&t=tEbC2Hkg7fdL2JgX-1) (temporary board, see full app after March 2024)
