### ISSUE TITLE
Add `Informational modal` to explain what it means to be a CalFresh recipient.

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1679]
- [x] Review naming and copy that describe option. 
- [x] Add a question: Can I use my Calfresh card to pay for transit rides?

**Comment by srhhnry** [comment]
![Image](https://github.com/cal-itp/benefits/assets/5394204/d675a61f-63bd-4c4c-a353-458dea017238)

Final modal screens can be [found here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281%3A19859&mode=design&t=o0m2YUqHOkmyueWF-1)
