### ISSUE TITLE
Add `CF_Eligibility_Start view` for Calfresh.

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1681]
It’s the same as older adult except for the title. Do we need any additional customizations?

**Comment by srhhnry** [comment]
No additional customizations needed for a copy-only update.

**Comment by srhhnry** [comment]
<img width="581" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/d7fcb738-21b4-4e9e-9037-a099830c92f5">

**Comment by srhhnry** [comment]
Final screens

<img width="582" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/f1d1b0da-d114-4bb9-b014-698740563f9a">

Figma board can be [found here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281%3A19859&mode=design&t=o0m2YUqHOkmyueWF-1)
