### ISSUE TITLE
Add `Desktop_IdG_Enrollment view` to confirm the rider is eligible for a low-income transit benefit

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1682]
- [x] Develop copy and an alert component to inform rider not to enter their CalFresh card number.
- [x] #1683

**Comment by srhhnry** [comment]
The new alert banner (known as "alert") can be found [here in the Benefits component library](https://www.figma.com/file/IuVNsLccmvumsUzW7IC5BF/Cal-ITP-Benefits-Component-Library?type=design&node-id=0%3A1&mode=design&t=5FoDbtLsp1UMDRBE-1). 

It looks like this: 
<img width="686" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/e3d63227-b577-47b4-8264-695082cf761c">
