### ISSUE TITLE
Design an alert component

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1683]
While we plan to use this new component in the low-income path first, consider how we might use if more generally.

**Comment by srhhnry** [comment]
Alert component (and variants) can be found in the [Benefits component library](https://www.figma.com/file/IuVNsLccmvumsUzW7IC5BF/Cal-ITP-Benefits-Component-Library?type=design&node-id=0%3A1&mode=design&t=fGcEOeqnyi5ErDca-1), and looks like this: 
<img width="572" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/385bb85b-593b-4d90-9651-28061505fc07">

**Comment by srhhnry** [comment]
@thekaveman Not sure if you need this ticket as part of the acceptance criteria for low-income, but here it is regardless!
