### ISSUE TITLE
Add `Success view` to confirm the low-income rider’s contactless card was matched to the benefit.

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1684]
- [x] Copy must inform the rider that the benefit expires 365 days from today.

**Comment by srhhnry** [comment]
Screens here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281-19859&mode=design

**Comment by srhhnry** [comment]
<img width="792" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/10648ede-212e-4d37-8212-9c788e105e84">

**Comment by srhhnry** [comment]
Final screens [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=5281%3A19859&mode=design&t=o0m2YUqHOkmyueWF-1):

<img width="649" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/83e3341f-7079-4767-b151-18f7208ca69c">
