### ISSUE TITLE
Revise supporting copy for US Veteran option in `Eligibility view`.

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1692]
See parent ticket for full context: #1691 

## Copy updates for `Eligibility view`

- Veteran pathway option: supporting copy explaining the _US veteran_ option needs to provide guidance to riders that they will use Login.gov for ID verification.  (Same info we provide for the Older adult pathway option.)
- Approved copy is in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) source file on the EN-US sheet.

## Acceptance criteria

- [ ] Supporting copy below the Older Adult option that tells the rider they will use Login.gov to verify identity is the same supporting copy at the end of the US Veteran option.

**Comment by segacy1** [comment]
New screen in Figma [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=12065-9057&mode=design&t=aE8yYgThuNX651Pp-4)

**Comment by machikoyasuda** [comment]
@indexing is this ready for development? If so, you can unassign Segacy so I can assign myself.
