### ISSUE TITLE
Revise explainer copy on `Vet_Eligibility_Start` view to guide riders to gather necessary info for Login.gov  

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1693]
See parent ticket for full context: https://github.com/cal-itp/benefits/issues/1691

## Copy updates for `Vet_Eligibility_Start` view
- Display explainer copy used by all eligibility pathways that use Login.gov to verify rider identity.
- Update button label (Get Started with Login.gov)
- Approved copy is in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) source file on the EN-US sheet.

## Acceptance criteria

- [ ] `Vet_Eligibility_Start` view content matches `OA_Eligibility_Start` view

**Comment by segacy1** [comment]
New screen in Figma [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=12065-9175&mode=design&t=aE8yYgThuNX651Pp-4)
