### ISSUE TITLE
Device mockups featuring the Benefits app

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1715]
## Need

When promoting and presenting the Cal-ITP Benefits app, we frequently need to represent the web application as a product—a tangible context for how a person might encounter the app in real life. We need a library of images that show the Benefits app in a variety of contexts.

## Guidelines

- We can use actual screenshots of the application or exports from Figma mockups.
- Represent the application in light mode.
- Desktop devices are silver (most neutral, common chassis color)
- Mobile devices are black/dark (most neutral, common chassis color)
- Use our sample agency rather than a specific agency using the Benefits app, e.g. MST or SBMTD
- We need frontal, flat representations of each view as a baseline, but I'd love to see some examples three-quarter views, clay devices, and other interesting ways to present the app.

#### Landing view

- [x] `Home Indirect Entry` on a Windows desktop monitor
- [ ]  ~~`Home Indirect Entry` on an Apple desktop (iMac)~~
- [ ]  ~~`Home Indirect Entry` on a Windows laptop~~
- [x]  `Home Indirect Entry` on an Apple laptop
- [ ]  ~~`Home Indirect Entry` on an Android mobile device~~
- [x]  `Home Indirect Entry` on an Apple mobile device

#### Eligibility view

- [x] `Eligibility` showing all enrollment pathways* on a Windows desktop monitor
- [ ] ~~`Eligibility` showing all enrollment pathways on an Apple desktop (iMac)~~
- [ ] ~~`Eligibility` showing all enrollment pathways on a Windows laptop~~
- [x] `Eligibility` showing all enrollment pathways on an Apple laptop
- [x] `Eligibility` showing all enrollment pathways on an Android mobile device
- [ ] ~~`Eligibility` showing all enrollment pathways on an Apple mobile device~~

> "all enrollment patheways" = Older Adult, Veterans, and Agency card 

#### Success view

- [x] `Success` via Login.gov on a Windows desktop monitor
- [ ]  ~~`Success` via Login.gov on an Apple desktop (iMac)~~
- [ ]  ~~`Success` via Login.gov on a Windows laptop~~
- [x]  `Success` via Login.gov on an Apple laptop
- [x]  `Success` via Login.gov on an Android mobile device
- [ ]  ~~`Success` via Login.gov on an Apple mobile device~~

## Acceptance criteria

- [x] Each asset shows the application in a web browser (preferably generic, i.e. not Chrome, Safari, or Firefox)
- [x]  If the page title shows in the browser, the page title is accurate according to the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) source file.
- [x]  If the favicon shows in the browser, we use the Benefit app favicon.
- [x] Each device mockup can be easily updated in Figma as we evolve the app by adding new enrollments pathways, different illustrations, etc.

**Comment by segacy1** [comment]
Frontal, flat representations are on [here](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=12237-4661&mode=design) the Device Mockups page in the Benefits figma and in review for edits. This does not yet include additional layouts/views like clay mockups and 3D. 

cc @machikoyasuda

**Comment by indexing** [comment]
@segacy1  As discussed, let's use a dedicated file in the Cal-ITP Benefits Figma project for device mockups. I've created the file here: https://www.figma.com/file/HKwtXKOPnpD1QBSCDqtOVm/Cal-ITP-Benefits-Device-Mockups?type=design&node-id=162%3A1949&mode=design&t=TnbYdsAhl9cltRYw-1

- [ ] Remove the "Device Mockups" page in the "Benefits (Full Application) Figma file.

I've also documented my process for creating device mockups use actual app screenshots. This workflow is significantly more complex than exporting from design mockups, but we can get any view at any breakpoint using this approach.  I've created what we need for the Veterans launch, but we'll need to fill in the additional ones noted above. Give this process a shot for some of the missing mockups and let me know if I need to revise for clarity. Thanks!

No clay model mockups or other additional option necessary right now.

---

# Process to create specific views for device mockups featuring the Cal-ITP Benefits web application

1. Locate a device asset to present the application. 

   > See *Figma Community* in the *Resources* section below for a link to a device library. 

2. Add the device to the appropriate page in the [Cal-ITP Benefits Device Mockups](https://www.figma.com/file/HKwtXKOPnpD1QBSCDqtOVm/Cal-ITP-Benefits-Device-Mockups?type=design&node-id=102%3A247&mode=design&t=FE50Gfpnsoa2Xoth-1) Figma file, such as *Device Mockups – Eligibility View*.

3. Locate a browser for the device type you’ve chosen. 

   > See *Figma Community* in the *Resources* section below for links to community files that have mobile and desktop browsers. 

4. Add the browser to the appropriate page in the [Cal-ITP Benefits Device Mockups](https://www.figma.com/file/HKwtXKOPnpD1QBSCDqtOVm/Cal-ITP-Benefits-Device-Mockups?type=design&node-id=102%3A247&mode=design&t=FE50Gfpnsoa2Xoth-1) Figma file, such as *Browser – Eligibility View.*

5. Determine the size of the view that will display on the device. 

   > For desktop, an example is 1440 x 1024. For mobile, use the default width and height. For Android, this is 360 x 640.

6. In a Chromium browser, [configure the browser to capture screenshots](https://gist.github.com/algal/972c43b533cade4332faf4ec4458fd93) using  developer tools. Visit the production version of the Benefits application at <http://benefits.calitip.org> or visit our test or dev environments.

7. Set the dimensions of the view to match device display you that determine in step 3.

8. Select the code to target and screenshot the view.

   > See a video demo of steps 7 and 8 here: <https://share.zight.com/JrumyZEA>

9. Import the `screenshot` into the browser page in Figma and combine it with the browser asset. 

10. Export the `browser+screenshot asset` from Figma. 

11. Import the `browser+screenshot asset` into the device view. 

   > I found that not setting the browser to full screen is the best way to show a full view of the app on desktop devices.

12. Export the `browser+screenshot+device asset` from Figma as PNG or JPEG to create a device mockup asset. 

13. Save both the `browser+screenshot asset` and the `browser+screenshot+device asset`  in the [Cal-ITP Benefits: Product Mockups](https://drive.google.com/drive/folders/1pajI4VRezAkj75h4Zg3qHxVEqZLonyhx?usp=drive_link) folder on Cal-ITP’s Google Drive for use by others in promotional materials.

## Resources

### Web application screenshots

- [Taking website screenshots](https://gist.github.com/algal/972c43b533cade4332faf4ec4458fd93#taking-website-screenshots)

### Figma Community

- [Device Mockup Library](https://www.figma.com/community/file/786708730400780813/device-mockups-library-100-devices)

- [Web Browser Mockups](https://www.figma.com/community/file/1138888721425526181/web-browser-mockups)

- [Google Chrome for Android](https://www.figma.com/community/file/949209833398927432/google-chrome-for-android)

- [iPhone Browsers - Safari & Chrome (iOS 15)](https://www.figma.com/community/file/939653933338991115/iphone-browsers-safari-chrome-ios-15)

**Comment by indexing** [comment]
All device mockups for the Benefits application now live in a .zip file this Cal-ITP Google Drive directory: https://drive.google.com/drive/folders/1pajI4VRezAkj75h4Zg3qHxVEqZLonyhx?usp=drive_link

The current version of the ZIP file contains the images above that are checked. The items that are struckthrough are specific devices we can address in the future if the need arises.

I deleted the page within the main Benefits application file in Figma linked above and moved all product mockups to their own Figma file: https://www.figma.com/file/HKwtXKOPnpD1QBSCDqtOVm/Cal-ITP-Benefits-Device-Mockups?type=design&node-id=128%3A188&mode=design&t=Lir6GDvaQfKbRc9L-1
