### ISSUE TITLE
Configure SBMTD PaymentProcessor in dev, test

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1724]
We've confirmed API access for SBMTD to Littlepay's QA environment. 

Now we need to configure the `sbmtd-payment-processor-*` secrets in dev and test to continue testing the SBMTD senior flow.

## Acceptance Criteria

- [x] Users see the Older Adult option for SBMTD in `dev-benefits` and `test-benefits`
- [x] A user who successfully verifies against Login.gov sandbox can complete enrollment in Littlepay's QA environment

## Additional context

See https://github.com/cal-itp/benefits/issues/1699 for the full list of `sbmtd-payment-processor-*` secrets.

**Comment by thekaveman** [comment]
We worked out the differences in APIs with Littlepay.

We can use our [`littlepay`](https://github.com/cal-itp/littlepay) CLI tool to configure groups and products, even before fully switching to the Back Office API for enrollment.

**Comment by o-ram** [comment]
Cross-posting: see #1409 for all discount product codes!

**Comment by thekaveman** [comment]
This is done for `dev` and `test` only.

Follow #1722 for `prod`.
