### ISSUE TITLE
Minor typo in Help / Login.gov modal

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1747]
NIST spelled out should be `National Institute of Standards and Technology`: https://www.nist.gov/

We have `National Institute of Standards of Techonology`

(_`of ... of` instead of `of ... and`_)

## To Reproduce

1. Go to benefits.calitp.org
2. Click on the Help page link
3. Scroll down to the heading "Why is Cal-ITP Benefits using Login.gov?"
4. See typo in first sentence

## Additional context

Here in the English PO file: https://github.com/cal-itp/benefits/blob/dev/benefits/locale/en/LC_MESSAGES/django.po#L122

Referenced in the Spanish PO file: https://github.com/cal-itp/benefits/blob/dev/benefits/locale/es/LC_MESSAGES/django.po#L158
The Spanish translation is `Instituto Nacional de Estándares de Tecnología` which is closer to `National Institute of Technology Standards`, this also seems incorrect?

**Comment by machikoyasuda** [comment]
NIST is el Instituto Nacional de Estándares y Tecnología
Source: https://login.gov/es/who-uses-login/
https://github.com/18F/identity-site/blob/50e1724eaf00dba130375886b9d683a71c8d8b29/content/_landing/who_uses_login._es.md?plain=1#L24

**Comment by machikoyasuda** [comment]
Actually...Login.gov has a different translation from NIST.gov itself 😒 

https://www.nist.gov/calibrations/la-version-en-espanol

`El Instituto Nacional de Normas y Tecnología (NIST, por sus siglas en inglés)`

Normas not Estándares

--

We can submit a PR to correct Login.gov docs.

**Comment by angela-tran** [comment]
It looks like at some point, nist.gov used `Instituto Nacional de Estándares y Tecnología`

https://www.nist.gov/search?s=Instituto+Nacional+de+Est%C3%A1ndares+y+Tecnolog%C3%ADa&index=all-meta-engine
vs.
https://www.nist.gov/search?s=Instituto+Nacional+de+Normas+y+Tecnolog%C3%ADa&index=all-meta-engine

Wikipedia has it with "Estándares"
https://es.wikipedia.org/wiki/Instituto_Nacional_de_Est%C3%A1ndares_y_Tecnolog%C3%ADa

**Comment by angela-tran** [comment]
I think we should make a separate GitHub issue to track the Spanish translation problem
