### ISSUE TITLE
Retry button is missing

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1755]
There is supposed to be a "Try again" button on the "retry" page. The user sees this page if there was a verification failure or error upon submitting the payment processor form.

## To Reproduce

1. Go through the SBMTD senior flow
2. Verify your senior eligibility
3. Try enrolling in the discount by submitting the payment processor form
4. See a page that says you can try again but doesn't provide a button for you to go anywhere

## Expected behavior

The user can use a "Try again" button to go back to the enrollment/index

## Screenshots

![image](https://github.com/cal-itp/benefits/assets/25497886/e631bb6f-6265-4ff6-93c0-914a1f4c95e8)

## Desktop
- OS: seen on Mac and Windows
- Browser: seen on Chrome and Firefox

## Additional context

We saw this while testing SBMTD senior flow on the dev Benefits site.

**Comment by indexing** [comment]
@segacy1 While reviewing this issue, I discovered this note in Figma. Let's address this design issue as part of the fix for this issue.


![Image](https://github.com/cal-itp/benefits/assets/6279581/a05d3136-1510-4413-89f5-6857e848e102)

**Comment by indexing** [comment]
@angela-tran Now that SBMTD Older Adults is in prod, I'd like to close the associated milestone. I believe this bug applies to ALL enrollment pathways, so I've added it to the November sprint. Are you okay removing this bug from the SBMTD Older Adults milestone?

**Comment by angela-tran** [comment]
@indexing Yes, that sounds good to me. I'll remove it from the milestone

**Comment by thekaveman** [comment]
We're going to focus this issue on the bug fix.

@indexing will create additional issues to track the design improvements for buttons across the app.
