### ISSUE TITLE
Eligibility confirmation spec issue

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#178]
This spec: https://github.com/cal-itp/benefits/pull/170/files#diff-1637a357180023d868d2fca69d3d4e2a68f7b58c61aa71b016977ca95ee672fcR36 is currently set to `skip()` because it does not pass with the way the app is currently set up.

Previously, the Eligibility Server API had fake merchant auth token routes to accept calls from the `abc` transit agency in development mode, but these have since been removed - as of this PR https://github.com/cal-itp/eligibility-server/pull/31/files#diff-e5991fd559847cf92df779bd8b72643e9b64926355be788735b3c1cfcabca211L219

Now, developers cannot get the `eligibility/confirm` page to load with valid test credentials b/c the app looks for valid tokens before it loads the page. There are several ways we can address this:

1. ~Configure some sort of stubbing/mocking in the Cypress test to return fake auth tokens, so that Cypress can open the `eligibility/confirm` page without payment buttons. (This addresses the Cypress issue but not the local dev one).~
2. ~Change the way Django opens this page. https://github.com/cal-itp/benefits/blob/dev/benefits/enrollment/templates/enrollment/index.html#L26 Have Django instead load the page and then asynchronously load the payment button. (This addresses both Cypress and local dev issue.)~
3. Create a fake Merchant Auth token so the page can load (and where would that code live and how would we do it?) (What we had in the past: https://github.com/cal-itp/benefits/issues/179)

**Comment by thekaveman** [comment]
Closed by #229!
