### ISSUE TITLE
Wire up Benefits and SBMTD Eligibility Server

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1783]
When this ticket is complete, SBMTD Mobility Pass will be officially "live" in the Benefits app.

## Acceptance Criteria

- [x] `dev` can successfully send and receive Eligibility API requests and responses to the `dev` Eligibility Server
  - [x] Use sample data in the Eligibility Server
- [x] `test` can successfully send and receive Eligibility API requests and responses to the `test` Eligibility Server
  - [x] Use sample data in the Eligibility Server
- [x] `prod` can successfully send and receive Eligibility API requests and responses to the `prod` Eligibility Server
  - [x] Depends on https://github.com/cal-itp/eligibility-server/issues/297 being complete
  - [x] Confirm data load into Eligibility Server
  - [x] Configure payment group
    - [x] Create group in `prod`
    - [x] Link group to discount product(s) in `prod`
  - [x] Configure Benefits secrets
    - [x] `SBMTD_MOBILITY_PASS_GROUP_ID`
    - [x] `SBMTD_SERVER_PUBLIC_KEY`
    - [x] `MOBILITY_PASS_VERIFIER_API_URL`
    - [x] `MOBILITY_PASS_VERIFIER_API_AUTH_HEADER`
    - [x] `MOBILITY_PASS_VERIFIER_API_AUTH_KEY`
    - [x] `MOBILITY_PASS_VERIFIER_JWE_CEK_ENC`
    - [x] `MOBILITY_PASS_VERIFIER_JWE_ENCRYPTION_ALG`
    - [x] `MOBILITY_PASS_VERIFIER_JWS_SIGNING_ALG`
    - [x] `MOBILITY_PASS_VERIFIER_ACTIVE`

## Additional context

- [x] Will need to get Front Door URLs from SBMTD Azure.
- [x] Will need to configure Benefits with the correct header info for each server instance

**Comment by thekaveman** [comment]
We have everything working `dev` and `test` for eligibility verification. 

But we're blocked on moving to `prod` due to a connection issue with the Littlepay QA environment

**Comment by thekaveman** [comment]
Code has been deployed to `prod`.

Benefits is ready to integrate with SBMTD Mobility Pass server in `prod`.

**Comment by indexing** [comment]
@o-ram If we haven't already, please let SBMTD know that we are ready to enable the Mobility Pass pathway when they give us the thumbs up. If possible, it would be great to soft launch this pathway (no promotion) ahead of the end of the year, but—of course—this decision lies with SBMTD.

**Comment by thekaveman** [comment]
We have the green light from SBMTD to take the Mobility Pass verification / enrollment pathway live!

Currently planned for Wednesday January 31.

**Comment by angela-tran** [comment]
Smoke test for SBMTD Mobility Pass pathway passed - was able to connect and see the unverified page

**Comment by angela-tran** [comment]
@thekaveman did smoke tests for MST Login.gov, SBMTD Login.gov, and MST Courtesy Cards

**Comment by machikoyasuda** [comment]
🎊
