### ISSUE TITLE
Secondary button component

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1786]
# Overview

This issue specifies the design requirements for a secondary button component to be added to the Benefits component library. The secondary button should be used for less important actions or actions that are alternatives to the primary button and allows us to present two actions for a user in the same view. It should be visually distinct from the primary button, but still consistent with the overall look and feel of our application design.

# Design Requirements

- The secondary button should be visually distinct from the primary button. This can be achieved through the use of color, font, fill, or border styling.
- The secondary button should be consistent with the overall look and feel of our of our current application design.
- The secondary button should meet all accessibility requirements. This includes providing adequate color contrast, text size, and focus indicators.
- The secondary button needs the following states: enabled, disabled, hover, pressed, and processing. 

# Accessibility Requirements

- The secondary button should have a color contrast ratio of at least 4.5:1 between the text and background colors.
- The secondary button label should be at least 16px in size.
- The secondary button should have a focus indicator that is visible to users with low vision that is at least 2px wide and can be visually distinguished from the surrounding content.

# Usage Guidelines

- The secondary button should be used for less important actions or actions that are alternatives to the primary button in the same view. For example, the secondary button could be used for the "Cancel" button in a dialog box or the "Back" button in a navigation bar while "Get started" or "Next" are the primary actions.

The secondary button should not be used for the most important action on a screen. The primary button should be the most visually prominent button on a screen and should be used for the most important action that the user needs to take.

**Comment by machikoyasuda** [comment]
Just wanted to note that this PR for the Admin In-Person Verification feature introduces a seconday button component: https://github.com/cal-itp/benefits/pull/2317

<img width="850" alt="image" src="https://github.com/user-attachments/assets/b64b7959-1408-4429-aa54-4231642d96b7">

```
/* Buttons */
/* Primary Button: Use all three classes: btn btn-lg btn-primary */
/* Outline Primary Button: Use all three classes: btn btn-lg btn-outline-primary */
/* Set button width in parent with Bootstrap column */
/* Height: 60px on Desktop; 72 on mobile*/
```

For now, it mostly inherits an Outline button from Bootstrap: https://getbootstrap.com/docs/5.2/components/buttons/#outline-buttons and adds our colors and height, along with a hover color.

**Comment by indexing** [comment]
No current need for this button option in the rider-facing Benefits app.
