### ISSUE TITLE
Create docs page describing live / active agencies and flows

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1791]
Idea from @indexing as an additional way to document what features we have live.

**Comment by machikoyasuda** [comment]
Something like this: 

  | Older Adults | Veterans | Agency card | Initial launch date | Status |  
-- | -- | -- | -- | -- | -- | --
Monterey Salinas-Transit | X | X | X | 2022 | LIVE |  
SBMTD | X |   | X | 2023 | IN PRODUCTION VALIDATION |  
SacRT |   |   |   |   | IN REVIEW |  
... |   |   |   |   |   |  
... |   |   |   |   |   |
