### ISSUE TITLE
Enable Google SSO login for Admin

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1817]
The basic Django admin manages local user accounts for login and access control.

As we grow usage of the tool, we'd like to not have to manage specific user accounts, and would rather login via existing accounts, e.g. Google Workspace.

## Acceptance Criteria

- [ ] Engineers can login to the Admin using `@compiler.la` Google Workspace accounts

## Additional context

Potential options from a quick search (haven't evaluated any of these yet):

- https://github.com/megalus/django-google-sso
- https://github.com/matthiask/django-authlib
- https://github.com/pennersr/django-allauth
- https://github.com/SAML-Toolkits/python3-saml
- https://github.com/AngellusMortis/django_microsoft_auth (we might want this later)

We could also likely roll something with our existing [`Authlib`](https://docs.authlib.org/en/latest/client/django.html) package.

**Comment by machikoyasuda** [comment]
Going to go with https://github.com/megalus/django-google-sso - the same GitHub org/maintainers also maintain a very similar one for Microsoft SSO: https://github.com/megalus/django-microsoft-sso
