### ISSUE TITLE
Metabase auto-posts Benefits metrics to slack

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1849]
In order to keep others at Cal-ITP informed on the usage of the Benefits app, we'd like Metabase to post a snapshot of the [Benefits dashboard](https://dashboards.calitp.org/dashboard/42-cal-itp-benefits) to the #benefits-general channel in the Cal-ITP Slack workspace.
- Post weekly on Sunday at 10pm PST. 
- Ideally we post a graphic of the current dashboard so users don't have to follow a link to get current information and we have a running record of metrics that user can refer to without going to Metabase.

![Image](https://github.com/cal-itp/benefits/assets/6279581/2619f8d0-665d-4546-901e-ec2e3a520c6c)

**Comment by indexing** [comment]
I updated the schedule to auto-send to match the spec above.

![Image](https://github.com/cal-itp/benefits/assets/6279581/e6f74571-947d-4bde-b25e-eaeba6da610d)

**Comment by thekaveman** [comment]
We're getting a funky result via the dashboard notification -- the number of enrollments chart looks way off (timeline is messed up, numbers don't align with what we see in Metabase). 

Trying a different approach to alert on the chart itself, should know if it works or not by today at 4pm Pacific.

**Comment by indexing** [comment]
I reached out to Charlie Costanzo to see if he had any insights on a fix for charts displaying differently on the dashboard and the Slack postings. His research revealed its a long-standing issue—going back to 2017!

https://github.com/metabase/metabase/issues/5493

He noted there is activity as recent as 2 weeks ago, so perhaps we will see a fix soon. 

In the meantime, Charlie is going to work with the team managing Metabase to upgrade to the newest version (v 0.48.3) in the event a fix has been implemented that addresses our issue. I will post here with updates to the version so we can monitor for improvements.

cc// @thekaveman

**Comment by indexing** [comment]
Here's the issue to track the Metabase version upgrade: https://github.com/cal-itp/data-infra/issues/3247

**Comment by thekaveman** [comment]
Blocked waiting to see if the Metabase version upgrade solves the issue described above.

**Comment by thekaveman** [comment]
@indexing the Metabase upgrade is complete as of this morning. Let's be on the lookout for our charts posting into Slack and hopefully they are more like what we expect!

**Comment by indexing** [comment]
@thekaveman I just manually sent an update from the Metabase Benefits dashboard to [#benefits-general](https://cal-itp.slack.com/archives/C013W8RUAMU) and the output is the same. 😑 Since two of the four charts are accurate, I think the next step is looking at ways we can hack charts that work to convey the info we want.

**Comment by thekaveman** [comment]
@indexing bummer, I saw those! I moved this back to `In Progress` since we aren't waiting for any more upgrades etc.

**Comment by indexing** [comment]
@o-ram and I did some work last week to update the Benefits dashboard with new metrics and slightly revised charts. Somewhat miraculously the output to Slack now looks good. I wish we knew what change made the charts display properly, but we don't. Sometimes you create your own luck.

### Enrollments
![Image](https://github.com/cal-itp/benefits/assets/6279581/968bc3ef-f728-487d-be92-8a531ed7c27f)

### Reduced fare payments processed
![Image](https://github.com/cal-itp/benefits/assets/6279581/c551f5b9-c7e2-4121-8f8c-a9be71ff2119)
