### ISSUE TITLE
Add a `Payment error` view to support scenario when low-income re-enrollment isn't available. 

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1865]
The low-income enrollment pathway is the first that requires benefit expiration. We will utilize Littlepay's new API that allows us to attach expiration date as an attribute to funding source IDs. 

We will use this spec to determine when to make re-enrollment an option.

> After a rider successfully enrolls their card for a low-income benefit, they will be able to re-enroll for the same benefit beginning 14 days preceding the date when their benefit ends. The app will not allow re-enrollment in the first 351 days following enrollment.

In the event that a rider attempts to re-enroll before the 14-day window for re-enrollment opens, we need new error-handling in the app on the [Payment Error](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=9758%3A52813&mode=design&t=GJMlK8QBXBjzUM0p-1) view that communicates to the rider why re-enrollment wasn't successful.

**Comment by indexing** [comment]
FYI @srhhnry @thekaveman I added this issue to the scope of the "minimum viable enrollment pathway" for low income riders (#1677)

**Comment by srhhnry** [comment]
![Desktop_EligibilityError_Login](https://github.com/cal-itp/benefits/assets/5394204/913c8fea-3243-4302-8b86-1140e15a6ba9)
<img width="375" alt="Mobile_EligibilityError" src="https://github.com/cal-itp/benefits/assets/5394204/a2f5d2a2-3ed5-4925-b2ca-40e7e299f5c1">

Here's my initial pass at the error screen. Copy passes Flesh-Kincaid levels. The intent is the page would need to generate a calculation (date of expiration -/+ 14 days) to inform the user when they can return to re-enroll.

**Comment by thekaveman** [comment]
@indexing @srhhnry I think this issue can be closed?
