### ISSUE TITLE
Release 2024.01.1

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1867]
### Release manager

@thekaveman

### Smoke tester

@thekaveman 

### Release version

2024.01.1

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `dev` branch and secrets are up to date
- [x] Create a branch called release/version from the source branch 
- [x] Bump the application version
- [x] Open a PR for the release branch into `dev`, merge https://github.com/cal-itp/benefits/pull/1868
- [x] Ensure `test` secrets are up to date
- [x] Open another PR from `dev` to `test`, merge https://github.com/cal-itp/benefits/pull/1869
- [x] QA the app in `test`
- [x] Ensure `prod` secrets are up to date
- [x] Open a PR for the `test` branch into `prod`, merge https://github.com/cal-itp/benefits/pull/1870
- [x] QA the app in `prod`
- [x] Smoke Test the app in `prod`
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Tag the release on the `prod` branch, push the tag to GitHub (see [docs](https://docs.calitp.org/benefits/deployment/release/#5-tag-the-release) for commands)
- [x] Create a release in GitHub for the tag, generating release notes
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by thekaveman** [comment]
[Smoke testing](https://docs.google.com/document/d/1ADXWW4mfLJwLKVqtVemPNX9yTqYKqIWfCz1DipAU02g/edit) of `prod` was successful for all active enrollment flows.

**Comment by machikoyasuda** [comment]
Release notes published: https://github.com/cal-itp/benefits/releases/tag/2024.01.1
