### ISSUE TITLE
Use DJHTML to lint HTML, Django, Jinja tempaltes

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#188]
Created this ticket after #187 added Prettier linting for CSS and JS/JSON.

(Or find another tool for linting Django-flavored HTML)

**Comment by machikoyasuda** [comment]
Another option: https://github.com/Riverside-Healthcare/djlint

**Comment by thekaveman** [comment]
Yet another option: https://github.com/rtts/djhtml
