### ISSUE TITLE
Merging into one branch causes all environments to restart

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1880]
The expected behavior is for only the environment corresponding to the branch to restart.

See Slack discussions:
 - https://cal-itp.slack.com/archives/C022HHSEE3F/p1704916040354209?thread_ts=1704914522.128459&cid=C022HHSEE3F
 - https://cal-itp.slack.com/archives/C022HHSEE3F/p1707344329873899

We want to avoid restarting the app when it's not necessary, since it can sometimes cause a little bit of downtime.

**Comment by angela-tran** [comment]
This is from the Slack thread, but gonna put here too:

> Maybe it would be better to have the deploy GitHub workflow tell Azure to restart the specific app service
> This section has somewhat of an example: https://learn.microsoft.com/en-us/azure/app-service/app-service-sql-github-actions#build-push-and-deploy-your-image

**Comment by angela-tran** [comment]
Looked briefly into what we'd need to use the Azure Login action, but I don't have access to Microsoft Entra ID in the CDT directory so currently cannot make any progress on that

**Comment by thekaveman** [comment]
I think we can use the [`azure/webapps-deploy`](https://github.com/Azure/webapps-deploy/) action step with a Publish Profile per environment, avoiding the need to authenticate with a service principal and getting involved with Microsoft Entra ID.

## Plan so far

### `dev`

- [ ] Turn off webhook deploys (e.g. the `Container Registry` option) in the [Azure App Service "Deployment Center"](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourceGroups/RG-CDT-PUB-VIP-CALITP-D-001/providers/Microsoft.Web/sites/AS-CDT-PUB-VIP-CALITP-D-001/vstscd); instead choose the `GitHub Actions` option
- [ ] Fill in details for `GitHub Actions` deploy; don't generate a workflow file, we'll use the existing one
- [x] Create an environment variable to hold the name of the Azure App Service, `AS-CDT-PUB-VIP-CALITP-D-001`
- [x] Create an environment secret to hold the contents of the [Publish Profile for this App Service]()
- [ ] Add a step in the deploy workflow that uses `azure/webapps-deploy` with the above config
