### ISSUE TITLE
Investigate recent Content Security Policy errors

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1887]
These seem to be inconsistent at best, and hard to tell if they actually represent a failure state for end-users. I do not believe this rises to the level of an _incident_. 

See [Slack thread](https://cal-itp.slack.com/archives/C022HHSEE3F/p1711735934653959) with an example of how this can happen based on browser plugins.

## Expected behavior

We should not receive Content Security Policy (CSP) error reports for any script, stylesheet, or URL being loaded from the Cal-ITP Benefits app or our known 3rd-party service partners.

**Comment by angela-tran** [comment]
The deliverable is a quick write-up on this issue of why we think these errors occur and some data to show it's not something we can control

**Comment by thekaveman** [comment]
These can happen for a number of reasons e.g. user has a plugin or extension in their browser like from Facebook that injects scripts and other resources into Benefits, which are then blocked by our CSP.

We'll continue to monitor these types of Sentry notifications but otherwise there isn't any follow-up action at this time.
