### ISSUE TITLE
[DESIGN] Update last name help text on Mobility Pass form to indicate case sensitivity

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1907]
There is concern from SBMTD that the existing help text on the Mobility Pass form is not clear enough about the case-sensitivity of the `Last name` field, currently:

![image](https://github.com/cal-itp/benefits/assets/1783439/7decc34d-13f3-4e0e-8065-a02676d59a76)

The suggested copy change for the highlighted text is:

> This form is case sensitive.

## Acceptance Criteria

- [ ] English copy is finalized
- [ ] English copy is translated to Spanish
- [ ] The updated copy for both languages appears on the Mobility Pass form

**Comment by thekaveman** [comment]
@indexing initial assignment for you to finalize the English copy and get it translated to Spanish.

**Comment by indexing** [comment]
If we make this change for SBMTD, we need to evaluate making the change for MST as well.

**Comment by indexing** [comment]
@srhhnry is revisiting this form view, so I'm reassigning for the design phase.
