### ISSUE TITLE
Fix numbering on Low-income Basic Flow 

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1912]
The chart shows `11` steps:

![image](https://github.com/cal-itp/benefits/assets/1783439/c6dcf65b-d2f3-4f17-b2ca-0a6a882d1a71)

But the list only has `9` steps:

![image](https://github.com/cal-itp/benefits/assets/1783439/9bb32c81-4454-4428-9fcf-d3531250cfcf)

## Expected behavior

The chart is (correctly) showing all steps in the process, while the list presents a more plain-language (and still correct) version of the process. Suggest removing the numbering from the chart (other flow charts do not have numbering) to avoid confusion.

**Comment by indexing** [comment]
@thekaveman I can see how you read the diagram and the basic flow together, but my intent was for each to have a distinct purpose. 

- The diagram shows each technical step in benefit enrollment and the sequence of system actions, as well as the relationship, between services and platforms. 
- The basic flow, on the other hand, lists the steps a _user_ (transit rider) takes to complete enrollment. It describes both what the user does and how the system responds to those inputs.  

Including the step to choose a transit agency, for example, is too granular for the diagram as that's a UI interaction. Step 5 in the flow is brief and covers several backend calls and responses in the diagram.

Thus, I see them as complementary and don't believe they have to align verbatim. 

If we want to make it more clear that they are distinct, I propose adding a header to the diagram that reads something like _Technical Architecture_ and moving the the _Basic Flow_ header above the sequence.

**Comment by thekaveman** [comment]
@indexing I follow you. I think I was tripped up mostly on the _numbering_ on the flow chart, especially since the other flow charts do not have numbering. Should we be consistent here (one way or the other)?

**Comment by indexing** [comment]
@thekaveman For me, the numbering in the chart is a helpful affordance to understand the process as a sequence and the numbering makes it a bit easier to step through the phases when scanning. I do note the numbering is new in this diagram; I propose adding it to the others (which I will do). Any objections? Maybe add this as a task in #1812 ?

**Comment by thekaveman** [comment]
Closing as this is being tracked in #1812.
