### ISSUE TITLE
SBMTD: Update agency card name in Cal-ITP Benefits

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1922]
SBMTD is renaming its agency card to avoid confusion for riders about the purpose of its various passes. Their agency card is currently named `Mobility Pass` but will change to `Reduced Fare Mobility ID`. We need to scope how deeply we will update the name in backend aspects of the system.

## Acceptance Criteria

- [ ] We have identified everywhere `Mobility Pass` appears in the system and who is responsible for the change (our team or SBMTD)
- [ ] Cal-ITP has met with SBMTD staff to discuss and scope this name change elsewhere in the system. 

## Additional context

The user-facing text updates are being tracked in #1952 and scheduled for `2024 - Sprint 03`

There are many other areas where `Mobility Pass` appears in the system, such as in server names, URLs, etc. Prior to meeting with SBMTD, we need identify all areas where `Mobility Pass` appears and confirm how deeply they want to update. We also need to identify any tasks that would require effort from SBMTD IT staff.

**Comment by thekaveman** [comment]
For the March Sprint, engineering will analyze and document each occurrence of `Mobility Pass` and its variations (e.g. `mobility-pass`) both in user-facing text and application code, and indicate who would need to be involved in making the change and the relative level of effort.

The results of this analysis will be added as a comment to this issue.

**Comment by thekaveman** [comment]
We made the public-facing changes in #1952. We're not going to worry about these internal-only changes for now.
