### ISSUE TITLE
Google SSO redirect is not working for deployed environments

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#1931]
## To Reproduce

1. Go to `/admin` on test-benefits.calitp.org
2. Click on `Sign in with Google`
3. See error from Google about how our app was trying to redirect to a URI that is not registered for the attempted Google SSO flow

## Expected behavior
The user is able to login (assuming the domain on their email is allowed via `GOOGLE_SSO_ALLOWABLE_DOMAINS`).

## Additional context

The error message tells us the redirect URI given to Google is one that starts with `http`. The URI we registered of course starts with `https`, so the question is why is the scheme being lost?

Our reverse-proxy is [configured to set the `X-Forwarded-Proto` header](https://github.com/cal-itp/benefits/blob/dev/appcontainer/proxy.conf#L3) as instructed [in the `django-google-sso` docs](https://megalus.github.io/django-google-sso/callback/#the-scheme), and our Django app is configured to pass that header along in `request.META` for use by consumers [such as `django-google-sso`](https://github.com/megalus/django-google-sso/blob/main/django_google_sso/main.py#L52). So everything there seems to be set up correctly and should work _if the request coming into NGINX_ truly does have `https` as its scheme.

Some notes from https://github.com/cal-itp/benefits/issues/199 make it more apparent that the request into NGINX is probably not SSL-encrypted.

**Comment by thekaveman** [comment]
I reached out to DevSecOps to see about their help in diagnosing this issue further from the Azure FrontDoor side.

**Comment by angela-tran** [comment]
Huge shoutout to @cal-itp/cdt-devsecops for spending time with us today to check over the Front Door 🙏 

After we checked as thoroughly as we could that the Front Door -> App Service connection is using HTTPS, I started thinking about the connections/ports being used _after_ the App Service, i.e. within the Docker container.

This led me to look in our codebase for where the port is set, which led me to find [`WEBSITES_PORT="8000"`](https://github.com/cal-itp/benefits/blob/dev/terraform/app_service.tf#L60), which led me to Googling more about it, which led me to this:

From [Configure a custom container for Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/configure-custom-container?tabs=debian&pivots=container-linux#detect-https-session):

> ### Detect HTTPS session
>
> App Service terminates TLS/SSL at the front ends. That means that TLS/SSL requests never get to your app. You don't need to, and  shouldn't implement any support for TLS/SSL into your app.
>
> The front ends are located inside Azure data centers. If you use TLS/SSL with your app, your traffic across the Internet will always be safely encrypted.

Here are some StackOverflow posts that show real-world examples similar to our situation:
- https://stackoverflow.com/questions/66806085/azure-app-service-for-containers-is-forwarding-https-requests-as-http-to-my-cont
- https://stackoverflow.com/questions/73720068/expose-tsl-ssl-server-on-azure-app-service

Since the Front Door is configured to take HTTP requests and forward them to HTTPS, it seems like it should be ok to register an `http` callback URI. (In addition to seeming ok, it seems like our only option.)

**Comment by SaranyaRSamy** [comment]
[like]  Ramasamy, ***@***.*** reacted to your message:
________________________________

**Comment by thekaveman** [comment]
I went ahead and added the `http` version of the redirect URL to each of the `dev`, `test`, and `prod` environments in Google based on @angela-tran's research.

Google SSO for the Benefits Admin is now active for all 3 environments.

cc @indexing
