### ISSUE TITLE
[DESIGN] Additional states to support errors in the enrollment process with Littlepay

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1939]
During implementation to support the Backoffice API from Littlepay, the dev team identified error states that are not currently represented in the app when a transit rider has passed eligibility for a benefit and is completing enrollment of their debit or credit card with Littlepay.

We need four distinct states in the `Enrollment error` view.
- Generic 500
- User enrollment error
- System enrollment error
- Already enrolled error (covered separately in #1921) 

Each state—where possible—needs to inform the user what the next step is to resolve the problem. 

---
### 500 error
A general error state that typically results from a problem with the agency configuration. The fix is outside the users control; resolution will require support from the Cal-ITP engineering team and a fix will be in place within a few hours.
 
- Incorrect Backoffice credentials (error is from Cal-ITP side)
- Incorrect group configuration (error is from Cal-ITP side)

**Acceptance criteria:**
- [x] Review current copy for accuracy and alignment with all error states.
- [x] View content communicates the next step for the user.
- [x] Copy explains to the user what happened using plain language that can be comprehended at an 8th grade reading level.
---

### User enrollment error
An error state that results when a user incorrectly inputs card details and submits the Littlepay form.

**Acceptance criteria:**
- [x] View content communicates the next step for the user.
- [x] Copy explains to the user what happened using plain language that can be comprehended at an 8th grade reading level.
---

### System enrollment error
An error state that results from a problem with on the Littlepay platform. The fix is outside the user's control; resolution will require support from Littlepay and may take days to resolve.
- Failure to get a token on the `enrollment index` view. The disabled primary button with the label "Please wait..." never becomes active. (error is from the Littlepay side)
- Failure to enroll the card in a group (error is from the Littlepay side)
- Failure to tokenize card (error is from Littlepay side) 

**Acceptance criteria:**
- [x] View content communicates the next step for the user.
- [x] Copy explains to the user what happened using plain language that can be comprehended at an 8th grade reading level.
---

**Comment by indexing** [comment]
@thekaveman Please review for this issue for accuracy. Once confirmed, we'll begin the design phase.

**Comment by srhhnry** [comment]
Here is an initial pass on all three error states. @indexing and @thekaveman any notes/comments/edits?

500 Error: 
<img width="707" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/bf97c225-2cc9-4f82-92fe-a3cdd9bad87f">


User Enrollment Error: 
<img width="754" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/39dddaeb-fd09-4ccd-9bed-e6c09296fa16">

System Enrollment Error:
<img width="731" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/dfed9c6e-63ca-4fd0-81e5-05d531ca9a93">

For the 500 and System enrollment errors we would direct the user to the home page, as both errors  _might_ take long enough to correct that the user would get kicked out of Login.gov. For the user enrollment error, we take them back to the Littlepay window.

I tried to make the 500 error a bit more branded and verbose to help the user feel like someone is paying attention, and I also left it vague enough that it hopefully covers all support states.

**Comment by srhhnry** [comment]
All of these text elements pass accessibility standards and are located in Ditto.

**Comment by srhhnry** [comment]
Checking in on feedback @thekaveman and @indexing

**Comment by srhhnry** [comment]
Final pass on these error screens can be found here.

500 Error
<img width="632" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/daa1fbb1-2397-40f9-ae0a-1337fe4160cb">

User Enrollment Error
<img width="488" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/e7c33d59-ec5b-4b7a-8686-724f10326f6f">

System Enrollment Error
<img width="520" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/739b35bb-f222-4ffa-ad93-5a05e09c922b">

Already Enrolled Error
<img width="575" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/8a1e24f4-7ef8-4b08-a025-88fa29067946">

**Comment by indexing** [comment]
Handoff to devs is complete. 

@srhhnry Please add links to the Figma mockups for each error view before closing this issue. Thanks.

**Comment by srhhnry** [comment]
Final screens, all can be found at[ Error Screens in Figma](https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(Full-Application)?type=design&node-id=14206%3A20263&mode=design&t=5t85Q0mXpU8sGdUo-1). 

500 error
<img width="998" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/60c1fea8-8d2d-4b5e-9f02-4aa3edec88a4">

User enrollment error
<img width="623" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/c92bf6a6-e439-444a-9d7a-f62f98609d64">

Agency card eligibility error
<img width="690" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/b10a28d2-4c96-4a75-9d01-c7a3e4bf0685">

System enrollment error
<img width="689" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/b2326479-049b-4d7a-aab0-bfd63c439ebf">
