### ISSUE TITLE
Translate new CalFresh strings

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1941]
## Acceptance criteria

- [x] @indexing submits new strings to the translation service
- [x] @indexing receives translated strings back from translation service
- [x] @indexing verifies translations
- [x] engineering implements in the PO files
  - [x] #2069
  - [x] #2070
  - [x] #2071

**Comment by indexing** [comment]
I've added Spanish translations for the low-income enrollment pathway to [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing). See the `forTranslation` sheet; all new strings are at the end of the row list beginning at row 170, "Calfresh Cardholder."

For future reference, I've attached the CSV file with all strings.
[Cal-ITP Benefits Application Mar 14.zip](https://github.com/cal-itp/benefits/files/14672479/Cal-ITP.Benefits.Application.Mar.14.zip)

cc// @thekaveman

**Comment by thekaveman** [comment]
Thanks for the heads up @indexing! When you and @mrose914 have a chance to look over everything and verify, can you please respond in this thread so we know they are ready for implementation in the app?

**Comment by indexing** [comment]
I verified that translations and didn't note any overt issues. 

I also created #1971 for a person to QA the translations once they are in context in the app.

**Comment by thekaveman** [comment]
@indexing reopening since this is our issue for implementation.

**Comment by thekaveman** [comment]
Blocked until we have all the new CalFresh English strings in place

## Remaining tickets

- [ ] #1877
- [ ] #1917 
- [ ] #1919 
- [ ] #1921

**Comment by thekaveman** [comment]
Planning to add the CalFresh Spanish strings tomorrow 5/2.
