### ISSUE TITLE
SBMTD: Update agency card name in user-facing text

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1952]
SBMTD is renaming its agency card to avoid confusion for riders about the purpose of its various passes. Their agency card is currently named `Mobility Pass` but will change to `Reduced Fare Mobility ID`. We need update our Benefits application copy to display the updated name.

## Acceptance Criteria

- [x] There are no instances of `Mobility Pass` in user-facing copy in the Benefits application.
- [x] All references to SBMTD's agency card in user-facing copy in the Benefits application are `Reduced Fare Mobility ID`.
- [ ] ~Design files reflect the two criteria above.~
- [x] [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) master includes the updated name.

## Additional context

A larger research and scoping effort to determine all non-user-facing instances of `Mobility Pass` is being tracked in #1922

**Comment by thekaveman** [comment]
Re-opened and assigned to @srhhnry for the design file updates.

**Comment by srhhnry** [comment]
Checking in about this. We don't currently have screens for each agency (as over time this would become untenable). That said, I could either:

1. Screenshot with this new text as a point of reference (especially as it looks longer than our demo copy, which might affect # of lines)
2. Create a variant or variable of this agency-specific copy in Ditto and kick off that process for copy

**Comment by indexing** [comment]
I've updated replaced `Mobility Pass` with `Reduced Fare Mobility ID` in the [application copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) master.

cc// @thekaveman @srhhnry

**Comment by thekaveman** [comment]
Marking this as complete.
