### ISSUE TITLE
Add MST Courtesy Card Option and Document Info

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#197]
As a rider with a MST Courtesy Card, I want the option to sign up with a MST Courtesy Card so I can enroll in the contactless fare-discount demonstration. 

**Acceptance Criteria**
- [x] Riders can select senior or MST CC discount options. 
- [x] When a rider selects “Senior Discount Program ” and clicks “continue” they will be redirected to the senior discount document page
- [x] When a rider selects “MST Courtesy Cardholder” and clicks “continue” they will be redirected to the courtesy cardholder discount document page. 

**Resources**

- [Figma Large_Eligibility01](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=1618%3A4627)
- [Large_Eligibility1 MSTCC](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=1618%3A4615) 
- [MST Courtesy Card Holder User Stories Google Doc](https://docs.google.com/document/d/1wxEY4VsxOqqP7FydVXbW9NEzpLznnjpB_IedtzCAHe0/edit#)

**Comment by vykster** [comment]
This story is up to date with current screens linked all changes from MST feedback have been incorporated into screens.

**Comment by thekaveman** [comment]
Closed with the work in #317
