### ISSUE TITLE
QA Spanish copy on test-benefits.calitp.org for CalFresh Cardholders

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#1971]
Before deploying the low-income enrollment pathway to production, we need a person to review the Spanish translation of the copy in the Benefits app for cogency.

We'll use the general test plan for Spanish translation documented on the [manual tests section](https://docs.calitp.org/benefits/tests/manual-tests/#spanish-translation-testing) of our testing page, except that we only need to review the CalFresh Cardholder enrollment pathway.

1. Open the [test environment Benefits application](https://test-benefits.calitp.org/) in the test environment using a supported browser.
2. Click the Español button on the right side of the application header, to switch the application language to Spanish.
3. Click Elija su Proveedor and choose Monterey-Salinas Transit as your transit agency.
4. Follow the Titular de la tarjeta CalFresh / CalFresh Cardholder enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing). You will need a cell phone, a test Login.gov account and test Littlepay card credentials. 

> New in this pathway are dates. Please sure they display as expected for a native speaker.
> Please be sure to open the "more information" modal for CalFresh Cardholders and reviewing the help copy.

6. Click Ayuda in the footer to review the Help page. Review the (4) new questions for CalFresh Cardholders.
7. Jot down any issues or notes during the review. Highlight any proposed changes on the forTranslation tab in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet. Use the comment feature in Google Sheets to share your feedback. Please mention Andy Walker in each comment.

**Comment by thekaveman** [comment]
Blocked by #2189

**Comment by lalver1** [comment]
I reviewed the Spanish translation for the CalFresh flow using CST in the [Benefits test environment](https://test-benefits.calitp.org/). 

In particular, the new CalFresh items in "Ayuda", eligibility verified and unverified pages, and the re-enrollment error dates looked good. Since I could not reach the enrollment success page in the Benefits test environment because the test cards had already been enrolled, I reviewed the translation of enrollment success using the source files and everything looked good too.

**Comment by lalver1** [comment]
Thanks for the reminder @thekaveman! Yep, I was able to use one of those test cards to reach the enrollment success page. The copy looks good too 👍

**Comment by thekaveman** [comment]
@indexing I think we are good to close this?

**Comment by indexing** [comment]
@thekaveman Agreed!
