### ISSUE TITLE
Rider MST CC information successfully verified 

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#198]
* As a rider with a valid MST Courtesy Card, I want to share my program enrollment information and see that I am eligible to participate in the contactless fare-discount demonstration. 
* As a rider with an _invalid_ MST Courtesy Card, when I enter in my program enrollment information, I should get a screen that says my eligibility could not be confirmed.

**Acceptance Criteria**
- [x] Rider can view a form to enter their last name and MST Courtesy Card number. 
- [x] Rider can enter their last name and MST Courtesy Card number (last name must be the same case)
- [x] When rider inputs the correct credentials (card number and last name), and clicks “check status”, the rider is shown a “Checking” status in the status button. 
- [x] Rider information is successfully verified in the dataset
- [x] Rider is shown a success screen

**Resources**
- Figma File: [Large_Eligibility2 MSTCC](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=1618%3A4658)
- Figma File: [Large_Eligibility3 MST CC](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=1618%3A4703)
- Figma File: [Large_Eligibility4_Success](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=1618%3A4737)
- [MST Courtesy Card Holder User Stories Google Doc](https://docs.google.com/document/d/1wxEY4VsxOqqP7FydVXbW9NEzpLznnjpB_IedtzCAHe0/edit#)

**Comment by vykster** [comment]
@Indiajar needs to edit screen to provide an alternative to the word "database" in the title

**Comment by vykster** [comment]
All screens are updated are ready to go.

**Comment by thekaveman** [comment]
Initial work on these screens was done in #317.

Moving back to the Backlog as we shift priorities for next Sprint. This User Story will be completed when we fully integrate with a verification server for Courtesy Cards.

**Comment by MarikoLochridge** [comment]
This user story was tested by myself (@MarikoLochridge ) @afeld @angela-tran on the following devices and browsers. The UAT is complete. No bugs were found.

Device: MacBook Pro (Retina, 13-inch, Early 2015)
Application: Google Chrome

Device:	Google Pixel 6 (Android)
Application:	Chrome

Device: Moto E4 (Android 7.1.1)
Application: Chrome

Device: Windows 10 laptop
Application: Firefox
