### ISSUE TITLE
Look at implementing HTTP Strict Transport Security

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#199]
HTTP Strict Transport Security or HSTS:

> For sites that should only be accessed over HTTPS, you can instruct modern browsers to refuse to connect to your domain name via an insecure connection (for a given period of time) by setting the “Strict-Transport-Security” header. This reduces your exposure to some SSL-stripping man-in-the-middle (MITM) attacks.

From https://docs.djangoproject.com/en/3.2/ref/middleware/#http-strict-transport-security. We may want/need to do this at the Nginx level instead, see https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/

Crucial to this decision is the understanding that ~~the AWS Load Balancer~~ Azure App Service handles SSL connections for this app, and not the Django/Nginx system; the domain's certs and HTTP -> HTTPS redirection is all managed at the ~~AWS Load Balancer~~ App Service level.

See for example this app's [nginx.conf](https://github.com/cal-itp/benefits/blob/dev/nginx.conf#L29) in which the Nginx server is listening on port 8000 for connections - this is because the Load Balancer sits between the user and Nginx, handling the SSL and translation into the app container. In which case, trying to set this from within the app container may cause more problems than it solves.

**Comment by afeld** [comment]
Also [identified by Jemurai through Burp](https://drive.google.com/drive/folders/1Zb2risjywexN71l4D2jqe_cTiUUuHKVc). Can test at:

https://securityheaders.com/?q=https%3A%2F%2Ftest-benefits.calitp.org&followRedirects=on

**Comment by thekaveman** [comment]
Needs more investigation into how to do this outside of the app / within Azure's infrastructure.

**Comment by thekaveman** [comment]
This is not a priority for now, Azure handles SSL termination.
