### ISSUE TITLE
Resolve `RuntimeWarning` about interacting with database during `AppConfig.ready()`

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2003]
> Should we be worried about this / look into it further? What can go wrong if "the app registry has not been fully populated" / what does that even mean?

Looking into this a little further, I found some Django docs that correspond with the `RuntimeWarning` we're seeing. This section [warns against interacting with the database in `AppConfig.ready()`](https://docs.djangoproject.com/en/5.0/ref/applications/#django.apps.AppConfig.ready):

![image](https://github.com/cal-itp/benefits/assets/25497886/54f02f38-701a-4299-a36b-0284610c72ca)

Our [`OAuthAppConfig`](https://github.com/cal-itp/benefits/blob/027d3aebcff0dc8c9f84215e0e1b0a855c85981c/benefits/oauth/apps.py#L17) interacts with the database by [querying for all `AuthProvider`s](https://github.com/cal-itp/benefits/blob/027d3aebcff0dc8c9f84215e0e1b0a855c85981c/benefits/oauth/client.py#L44).

The "Application intialization process" documentation describes how the app registry gets populated and why "premature database queries are discouraged": https://docs.djangoproject.com/en/5.0/ref/applications/#initialization-process

But I'm not sure if there's a better place for us to register our Authlib configurations.

Maybe we should register each `AuthProvider`'s configuration upon the first attempt to actually use it?

_Originally posted by @angela-tran in https://github.com/cal-itp/benefits/issues/1809#issuecomment-1874724416_

**Comment by thekaveman** [comment]
Related: #1379

**Comment by angela-tran** [comment]
Exceptions from misconfiguration of AuthProviders could also be swallowed by the way the code works right now, and the fix to this ticket would also fix that
