### ISSUE TITLE
[TRACKING] Agency Card flow improvements

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2006]
Based on design specs in #1907 

## Acceptance criteria
- [x] #2007
- [x] #2010
- [x] #2011
- [x] #2012 
- [x] #2013
- [x] #2014
- [x] #2073
- [x] #2015
- [x] #2075 
- [x] #2076
- [x] #2022

**Comment by thekaveman** [comment]
This is done and was deployed to [`prod` in `2024.05.1`](https://github.com/cal-itp/benefits/releases/tag/2024.05.1).
