### ISSUE TITLE
`Enrollment success`: update copy and spacing

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2015]
![image](https://github.com/cal-itp/benefits/assets/25497886/dfca4eea-d1d5-448d-8f50-d2ce06b74994)

## Acceptance Criteria

- [x] Headline copy has changed 
- [x] Body copy has changed (mentions the transit agency more)
- [x] “You were not charged…” was moved down as its own separate sentence
- [x] Make sure the image is 40px below the heading
- [x] Make sure the spacing between heading and body copy should be 56px
- [x] Spacing is 16px between the body copy and the image

**Comment by thekaveman** [comment]
I think this work should happen on top of #1919 as that issue also updates the copy on this page.
