### ISSUE TITLE
Shift all screens so the headline is 148px spacing from the top (to follow 8-pt grid)

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2016]
While doing design review for #1907 / #2006, we (@indexing @srhhnry @thekaveman @angela-tran @lalver1) noticed that the designs in Figma call for spacing of 150px between the top of the page and the heading. We've been working towards using a 8-pt grid system for all designs (i.e. values for spacing are multiples of 8), and this would be an easy one to do.

## Acceptance Criteria

- [ ] Figma designs have been updated
- [ ] Once Figma is updated, devs implement code change

**Comment by angela-tran** [comment]
@indexing @srhhnry -- is this the right definition of 8-pt grid?

> We've been working towards using a 8-pt grid system for all designs (i.e. values for spacing are multiples of 8), ...

**Comment by indexing** [comment]
So, yeah, for a value that is currently 150, we'd choose either 152 or 144. Rounding to the nearest multiple, we'd go with 152. If the spacing looks too large, go with 144. Thoughts on one or the other @srhhnry ?

**Comment by machikoyasuda** [comment]
This task is now being done by #2540 so I think we can close this.
