### ISSUE TITLE
Implement error handling during authentication with the IDG for good UX

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2019]
## Overview

This is a follow-up to the minor incident documented in #2009.

We want to ensure that if errors are generated during the Auth interaction with IdG they are handled appropriately by the Benefits app, and users are given a meaningful error message.

This is related to the new error page design and scoping happening for #1939

## Eligibility verification error

This error state addresses errors result after a rider has authenticated with Login.gov and the Benefits requests the CDT Identity Gateway verify eligibility for the selected transit Benefit. The fix is outside the user's control; resolution will require support from the CDT team and may take hours to resolve.

The genesis for this error message is the incident documented in this [report](https://docs.google.com/document/d/15QLfupcL6KVfT54ZtBODZk8Mtahdvy9BDcqJ40VQKvE/edit#heading=h.78n6lxqhffn). 

“The technical manifestation of this issue was that when the Benefits application sent its request to the IdG, and the user completed their sign in with [Login.gov](https://github.com/orgs/cal-itp/projects/8/views/Login.gov), the IdG attempted to sign the token response back to Benefits with an expired certificate. This led to a failure in the IdG, with the resulting 500 response back to the Benefits app, causing a failure to parse the token response, which ultimately generated the Sentry notification.”

### Acceptance criteria:

**Design criteria**

- [x] View content communicates the next step for the user.
- [x] Copy explains to the user what happened using plain language that can be comprehended at an 8th grade reading level.
- [x] Copy is translated into Spanish

**Engineering criteria**

- [x] Implement this version
<img width="718" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/870a7e52-d43f-4135-8123-340236cc324f">

- [x] No surprises on spacing, colors, fonts, etc -- all the same as other error pages
- [x] In `oauth.views`, any error condition related to creating or using the `oauth_client` shows this error page
- [x] Whenever this error page is shown, a Sentry event captures the exception (this will be an explicit Sentry call)
- [x] We aren't handling the `error_code` case returned from IdG in this ticket

**Comment by srhhnry** [comment]
Screen for error that occurs on the Login side of the handoff
<img width="718" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/870a7e52-d43f-4135-8123-340236cc324f">

Screen for error that occurs on the IDG side of the handoff
<img width="710" alt="image" src="https://github.com/cal-itp/benefits/assets/5394204/f871da00-c401-4ac4-9054-cd1c3728db54">

All of the copy in these screens passes accessibility. Note the use of the sad bus icon as a decorative image. CTAs are to Return home (sentence case). 

I created two screens to cover more use cases, and am happy to talk through more about how they might work beyond the scope of this ticket.

**Comment by srhhnry** [comment]
Checking in on this ^

**Comment by indexing** [comment]
Design review scheduled for 6/12 to complete handoff.
