### ISSUE TITLE
[TRACKING] Convert app front-end to 8 point grid

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2025]
Aligning Figma and the app front-end on an 8 point (8 pixel) grid.

## Acceptance Criteria

- [x] #2016

**Comment by machikoyasuda** [comment]
With #2540 and the rest of the reCAPTCHA #2537 tickets, I believe a significant portion of this will be taken care of, and will allow us to delete a good amount of custom classes, CSS and simplify templates. I vote to close this issue, unless there are any other high-priority issues are found.

cc / @indexing @srhhnry

**Comment by indexing** [comment]
@machikoyasuda  I vote for closing this issue and addressing any elements that vary from the grid going forward as individual efforts.
