### ISSUE TITLE
Load Spanish translations for MST Courtesy Cards

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#206]
- As a spanish speaking rider with a MST Courtesy Card, I want to be able to view the tool in spanish so that I can sign up for the contactless fare-discount demonstration.

#### Acceptance criteria 
- [x] All MST CC screens and Help page can be toggled into Spanish mode and accurate Spanish translations are loaded

**Comment by vykster** [comment]
@thekaveman @machikoyasuda I know Lex loaded the last batch of spanish translation files. What do you need, or what is the process to add additional translated content for a new screen?

**Comment by thekaveman** [comment]
@vykster here's our current translation files:

* [English](https://github.com/cal-itp/benefits/blob/dev/benefits/locale/en/LC_MESSAGES/django.po)
* [Spanish](https://github.com/cal-itp/benefits/blob/dev/benefits/locale/es/LC_MESSAGES/django.po)

Each piece of text in there looks like:

```
msgid "id"
msgstr "This is where the text goes"
```

For pages like https://test-benefits.calitp.org/eligibility where the text is displayed in formatted HTML (labels, icons, lists, etc.) we have to break each one of those atomic text units into its own entry in the translation files:

```
msgid "eligibility.index.content_title"
msgstr "Great, you’ll need two things before we get started..."

msgctxt "image alt text"
msgid "core.icons.idcardcheck"
msgstr "Identification card icon with checkmark"

msgid "eligibility.index.item1.title"
msgstr "Your California ID"

msgid "eligibility.index.item1.text"
msgstr "Driver’s license or ID card"

msgctxt "image alt text"
msgid "core.icons.bankcardcheck"
msgstr "Bank card icon with contactless symbol and checkmark"

msgid "eligibility.index.item2.title"
msgstr "Your bank card"

msgid "eligibility.index.item2.text"
msgstr "A debit or credit card"

msgid "eligibility.index.p1"
msgstr ""
"This program is currently open to those who are 65 or older. Not over 65? "
"Get in touch with your transit provider to learn about other available "
"discount programs."

msgid "eligibility.index.button"
msgstr "Ready to continue"
```


(_Note_: we also have image alt text in here, so any new icons/images need alt text and translations).

So to start, it would help to break the Figma file into "atomic text units"; essentially each piece of text - word(s) and/or phrase(s) - that is displayed in a single string with the same formatting. Any time new formatting is introduced: bold, italics, size, lists, new paragraph, etc... it has to be a new "atomic text unit".

**Comment by thekaveman** [comment]
Initial work on this was done in https://github.com/cal-itp/benefits/issues/317.

Moving back to the Backlog as we shift priorities for next Sprint. This User Story will be completed when we fully integrate with a verification server for Courtesy Cards.

**Comment by o-ram** [comment]
@thekaveman Translations here: https://docs.google.com/document/d/1uzGaFF73CKoC7nftYhQ5329obHcz9SJj/edit

I highlighted the two places changes were made to the screens in yellow. They're very minor and India and I have already communicated about them, but I know you all are very busy right now so I want to make sure they don't get lost with everything going on :)
