### ISSUE TITLE
Translate all strings for `Improved UX for application error states`

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2074]
This issue addresses Spanish translations for the copy changes in this milestone: https://github.com/cal-itp/benefits/milestone/46

## Acceptance Criteria

- [x] @indexing submits new strings to the translation service
- [x] @indexing receives translated strings back from translation service
- [x] @indexing verifies translations
- [x] engineering implements in the PO files

**Comment by indexing** [comment]
I've added Spanish translations for the updates to our application error states to [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing). See the forTranslation sheet; all new strings are highlighted in yellow.

For future reference, and to provide an easier option for adding translations for these few views,  I've attached the CSV file that includes the error state strings. (The file also includes those for agency enrollment, but perhaps the smaller subset will make updating the PO files quicker.)

[Spanish-UX Improvements Error States05.01.2024.csv](https://github.com/cal-itp/benefits/files/15201737/Spanish-UX.Improvements.Error.States05.01.2024.csv)



cc// [@thekaveman](https://github.com/thekaveman)

**Comment by angela-tran** [comment]
The last of these translations were done in [#2088](https://github.com/cal-itp/benefits/pull/2088/files#diff-748b0299f076e6e9a7c2a8bd1ecae94e02768b9c07bd8a84ddfa4ebdb62752fd) - https://github.com/cal-itp/benefits/pull/2088/commits/95ec1066f193891a09e27f8e1d2b11090e9aa1fc
