### ISSUE TITLE
QA Spanish copy on test-benefits.calitp.org for `Improved UX for agency card enrollment`

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2076]
Before deploying the updates to the agency card enrollment pathway to production, we need a person to review the Spanish translation of the copy in the Benefits app for cogency.

We'll use the general test plan for Spanish translation documented on the [manual tests section](https://docs.calitp.org/benefits/tests/manual-tests/#spanish-translation-testing) of our testing page, except that we only need to review the agency card enrollment pathway.

1. Open the [test environment Benefits application](https://test-benefits.calitp.org/) in the test environment using a supported browser.
2. Click the Español button on the right side of the application header, to switch the application language to Spanish.
3. Click Elija su Proveedor and choose Monterey-Salinas Transit as your transit agency.
4. Follow the Tarjeta de cortesía / Courtesy Card enrollment pathway to completion using [test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit?usp=sharing). You will need a cell phone and test Littlepay card credentials.

Jot down any issues or notes during the review. Highlight any proposed changes on the forTranslation tab in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet. Use the comment feature in Google Sheets to share your feedback. Please mention Andy Walker in each comment.

**Comment by lalver1** [comment]
Locally tested using the `dev` branch since [`c07ae69 (Feat: enrollment success)`](https://github.com/cal-itp/benefits/commit/c07ae691452738c562e72716dc67ce6c98c7fa86) has not been deployed to `test` yet. Proposed 4 minor changes by commenting on the `forTranslation` tab in the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet.

**Comment by indexing** [comment]
@lalver1 I've accepted and updated the four minor copy changes on the `forTranslation` tab—all good suggestions.

**Comment by thekaveman** [comment]
@lalver1 do your proposed changes need to be applied to the language files in Benefits?

**Comment by lalver1** [comment]
Yes, that's a good point @thekaveman, I'll get started on a local branch and then will create a PR to merge them into `dev`.
