### ISSUE TITLE
QA Spanish copy on test-benefits.calitp.org for `Improved UX for application error states`

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2077]
Before deploying the updates to the application error states to production, we need a person to review the Spanish translation of the copy in the Benefits app for cogency.

Typically we use the general test plan for Spanish translation documented on the [manual tests section](https://docs.calitp.org/benefits/tests/manual-tests/#spanish-translation-testing) of our testing page, but for this review it will be difficult or not possible to produce the error states covered by this milestone. Thus, we will need to review the copy in Figma.

Jot down any issues or notes during the review. Please use the comment feature in Figma to share your feedback. Please mention Andy Walker in each comment.

**Comment by thekaveman** [comment]
@lalver1 it probably makes more sense to do this copy QA _locally_ instead of on `test-benefits`, since you'll have to edit the code slightly to induce the necessary errors.

See the instructions on the associated PRs

* #2088
* #2089
* #2117

**Comment by lalver1** [comment]
Thanks for the suggestion @thekaveman, I tested locally so I could induce the errors.

@indexing the Spanish copy looks good for these 3 associated PRs:

- #2088 (tested Login.gov and non-Login.gov flow)
- #2089 (tested Login.gov and non-Login.gov flow)
- #2117 (tested Login.gov and non-Login.gov flow)

I left 6 comments on the [Cal-ITP Benefits Application Copy](https://docs.google.com/spreadsheets/d/1_Gi_YbJr4ZuXCOsnOWaewvHqUO1nC1nKqiVDHvw0118/edit?usp=sharing) spreadsheet, one for each string that was checked. I guess that once you look over the spreadsheet and accept the comments we can close this ticket.

**Comment by indexing** [comment]
@lalver1 I believe I accepted all comments in the spreadsheet, so we can close.
