### ISSUE TITLE
Update documentation to reflect changes in the copy delivery process

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2218]
Revise this section of our documentation to include support for Ditto and any other changes in the process that result from adopting Ditto.

https://docs.calitp.org/benefits/product-and-design/copy-delivery/

## Acceptance Criteria

- [ ] Documentation accurately reflects current process.

**Comment by indexing** [comment]
@srhhnry You mentioned yesterday that you were writing down the "how" behind our Ditto implementation. Once we've ironed out the kinks in our approach, will you update this documentation?

**Comment by srhhnry** [comment]
Here's the current doc that outlines how Figma/Ditto/Crowdin work together: https://docs.google.com/document/d/1AZW63qNk25_vEkuzoIqZJt-T5QcLBLc2TEEwtGznz_k/edit?usp=sharing

Let me know if there are more questions or things that are unclear. To note, I've also tested the process for translating variants that's described here and it looks like it works pretty well due to all of the text being componentized.

**Comment by srhhnry** [comment]
@indexing or @thekaveman I think I need permission to edit the docs.cal-itp copy process page. I don't see a setting for it anywhere so I think I need a permission change?

**Comment by thekaveman** [comment]
@srhhnry you are on a GitHub team that has write access to this repository, so you should be able to edit the file and submit a Pull Request with your edits. This can be done directly within the GitHub website interface:

1. Navigate to the repository homepage: [https://github.com/cal-itp/benefits](https://github.com/cal-itp/benefits)
2. Navigate to the specific documentation markdown file inside the docs folder: [`docs/product-and-design/copy-delivery.md`](https://github.com/cal-itp/benefits/blob/main/docs/product-and-design/copy-delivery.md)
3. Click the edit (pencil) icon on the file to enter edit mode
![2024-08-26_14-59](https://github.com/user-attachments/assets/58e20143-81df-49d0-a6e7-96d090610d9d)
4. Make your changes in the markdown editor (previewing along the way if you like), and "Commit" when finished
![image](https://github.com/user-attachments/assets/d3ec5ade-a418-4cb9-b4f8-69d2168e0eda)

**Comment by srhhnry** [comment]
Documentation is complete in this doc: https://docs.google.com/document/d/1N-sVEEfo2ghklVDlbgvKWDr3fMjSlE4j8rC0_55OYJ0/edit?usp=sharing

@machikoyasuda volunteered to update the github docs site (thank you thank you!) with the completed copy.

**Comment by srhhnry** [comment]
Update: @machikoyasuda (and other interested parties): I added this section on Timeline:

Timeline
Design follows the sprint schedule set by Product and Engineering, however there is no standard number of sprints or time within a sprint dedicated to the copy process. Rather, the process timeline is determined by effort required.

Generally, Design will conduct research in an effort to determine parameters for the copy and to shape a first draft. Those parameters are then approved and/or finalized by Product. After that design then does a UX writing pass and further shapes the copy. Copy is reviewed by Product and then reviewed by Engineering during handoff.

Engineering requests that the copy is finished before the design review and before the next sprint starts (presumably the sprint the copy would be implemented in). Translating the copy takes about a week so it’s important to plan accordingly.
