### ISSUE TITLE
Model refactor: `AuthProvider`

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2233]
## Acceptance criteria

- [x] Model renamed to `ClaimsProvider`
- [x] Each field in the model definition has a description
- [x] Field `EligibilityVerifier.auth_provider` renamed to `EligibilityVerifier.claims_provider`
- [x] All variable instances and functions renamed to `claims` or `claims_provider` (e.g. `uses_claims_verification` instead of `uses_auth_verification`)
- [x] All comments updated to remove mention of "auth" or "auth provider", using "claims" or "claims provider" instead
- [x] Existing Django config data is migrated
- [x] Docs are updated

## Impact on the code

- [ ] [Code search for `AuthProvider` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+AuthProvider&type=code)
- [ ] [Code search for `auth_provider` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+auth_provider&type=code)
- [ ] [Code search for `auth_required` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+auth_required&type=code)
- [ ] [Code search for `auth_verification` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+auth_verification&type=code)
- [ ] [Code search for `client_name` in the repo](https://github.com/search?q=repo%3Acal-itp%2Fbenefits+client_name&type=code)

## Impact on existing data

- [x] Standard migrations for model/field renames should maintain existing data

## Impact on analytics

- [ ] [The `client_name` field is logged in analytics by setting the `auth_provider` event property](https://github.com/cal-itp/benefits/blob/main/benefits/oauth/analytics.py#L15). Since this field will be renamed in the code, we should rename the property in analytics.
- [ ] #2247 is a follow-up

## Impact on Admin permissions

- [x] [View permissions](https://github.com/cal-itp/benefits/blob/main/benefits/core/migrations/0014_staff_group_view_permissions.py) need to be updated for the new model name
- [x] [Edit permissions](https://github.com/cal-itp/benefits/blob/main/benefits/core/migrations/0015_staff_group_edit_permissions.py) need to be updated for the new model name
- [x] [Read only fields](https://github.com/cal-itp/benefits/blob/main/benefits/core/admin.py#L83) need to be updated with the renamed field

**Comment by angela-tran** [comment]
> Each field in the model definition has a description

@thekaveman Is this referring to setting [`help_text`](https://docs.djangoproject.com/en/5.0/ref/models/fields/#help-text)?

**Comment by thekaveman** [comment]
> > Each field in the model definition has a description
> 
> @thekaveman Is this referring to setting [`help_text`](https://docs.djangoproject.com/en/5.0/ref/models/fields/#help-text)?

I think so? I was thinking that since we're touching all the models, and in the Admin more, it would be useful to include descriptions that we can see in the Admin for each field. It looks like that is the field that shows up on the model form widget.

**Comment by angela-tran** [comment]
> - [ ] All variable instances and functions renamed to `claims` or `claims_provider` (e.g. `uses_claims_verification` instead of `uses_auth_verification`)

@thekaveman - I'm curious what you think of an idea I have:

I've been looking at the `EligibilityVerifier.is_auth_required` method and thinking about whether it should be renamed to `is_login_required` or `is_claims_required` / `are_claims_required`. The only place it's used is in the middleware called `LoginRequired` - [middleware.py#L134](https://github.com/cal-itp/benefits/blob/main/benefits/core/middleware.py#L134).

After looking over the code, I'm starting to think that there isn't any benefit to having these two separate boolean states of "does this verifier require login?" and "does this verifier use claims for verification?" Currently we don't have any use case where one of them would be true and the other is false, so I feel like it's just adding unnecessary possibilities.

It's even more apparent that these two booleans should really be one if you imagine there being both methods `is_claims_required` and `uses_claims_verification` on `EligibilityVerifier`.

I'm proposing we get rid of `is_auth_required` (moving the `self.claims_provider is not None` check into `uses_claims_verification`) and use `uses_claims_verification` in its place. I think this refactor would be small enough and is in line with the idea behind renaming `AuthProvider` to `ClaimsProvider`, which is that what this model really does is give us claims; authentication/login is just a means of doing that.

Wanted to get your feedback before I go ahead with any changes.

**Comment by thekaveman** [comment]
I think this is a great idea!
