### ISSUE TITLE
Transit agency staff should see a home dashboard upon logging in

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2246]
## Acceptance criteria
- [ ] `/admin` for **a transit agency user** shows the home dashboard UI (see mockup below)
- [ ] `/admin` for a superuser or Cal-ITP user shows the default Django admin index
- [ ] Buttons link to URLs that were defined in #2284 

#2268 will implement the "Transit processor" link, so don't worry about that part of the UI for this ticket.

![image](https://github.com/user-attachments/assets/deb3d808-e3a3-403c-9418-f54d11b19ff2)

**Comment by angela-tran** [comment]
Thanks @lalver1 for updating the issue description 🙏 

Here's a section from Django docs on CSS variables that drive the admin site's theming, in case it's helpful: https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#theming-support

**Comment by lalver1** [comment]
No problem @angela-tran 🙂
Ah, thanks for that! I was actually looking at how to override the template that `admin` uses, so this is very helpful!

**Comment by angela-tran** [comment]
@lalver1 and I met earlier to talk through how to conditionally show the home dashboard and the default index page. I had originally been thinking we would just override `admin/index.html` and use conditionals on the user to determine what to show, but after going through some of it with Luis, we came to the consensus that it'll be much cleaner to have a separate template.

The default index page is returned by the [`AdminSite.index`](https://github.com/django/django/blob/main/django/contrib/admin/sites.py#L552-L571) function, so in order to return a different template for transit agency staff users, we need to override this function.

Luis and I worked through putting the [necessary configuration](https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#overriding-the-default-admin-site) in place correctly so that there are no regressions and so that he can override `index`.

**Comment by angela-tran** [comment]
This ticket is pretty big. The plan is to do it in 3 PRs:
- [ ] Create a base template which defines the header navbar and includes the styles that every page will need at a minimum
- [ ] Implement and return the dashboard template for transit agency staff users in the `index` view function, except for the top-right `{% usertools %}` block
- [ ] Implement the top-right `{% usertools %}` block

cc @lalver1
