### ISSUE TITLE
Create a route to support sending users directly to `eligibility:confirm`

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2252]
As we work on the SBMTD flyer/mailer to message out the Benefits app to their riders with a _Reduced Fare Mobility ID_, we'd like to include a URL that will shortcut users as much as possible through the enrollment flow.

To that end, we should support a direct route into `eligibility:confirm` for the agency card flows.

## Acceptance Criteria

- [x] Create a URL that deep-links in the app so users can immediately enter agency card details without having to click though: Get Started > Select agency > Choose Benefit > Prepare (> Enter agency card details) 
- [x] A route exists to pre-configure a users' `TransitAgency` and ~`EligibilityType`/`EligibilityVerifier`~ `EnrollmentFlow`
- [x] The route takes the user to `eligibility:confirm` e.g. the eligibility confirmation form page
- [x] This route only works for flows utilizing the Eligibility API / forms -- show the user error page for other flows

## Additional context

See #1204 for how agency selection was implemented for `eligibility:index`. The work for this ticket can be done in a similar fashion.

**Comment by thekaveman** [comment]
Suggest waiting for #2236 to be complete before working on this.

**Comment by thekaveman** [comment]
For the URL:

* We don't expect users to actually type this in, rather scanning from a QR code or entering a bitly / shortname
* URL pattern will look something like `/<agency>/agency-card` e.g. `/sbmtd/agency-card`

**Comment by thekaveman** [comment]
Could start on this on top of #2293

**Comment by indexing** [comment]
@thekaveman I am encoding both URLs for the mailer today. To confirm, this is what I'm an using for each of the full URLs.

**QRCODE**
https://benefits.calitp.org/sbmtd/agency-card?utm_source=printed_mailer&utm_medium=QRCODE&utm_campaign=SBMTD_mobility-ID&utm_id=sep2024&utm_content=mobilityID_EN

**SHORT URL (https://bit.ly/sbmtd-enroll)**
https://benefits.calitp.org/sbmtd/agency-card?utm_source=printed_mailer&utm_medium=short_URL&utm_campaign=SBMTD_mobility-ID&utm_id=sep2024&utm_content=mobilityID_EN

**Comment by thekaveman** [comment]
@indexing in the current implementation they look like `/{slug}/agencycard` (i.e. no dash in agencycard).

I can update it if its too late.

**Comment by indexing** [comment]
@thekaveman Yes. Please add the dash so we use `/{slug}/agency-card`. 🙏
