### ISSUE TITLE
Release initial Admin permissions, OAuth error UX improvements, tag-based deployment, small UX fixes

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2255]
### Release manager

@lalver1

### Smoke tester

@angelatran

### Release version

`2024.07.2`

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `main` branch and secrets are up to date
- [x] Ensure `test` secrets are up to date
- [x] Create and push an annotated `-rc` tag on `main`
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Create and push an annotated tag on `main`
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
Smoke tested SBMTD Older Adult and Reduced Fare Mobility ID ✅

**Comment by lalver1** [comment]
Smoke tested Older Adult for MST
