### ISSUE TITLE
Hide native login fields

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2264]
To reduce confusion, we should hide the native login fields on the view for `/admin`.

## Acceptance Criteria

- [ ] The login page only has buttons for logging in with SSO

## Additional context
[Hiding the login form](https://megalus.github.io/django-google-sso/customize/#hiding-the-login-form)

**Comment by thekaveman** [comment]
> (Optional) There is a separate view for logging in with native login, for superuser use only

Yes please! :+1:

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran Just to confirm, is this `(Optional) There is a separate view for logging in with native login, for superuser use only` part of *this* ticket, or is it a future ticket? If it is part of this ticket, where should the separate view live?

**Comment by machikoyasuda** [comment]
Wait nevermind - found it ~ https://github.com/orgs/cal-itp/projects/8/views/9?pane=issue&itemId=74153500 @thekaveman @angela-tran

**Comment by angela-tran** [comment]
> @thekaveman @angela-tran Just to confirm, is this `(Optional) There is a separate view for logging in with native login, for superuser use only` part of _this_ ticket, or is it a future ticket? If it is part of this ticket, where should the separate view live?

Great question. It is a separate ticket - #2297. I forgot to link it here, thanks for asking!
