### ISSUE TITLE
Model and capture local enrollment events

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2267]
As we roll out the in-person eligibility and enrollment feature, we'd like to implement a basic enrollment log to support reporting or auditing requests from agencies -- in a way that is not tied to an external service.

Since Django already provides a framework for modeling this data, we can start simply by:

* Creating a new Django model like `EnrollmentEvent`
* Creating and saving an instance of this model when enrollment succeeds (digital and in-person)

### `EnrollmentEvent`

- [x] Django model defined in the usual `benefits/core/models.py` with migrations
- [x] Fields
  - [x] `id` (pk): [`UUIDField`](https://docs.djangoproject.com/en/5.1/ref/models/fields/#uuidfield) with default configured
  - [x] `agency`: `ForeignKey` to `TransitAgency`
  - [x] `flow`: `ForeignKey` to `EnrollmentFlow`
  - [x] `method`: `TextField` with `choices=["digital", "in_person"]`
  - [x] `verified_by`: `TextField`
  - [x] `enrollment_datetime`: [`DateTimeField`](https://docs.djangoproject.com/en/5.1/ref/models/fields/#datetimefield) with default to the current datetime when the model instance is created
  - [x] `expiration_datetime`: [`DateTimeField`](https://docs.djangoproject.com/en/5.1/ref/models/fields/#datetimefield)
- [x] All fields are required, except for `expiration_datetime`
- [x] All fields are read-only for all users (in production)
- [x] Model instances can be created, viewed, and deleted by `superuser` (except in production, where they are read-only)
- [x] Model instances can be viewed by `STAFF_GROUP_NAME` members in all environments, and added/changed in non-production environments
- [x] No other permissions for this model for any user
- [x] Implement `__str__` for default Admin display to output the `enrollment_datetime`

### Implementation

- [x] When a user successfully enrolls via the Benefits app interface, code creates and saves an `EnrollmentEvent`:
  - [x] `agency`: the agency from the user's session
  - [x] `flow`: the flow from the user's session
  - [x] `method`: `"digital"`
  - [x] `verified_by` depends on the value of `uses_claims_verification`
    - [x] `True`: `flow.claims_provider.client_name`
    - [x] `False`: `flow.eligibility_api_url`
  - [x] `expiration_datetime`: calculated enrollment expiry, if any
- [x] When a user successfully enrolls via the In-person interface, code creates and saves an `EnrollmentEvent`:
  - [x] `agency`: the agency from the user's session
  - [x] `flow`: the flow from the user's session
  - [x] `method`: `"in_person"`
  - [x] `verified_by`: `f"{user.first_name} {user.last_name}"` from the currently logged-in agency user
  - [x] `expiration_datetime`: calculated enrollment expiry, if any

**Comment by thekaveman** [comment]
We're not going to work on this right now for the MVP of the in-person eligibility and enrollment feature.

**Comment by thekaveman** [comment]
We'll

**Comment by thekaveman** [comment]
Updated this ticket to describe just modeling and capturing the data for an enrollment log. 

We'll come back to visualizing and reporting on this data later.
