### ISSUE TITLE
Enhance `EnrollmentFlow` model with field to indicate it is a pathway that can only be done in-person

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2287]
## Acceptance Criteria

- [x] We need a way to represent that a flow is digital-only, in-person only, or supports both.

**Comment by angela-tran** [comment]
Done shaping, need to ask for feedback

My thought on this is that this modeling reflects the use case we have in mind. We can refactor this field into something else if the use case changes.

**Comment by thekaveman** [comment]
Let's align the field naming here with what we choose for the property name in #2245 

@indexing suggests `method` for the name of the field/property. 

Devs suggest possible values of `digital` or `in_person`.

**Comment by thekaveman** [comment]
This can reuse some of the helpers introduced in #2367
