### ISSUE TITLE
Medicare cardholder: determine if sign out is supported

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2354]
Need to confirm with @johnatstate if the Blue Button API / interaction supports the notion of sign out.

**Comment by johnatstate** [comment]
Blue Button 2.0 does not support signout; however, the IdG does. You can submit an OIDC signout request to the IdG's endsession endpoint no matter the identity provider. Technically, as far as the Benefits app is concerned, the IdG is the IdP. Sure, it offloads the ultimate authentication to a third- (or even fourth-) party IdP, but Benefits is only interacting with the Identity Gateway, so it really doesn't matter if the authenticator supports signout.

**Comment by thekaveman** [comment]
@srhhnry @indexing FYI, we can display a "sign out" button/link for Medicare users. Do we want to update the designs for this?

**Comment by srhhnry** [comment]
I am not personally a fan of adding options for users to sign out. However, with Login we did want to satisfy some security concerns. As a compromise our sign out copy within the flow is small; it's to encourage users to stay on the path. Signing out before the user completes the flow doesn't provide much and can be either confusing or distracting. If there are no relevant security concerns with users accidentally being logged into the Medicare.gov account via the IdG, then I vote no sign out or we add a sign out to the last page (after the demo).

**Comment by indexing** [comment]
@thekaveman As you propose, let's revisit sign out for Medicare.gov until after the demo.
