### ISSUE TITLE
Medicare cardholder: configure flow in `dev` for CST

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2356]
Related to #2357

## Acceptance criteria

- [x] A new `EnrollmentFlow` instance is created via the `dev` Admin
- [x] The new flow's system name is `medicare`
- [x] The new flow is configured with appropriate IdG connection, and scope and claim #2363
- [x] The new flow is configured with templates created by related issues
  - [x] #2350
  - [x] ~#2351~ used in the radio button template, doesn't need to be configured on the model
  - [x] #2352
  - [x] #2358
  - [x] #2414 
- [x]  The new flow is configured with a label, the copy of which matches the label from `selection_label_template`
- [x] The new flow is configured with a group ID for a newly created group
- [x] The new flow is added to the CST transit agency
- [x] The new flow is first in the list of all CST flows (show it shows up first on the `eligibility:index` page)
- [x] The new flow confirms eligibility using a valid sample Medicare.gov account

**Comment by angela-tran** [comment]
Blocked until #2414 is merged (and deployed?)

**Comment by angela-tran** [comment]
I've finished configuring the flow and adding it to transit agency CST! You can now start trying it out at dev-benefits.calitp.org. 

<img src="https://github.com/user-attachments/assets/78fba9d7-2dc9-4627-bc83-a67febea5c70" width="350">
<img src="https://github.com/user-attachments/assets/7d21e652-cfd8-47b1-8385-df9082546bfd" width="350">    

<br/>
<br/>

The only thing is I'm not sure what test account to use to finish the eligibility confirmation. It looks like I'm taken to the real Medicare.gov site with a `redirect_uri` parameter in the URL that's pointing at `sandbox.bluebutton.cms.gov`.

![image](https://github.com/user-attachments/assets/6f11115c-c749-4c0b-98ce-6a3524d33a97)

**Comment by angela-tran** [comment]
Found some test credentials, details here: https://cal-itp.slack.com/archives/C037Y3UE71P/p1727725884145749?thread_ts=1727471059.798969&cid=C037Y3UE71P

Went through the full Medicare enrollment pathway with CST

![image](https://github.com/user-attachments/assets/0f50705d-0eed-48ad-8009-b9abbdf87792)
