### ISSUE TITLE
Medicare cardholder: `enrollment:success` - create success template

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2358]
We may not actually need a new template here, it could be the standard agency-specific success template.

## Figma screen

https://www.figma.com/design/nsTk6xsQ1o4pQtsJUNgA0D/Medicare-Cardholder-Pathway?node-id=9752-52650&m=dev
 
## Acceptance criteria

- [ ] This screen is shown upon successful enrollment via this flow
- [ ] English and Spanish is implemented for all copy
- [ ] ~The sign out link is available for the user~

**Comment by machikoyasuda** [comment]
I thought we aren't doing the Sign out link for now?

cc @srhhnry @thekaveman

**Comment by thekaveman** [comment]
> I thought we aren't doing the Sign out link for now?
> 
> cc @srhhnry @thekaveman

Yep you're right. I added that before we all talked about it.
