### ISSUE TITLE
Release update to littlepay 2024.09.1, new in-person views, Medicare enrollment pathway progress, and enrollment records

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2374]
### Release manager
@angela-tran 

### Smoke tester
@machikoyasuda 

### Release version

2024.09.2

### Slack thread

https://cal-itp.slack.com/archives/C037Y3UE71P/p1726685689483929

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `main` branch and secrets are up to date
- [x] Ensure `test` secrets are up to date
- [x] Create an annotated release candidate tag on `main` (`git tag -a YYYY.0M.R-rcR`)
- [x] Push the annotated release candidate tag (`git push origin YYYY.0M.R-rcR`)
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Create an annotated release tag on `main` (`git tag -a YYYY.0M.R`)
- [x] Push the annotated release tag (`git push origin YYYY.0M.R`)
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by machikoyasuda** [comment]
Smoke tested:
-     Older Adult for MST ✅
-     Veterans for MST ✅
-     Courtesy Card for MST ✅
-     Older Adult for SBMTD ✅
-     Reduced Fare Mobility ID for SBMTD ✅

**Comment by machikoyasuda** [comment]
Smoke tested:
- Older Adult for MST ✅
- Veterans for MST ✅
- Courtesy Card for MST ✅
- Older Adult for SBMTD ✅
- Reduced Fare Mobility ID for SBMTD ✅
