### ISSUE TITLE
Admin: Update all Admin app view titles

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2381]
This ticket is still in Needs shaping, and is a placeholder for @indexing to update the titles in Miro, so that devs can update the titles throughout the Adminstrator app.

---

Proposed title structure: `Agency name | View title | Name of app`

Examples: 

- /admin, not logged in: `Log in | Cal-ITP Benefits Administrator`
- /admin, logged in: `California State Transit | Dashboard | Cal-ITP Benefits Administrator`
- /admin, in-person enrollment flow: `California State Transit | In-person enrollment | Cal-ITP Benefits Administrator`

**Comment by indexing** [comment]
I've updated the titles in Miro. 

Currently, we have three main views in the app for agency users:
- **Log in** (Log in | Cal-ITP Benefits Administrator)
- **Dashboard** (Transit agency name | Dashboard | Cal-ITP Benefits Administrator)
- **In-person enrollment** (Transit agency name | In-person enrollment | Cal-ITP Benefits Administrator)

I've provided a single title for each view, but there is one to many _states_ for each view. For example, the in-person enrollment view has benefit selection, card details, loading, user enrollment error, system error, etc. I'm proposing we don't update the title to reflect each state. If we don't align on this approach I can differentiate, but I'm starting with the leanest approach.

Does this work?
