### ISSUE TITLE
Admin: In-Person - The Cancel / Go back button row is confusing

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2398]
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/89e8eb65-790b-4c2d-8152-42b937c9703c">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/a7fd0498-d7aa-4eb1-bf95-a43b735f875c">

It's too easy to accidentally click `Go back` in this view. We need a better design here.

**Comment by thekaveman** [comment]
Initial assignment to @indexing, who I think is already working on a new layout here.

**Comment by indexing** [comment]
I've updated the mock-up. 

I removed the `Go back` button entirely, so we now have a full-width `Cancel` secondary button. Thus, the single CTA in this view is now `Submit`.
