### ISSUE TITLE
Release new in-person features, analytics refactors, and Medicare Spanish copy

### ISSUE THREAD

**Issue by lalver1** [cal-itp/benefits#2411]
### Release manager

@lalver1

### Smoke tester

@angela-tran

### Release version

2024.09.3

### Slack thread

https://cal-itp.slack.com/archives/C037Y3UE71P/p1727374395820949

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `main` branch and secrets are up to date
- [x] Ensure `test` secrets are up to date
- [x] Create an annotated release candidate tag on `main` (`git tag -a YYYY.0M.R-rcR`)
- [x] Push the annotated release candidate tag (`git push origin YYYY.0M.R-rcR`)
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Create an annotated release tag on `main` (`git tag -a YYYY.0M.R`)
- [x] Push the annotated release tag (`git push origin YYYY.0M.R`)
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
Smoke testing:
- MST Older Adult ✅ 
- MST US Veteran ✅ 
- MST Courtesy Card ✅ 
- SBMTD Older Adult ✅ 
- SBMTD Reduced Fare Mobility ID ✅
