### ISSUE TITLE
Eligibility Start: Login.gov identity verification modal widow

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2432]
**Status**: Needs shaping and possibly design

## The problem

The Login.gov identity verification modal on the Eligibility Start page has what is known as a ["widow" in the print design world](https://en.wikipedia.org/wiki/Widows_and_orphans) - the way the external link icon hangs out by itself on a second line on the English version. The Spanish version's translation is long enough that the second line has more than one word.

![Image](https://github.com/user-attachments/assets/a2f7441c-7ee4-4b1b-9da0-c6f22e8f109d)
[Learn more about identity verification](https://test-benefits.calitp.org/eligibility/start#modal--identity-verification)

## Potential fixes

- **Easiest and fastest fix**: My initial thought, looking at this specific sentence, is to remove the word `Please`. I would feel comfortable only changing the English and leaving Spanish the same.
![Image](https://github.com/user-attachments/assets/eba7df8e-127f-484c-9516-a17daa4a0a22)
- Other options: Adding more horizontal margin/padding for _all_ modals. This is a much much much greater fix. 

If we're okay with my easy fast fix, this ticket is a 1. All other options would require a lot more effort for design and implementation and testing.

**Comment by machikoyasuda** [comment]
What is the status of this ticket? @indexing @srhhnry

**Comment by indexing** [comment]
We are going to revisit the design of modals and copy more broadly rather than simply addressing the issue here.
