### ISSUE TITLE
Setting up SBMTD in-person for October 17th

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2433]
- [x] Meet with @indexing to go over what is needed
- [x] Confirm SBMTD `EnrollmentFlow`s are configured correctly
   - [x] Check `label` is set to correct display value
   - [x] Check over other config for OAuth, eligibility-server API, transit processor   
- [x] Configure `TransitProcessor.portal_url`
- [x] Enable login fields
- [x] Set up accounts for transit agency staff members
   - [x] Check `Staff` checkbox for each user
   - [x] Prep for sharing (initial) passwords securely
- [x] Create `Group`s to set as `staff_group` and `customer_service_group` on SBMTD `TransitAgency`, and add users to groups
- ~Do an internal test enrollment (if we can delete the EnrollmentEvent) (or maybe it's ok if we see the user was one of us?)~ - we decided to hold off on doing this, see [this Slack thread](https://cal-itp.slack.com/archives/C037Y3UE71P/p1728597005282719?thread_ts=1728592143.795789&cid=C037Y3UE71P)
- [x] Prep to do a test run of in-person enrollment with the agency
   - Customer success will facilitate
   - Will run through it with a real eligible user so we don't have to go back and delete any test EnrollmentEvents
 - [x] Fix #2445 - #2446 
 - [x] Remove the "Change password" link so it doesn't distract from this beta test - #2447

**Comment by indexing** [comment]
cc// @o-ram

**Comment by angela-tran** [comment]
Prep work done
