### ISSUE TITLE
Set up Nevada County in `test`

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2434]
## Acceptance criteria

- [x] Meet with @o-ram to get the transit agency's information
- [x] Confirm that the transit agency and Littlepay have a contract
- [x] Obtain Back Office API Credentials from Littlepay (both for production and qa) 
- [x] A Nevada County Connects logo (small and large) is created and saved in `static/img/agencies`
- [x] A transit agency is created for Nevada County
  - [x] Create `index` template
  - [x] Create `eligibility index` template
  - [x] Enter a slug, short name, long name, info url, and phone
  - [x] Select a QA transit processor
  - [x] Enter transit processor's audience and client id
  - [x] Create the transit processor's client secret name in Azure Key Vault
  - [x] Enter transit processor's client secret name
- [x] A transit processor is created for Nevada County
- [x]  A NevCo Staff group is created
- [x]  A NevCo Customer Service group is created
- [x]  A NevCo user is created
- [x] Create `enrollment success` template
- [x] An Older Adult enrollment flow (digital/in-person) is created for Nevada County
  - [x] Enter system name, claims provider, scope, claim, and scheme
  - [x] Enter a label
  - [x] Enter a `group id` (use `Senior 65+` created in Littlepay)
- [x] A Medicare Cardholder enrollment flow (digital/in-person) is created for Nevada County
  - [x] Enter system name, claims provider, scope, claim, and scheme
  - [x] Enter a label
  - [x] Enter a `group id` (use `Medicare` created in Littlepay)
- [x] A Disability enrollment flow (in-person) is created for Nevada County
  - [x] Enter a label
  - [x] Enter a `group id` (use `Disability` created in Littlepay)
- [x] A Youth enrollment flow (in-person) is created for Nevada County
  - [x] Enter a label
  - [x] Enter a `group id` (use `Youth` created in Littlepay)

**Comment by lalver1** [comment]
Hi @o-ram, I was wondering if I could ask you some questions about Nevada County Transit. I can look at your calendar and send you an invite for today or tomorrow if that's ok.

**Comment by o-ram** [comment]
@lalver1 of course! Let's do tomorrow, I'm pretty open so pick whatever free time slot you'd like!

**Comment by lalver1** [comment]
Thanks! I'll send you an invite in a sec

**Comment by thekaveman** [comment]
@lalver1 this is marked `Done` in the project but still open. Should it be closed?

**Comment by lalver1** [comment]
Sorry about that @thekaveman, let me actually set it to 'In Review' in the project since Olivia is taking a look at `test` to make sure we don't need any changes to the copy.
