### ISSUE TITLE
Typo in Medicare modal / help copy

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2437]
## To Reproduce

1. On test-benefits.calitp.org (or dev-benefits.calitp.org), select "California State Transit" as your transit provider
2. Click the link shown in the "Medicare Cardholder" transit benefit radio button
3. See typo
4. Close out of modal
5. Click "Help" in the footer
6. Scroll to the Medicare questions
7. See typo

## Expected behavior

Instead of `if you have do not currently have`, it reads `if you do not currently have`.

## Screenshots

From test-benefits.calitp.org, in the radio button modal for Medicare.
https://cal-itp.slack.com/archives/C037Y3UE71P/p1728418993875589

![Image](https://github.com/user-attachments/assets/07438a84-9695-43d9-9f02-0878cdf77e33)

## Additional context

The typo is in our source of truth, Ditto, as well, so it should be updated there too.

![Image](https://github.com/user-attachments/assets/f82a9299-8e48-462a-9641-7a8e2841a4eb)

**Comment by srhhnry** [comment]
Fixed in Ditto in English. I thiiiiiiiink the Spanish doesn't have the same typo, but I'm not 100%

![Image](https://github.com/user-attachments/assets/53b1740b-08d7-4dde-a959-b606d1c35be2)
