### ISSUE TITLE
favicon doesn't show up on the Superuser's admin

### ISSUE THREAD

**Issue by lalver1** [cal-itp/benefits#2443]
Maybe need a future ticket: The favicon doesn't show up on the superuser homepage, but it does for the other admin pages: log in, log out, in-person flow pages. 

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/18279020-1f3d-4bfe-a336-2329702fa22d">

_Originally posted by @machikoyasuda in https://github.com/cal-itp/benefits/pull/2430#discussion_r1792263899_

The favicon is not showing up in the Superuser's admin page, but it seems like we can use the `extrahead` block of the `admin` app's `base.html` template to include it. So we may need to override the `admin/index.html` template and include the icon in the `extrahead` block.

**Comment by ohmegasquared** [comment]
![Image](https://github.com/user-attachments/assets/13149edb-326f-4b8c-804d-706d1776581b)

I explored an admin favicon option - using black Cal ITP style with the benefits label. 

@srhhnry what do you think about this option?

[favicon_io.zip](https://github.com/user-attachments/files/17386386/favicon_io.zip)

**Comment by srhhnry** [comment]
This is great! What a cool idea. Branding is not exactly my strength, but I wonder if we need the Cal-ITP blue on the Benefits banner? All black makes more aesthetic sense to me, but maybe both would be nice to have?
