### ISSUE TITLE
Add "Powered by" link to application footer

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2449]
We'd like visitors to the Benefits application to understand who is behind the planning, design, development, and maintenance of the software. We can add a simple link to the application footer, visible on all screens in the app.

I suggest placement at the far right side of the footer, within the overall container, e.g.

![Image](https://github.com/user-attachments/assets/913b57f1-b5c2-471a-987e-1be29d4794e3)

Use the following language:

> Powered by [Compiler LLC](https://compiler.la)

## Acceptance Criteria

- [x] Copy is translated to Spanish
- [x] Design for an additional footer link with the above text is done and handed-off to Dev
- [ ] Dev implements the link in Benefits app footer

## Additional context

Related to #2448

**Comment by thekaveman** [comment]
@srhhnry this is definitely a stretch goal for this Sprint, so no rush. Initial assignment to you for a (hopefully) quick and simple design.

We will need to translate this copy as well.

**Comment by srhhnry** [comment]
Initial design on desktop: ![Image](https://github.com/user-attachments/assets/47fd3cae-f164-43fc-86f0-1230862c68f0)


I'll need to figure out a mobile solution though as it's not as clear how that would work. Will update when I have it.

**Comment by machikoyasuda** [comment]
@thekaveman @srhhnry Is this design done and ready for development for this sprint?

**Comment by thekaveman** [comment]
I think we just need a translation for "Powered by" @machikoyasuda @srhhnry

**Comment by machikoyasuda** [comment]
Assigning myself for the dev tasks of this PR

**Comment by machikoyasuda** [comment]
@srhhnry Please submit this albeit tiny translation request to BabbleOn.

**Comment by srhhnry** [comment]
Design is merged, copy is updated to Ditto and synced to Crowdin. I've also informed Salim of the new translation need.

**Comment by machikoyasuda** [comment]
The Spanish translation is now live in Crowdin. From Salim: ` We were able to easily cover both using the TM so there is no charge for this one. Let me know if you need help with anything else.` TM is Crowdin's "Translation Memory" feature: https://support.crowdin.com/translation-memory/

**Comment by srhhnry** [comment]
The spanish translation is now synced to Ditto!

**Comment by thekaveman** [comment]
@srhhnry see my review comment here: https://github.com/cal-itp/benefits/pull/2460#discussion_r1803973084

Is it possible to make a slight change to the design?
