### ISSUE TITLE
Mobile and Tablet Prototype of Cal-ITP Benefits for Conferences

### ISSUE THREAD

**Issue by indexing** [cal-itp/benefits#2458]
@vykster Requested a prototype of the current Benefits app to demo on handheld devices at the upcoming CTA conference (Nov 20–22, 2024). We want a way to show booth visitors how the application works without having to manage test accounts, etc. 

### Requirements

- Displays all benefit options currently available in production. 
- Optimized for use on tablet devices.
- Optimized for use on mobile devices.

Ideally the prototypes will be complete by 11/15 so the team can test on each of the devices they will have at the booth ahead of the conference.

cc// @AnthonyRollins

**Comment by srhhnry** [comment]
I have a few clarifying questions:

- This is assigned to me, so I'm assuming this is for a Figma prototype. If so, we have to work with a few limitations. The current figma boards only accommodate a small mobile device or a small desktop/laptop screen. For a prototype to operate on a tablet device, we could likely display in _landscape mode only_ as is. If you all want portrait mode, I'll need to build that out. We won't have the ability to flip back and forth. 
- I can easily prototype interactive flows for Medicare, Agency Card, and then one of the Login flows (Calfresh, Older Adult, Veteran). If you all need _all of the flows_ to be interactive I'll have to set that up in the prototype but it will take some time. I'll start with building out the first three I mentioned and we can go from there.

**Comment by srhhnry** [comment]
Here is the link for a prototype at the mobile breakpoint:

https://www.figma.com/proto/xR80Mo48O7U9RR2ucMLP6U/Mobile-Prototype?page-id=5766%3A22626&node-id=9290-79436&node-type=canvas&viewport=138%2C258%2C0.03&t=8xtGV1jB7a2WhV79-8&scaling=scale-down&content-scaling=fixed&starting-point-node-id=9290%3A79436&hide-ui=1

It can run through abbreviated versions of the Medicare, Calfresh, and Agency flows. The Medicare flow only consists of one screen, as we were never provided mobile screens from the CMS team (and I haven't been able to wrangle any from the internet).

**Comment by srhhnry** [comment]
The prototype is merged into Main and so I'm closing this issue.
