### ISSUE TITLE
Update logo files for SacRT

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#2488]
From @machikoyasuda:

> I just noticed SacRT rebranded and even changed their logo (at least on their website)

![Image](https://github.com/user-attachments/assets/57a483a1-f5b9-4112-9a6d-fb2156d91839)

**Comment by thekaveman** [comment]
Blocked while we wait for the new logo files.

**Comment by indexing** [comment]
I've attached updated logos for mobile and desktop at 1x. Branding guidance doesn't provide an option to use the circular aspect of the logo only, so I've included the full wordmark (the full name of the agency with the logo). This approach aligns with the logos of other agencies, although the legibility of the logo at the mobile breakpoint isn't great.

![Image](https://github.com/user-attachments/assets/5d8999ce-cdbd-4b1e-9a81-4460c8159c09)
![Image](https://github.com/user-attachments/assets/f9633bf6-f9c8-451e-9d29-94291c7af782)

We can review this aspect of the implementation with SacRTonce it is in the application.

cc//@kegan

**Comment by indexing** [comment]
Here's a link to the branch in Figma that contains the new assets: https://www.figma.com/design/SeSd3LaLd6WkbEYhmtKpO3/branch/NBUBrNHp0MadB2JhbJIn1d/Benefits-(Full-Application)?m=auto&node-id=2-11&t=dF8NuXscYdfqlBSp-1

Note that SacRT only provided image files, there are no SVG files in the source they provided.
