### ISSUE TITLE
Decide how (if) to assign customer_ref

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#25]
## Background

Our discount provider's API includes a field `customer_ref` on the customer object, which can be set **one time** to a unique value (uniqueness as defined by the _API caller_, not the discount provider). This value is visible in the provider's Merchant Portal and serves as a way to correlate the customer with an outside record.

* There is no concept of a customer database or storage of customer transactions in `benefits`, so there is no way to track uniqueness
* `benefits` does not ask for any data beyond the basics necessary for eligibility verification, so we have no meaningful values to fill in here (e.g. email address)

## Options

1. Leave this blank
2. Generate a value using `uuid.uuid4()`
3. Correlate with e.g. an analytics ID
4. Something else?

I lean towards **1** since we don't really have a need for this right now, and I don't believe it is a required field in the API. 

//cc @vykster @calexity @krainboltgreene

**Comment by vykster** [comment]
I would also agree with 1 if it's not a required field.

**Comment by thekaveman** [comment]
Seems I was mistaken and `customer_ref` is a required field for API calls.

We'll go with Option 2 above as this is the simplest and maintains complete customer anonymity.

**Comment by thekaveman** [comment]
Just a quick follow-up; we've recently learned from the discount provider that their API will in fact _create_ a customer record automatically if one does not exist, during a query for said record. See #30 for the code update. 

The point in this issue is now moot, as we are not explicitly creating the customer record ourselves, and this field is not required in any subsequent calls. We'll leave it blank until/if we come up with a meaningful value.
