### ISSUE TITLE
Copy change request for SacRT: edit transportation type and add context regarding timeline

### ISSUE THREAD

**Issue by o-ram** [cal-itp/benefits#2505]
Make 2 copy changes to SacRT's benefits enrollment home page (page titled `Choose the transit benefit you would like to enroll in`), as per requests from SacRT conveyed to the payments team.

1. The transportation type on the page says that the reduced fare is available on light rail. However, SacRT's launch is going to be on bus only in early 2025, with light rail following later in the year.
2.  They would like to make it clear that the new system with the discount won't be available until early 2025.

## Acceptance Criteria
- [x]  The transportation type is changed to bus so it reads `All SacRT transit benefits reduce fares by 50% for bus service.`
- [ ] Add context to the first paragraph that tells the user this will be available in early 2025. Something like `All SacRT transit benefits will reduce fares by 50% for bus service starting in early 2025.` _See comment section for requested copy._
- [ ] All copy changes that are made are translated into Spanish as well

## Additional context

Task/request number one is the priority, so the transportation type is correct when SacRT announces this to riders (They are planning to announce this to the public on Thursday). The second request can follow after if need be.

Relevant slack thread: https://cal-itp.slack.com/archives/C013W8RUAMU/p1730828646175419

**Comment by o-ram** [comment]
For the second request about adding some launch timeline copy, the proposed copy change is: `With the new fare system launching in 2025, all SacRT transit benefits will reduce fares by 50%. This benefit will be available on all SacRT buses in early 2025 and will include light rail later in the year.`

**Comment by indexing** [comment]
The final copy approved by SacRT as noted here: https://cal-itp.slack.com/archives/C013W8RUAMU/p1730921766184889?thread_ts=1730828646.175419&cid=C013W8RUAMU

`With the new Tap2Ride fare system launching in 2025, SacRT riders that are eligible for discount fares can enroll below. The discount benefit will be available on all SacRT buses beginning in early 2025 and will include light rail tap devices later in the year.`

@srhhnry Please update Ditto and kick-off the translation process for this new copy.

**Comment by srhhnry** [comment]
This copy, along with a second, pared down paragraph, has been uploaded to Crowdin and translated by Babble-on. 
Mocks are here:
![Image](https://github.com/user-attachments/assets/297d9a9c-4ded-45a3-8e13-931e38625941)
![Image](https://github.com/user-attachments/assets/c4573940-82d0-4883-bca6-859bd2784a3f)

Waiting on direction from @indexing and SacRT for which direction of copy to upload back to Ditto.

**Comment by indexing** [comment]
We’re moving forward with the approved copy provided by SacRT as it is presented in the first screenshot.

`With the new Tap2Ride fare system launching in 2025, SacRT riders that are eligible for discount fares can enroll below. The discount benefit will be available on all SacRT buses beginning in early 2025 and will include light rail tap devices later in the year.`

cc// @thekaveman @srhhnry @angela-tran @lalver1
