### ISSUE TITLE
Release SacRT transportation type update

### ISSUE THREAD

**Issue by lalver1** [cal-itp/benefits#2506]
### Release manager

@lalver1

### Smoke tester
@angela-tran 

### Release version

2024.11.1

### Slack thread

https://cal-itp.slack.com/archives/C037Y3UE71P/p1730846971061249

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `main` branch and secrets are up to date
- [x] Ensure `test` secrets are up to date
- [x] Create an annotated release candidate tag on `main` (`git tag -a YYYY.0M.R-rcR`)
- [x] Push the annotated release candidate tag (`git push origin YYYY.0M.R-rcR`)
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Create an annotated release tag on `main` (`git tag -a YYYY.0M.R`)
- [x] Push the annotated release tag (`git push origin YYYY.0M.R`)
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by angela-tran** [comment]
Smoke testing on prod:
- MST Older Adult, unverified ✅ 
-

**Comment by angela-tran** [comment]
@lalver1 Smoke testing is complete and passed

**Comment by lalver1** [comment]
Release: https://github.com/cal-itp/benefits/releases/tag/2024.11.1
