### ISSUE TITLE
Set up a Medicare flow in prod

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2510]
Was started as a part of #2503 

We don't currently have a transit agency to add this to, but we can at least fill out the values we know a Medicare flow will need.

### Configuration changes
- [x] Configure a new `EnrollmentFlow` instance via the `prod` Admin
   - [x] System name is `medicare`
   - [x] Set the claims provider as the one created in #2503 
   - [x] Scope and claim is in Slack: https://cal-itp.slack.com/archives/C037Y3UE71P/p1722463462650049
   - [x] Configure extra claims: `disabled`
   - [x] Configure eligibility templates
      - [x] "selection_label_template": "eligibility/includes/selection-label--medicare.html"
      - [x] "eligibility_start_template": "eligibility/start--medicare.html"
      - [x] "help_template": "core/includes/help--medicare.html"
   - [x] Configure label as "Medicare Cardholder"
   - [x] Put in a placeholder group ID since we don't know which transit agency this flow will be for
   - [x] Leave "Enrollment success template" as the default since we don't know which transit agency this flow will be for

### Things to configure when there is a transit agency that wants to use this flow
- group ID
- enrollment success template
- transit agency

### Things to check when there is a transit agency that wants to use this flow
- [x] ~Check with @johnatstate that there is a Medicare test account filter in production~ - from [Slack](https://cal-itp.slack.com/archives/C037Y3UE71P/p1731084297080259?thread_ts=1731018366.364889&cid=C037Y3UE71P),
> The Medicare filter is part of this [deployment].

**Comment by angela-tran** [comment]
Pausing this until we have a transit agency to finish this out with.

**Comment by thekaveman** [comment]
@indexing now that MST is live, can we close this issue?
