### ISSUE TITLE
Release copy update for SacRT

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2515]
### Release manager

@angela-tran

### Smoke tester

@lalver1

### Release version

2024.11.2

### Slack thread

https://cal-itp.slack.com/archives/C037Y3UE71P/p1731439491885229

### What type of release is this?

Regular

### Regular release checklist

- [x] Ensure the `main` branch and secrets are up to date
- [x] Ensure `test` secrets are up to date
- [x] Create an annotated release candidate tag on `main` (`git tag -a YYYY.0M.R-rcR`)
- [x] Push the annotated release candidate tag (`git push origin YYYY.0M.R-rcR`)
- [x] QA the app in test
- [x] Ensure `prod` secrets are up to date
- [x] Create an annotated release tag on `main` (`git tag -a YYYY.0M.R`)
- [x] Push the annotated release tag (`git push origin YYYY.0M.R`)
- [x] Smoke Test the app in prod
- [x] Confirm acceptance of Smoke Tests by adding a comment to this issue
- [x] Edit release notes to link back to this Release process issue
- [x] Edit release notes with additional context, images, animations, etc. as-needed

**Comment by lalver1** [comment]
Smoke testing on prod:

- MST Older Adult, unverified ✅
- MST Veteran, unverified ✅
- MST Courtesy Card, unverified ✅
- SacRT Older Adult, unverified ✅
- SacRT Veteran, unverified ✅
- SBMTD Older Adult, unverified ✅
- SBMTD Reduced Fare Mobility ID, unverified ✅

**Comment by angela-tran** [comment]
Release: https://github.com/cal-itp/benefits/releases/tag/2024.11.2
