### ISSUE TITLE
reCAPTCHA: Agency Card form - Realign form, text and button

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2543]
- Desktop: Page text and buttons are now 6-columns and left-aligned
- Mobile: Ensure no regressions

**Comment by machikoyasuda** [comment]
I think this ticket may be mostly, if not entirely, complete when #2570 is merged. We'll see!

**Comment by machikoyasuda** [comment]
With the closure of #2570, Agency Card form page is also completed: 

![Image](https://github.com/user-attachments/assets/0108d2b0-9ff9-44b6-94b2-1fe42be05c0f)

**Comment by angela-tran** [comment]
Ticket status was changed to Done but ticket itself was not actually closed... I don't see why it should remain open, so closing it
