### ISSUE TITLE
reCAPTCHA: Enrollment index - Realign text, button

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#2546]
- Desktop: Page text and buttons are now 6-columns and left-aligned
- Remove manual breaks from h1 text
- Mobile: Ensure no regressions
- Don't forget CalFresh alert box page

**Comment by angela-tran** [comment]
Oh hmm, @machikoyasuda is this ticket the same as #2569? Not urgent

**Comment by machikoyasuda** [comment]
Oh oops, yes it is. I should have put Figma screenshots in these to be extra clear.
