### ISSUE TITLE
Enable the Medicare cardholder enrollment pathway for MST

### ISSUE THREAD

**Issue by o-ram** [cal-itp/benefits#2549]
MST has requested we enable Medicare cardholders in their agency instance in Cal-ITP Benefits.

## Acceptance Criteria

- [x] Additional products are associated with the group ([see comment below](https://github.com/cal-itp/benefits/issues/2549#issuecomment-2521953603))
- [x] Medicare cardholder appears in the list of benefit options a rider can choose when enrolling for transit discounts within the MST instance in Cal-ITP Benefits at https://benefits.calitp.org/mst

## Additional context

I (Olivia) anticipate creating the required group/product with MST during a regularly scheduled meeting on 12/4.

When this task in complete, transit riders will have four different benefit options from which they can begin enrollment.

Medicare cardholder
Older adult
U.S. Veteran
Courtesy Card 

Note: Medicare cardholder is always first in the list following design intent.

**Comment by machikoyasuda** [comment]
Very exciting @o-ram! Thanks for a well-written ticket.

Related: https://github.com/cal-itp/benefits/issues/2519

**Comment by thekaveman** [comment]
Blocking until we have

- [ ] Confirmation that Littlepay group has been created and configured
- [ ] The Littlepay group ID

**Comment by o-ram** [comment]
The group and products have been created!

Littlepay Medicare group ID: `2c869e5b-6ad7-444a-802e-f97861766954`

The newly created Medicare discount product should already be associated to this group, but here is the product ID just in case: `b6473f14-8521-4aca-9c53-dfae5e6e66a1`

We will need to associate the following 4 additional product IDs on the backend (for the capping products), due to the Littlepay restrictions on adding existing products to new groups within the portal:

`4f945c2e-7aad-4e1e-a3b0-043e92c055e9`
`380991bd-70d2-42ff-9219-cb105818bdde`
`1b82328e-a308-4f8e-bb93-0a1a13e6c849`
`cb07d634-da91-4cbf-b39d-a7351b82d327`

So, in total, this group ID should end up with 5 associated products.

Let me know if any of this isn't clear, and thank you!!

**Comment by thekaveman** [comment]
@o-ram @indexing are we ready to take this flow live for MST?

**Comment by o-ram** [comment]
@thekaveman yes, proceed! The flow can be pushed live cc @indexing

**Comment by thekaveman** [comment]
cc @machikoyasuda @angela-tran

**Comment by angela-tran** [comment]
@o-ram, in your message, you mentioned:

> So, in total, this group ID should end up with 5 associated products

but from @thekaveman 's [comment](https://github.com/cal-itp/benefits/issues/2549#issuecomment-2523931478), there are 6 associated products currently. This product is the extraneous one:
```
ProductResponse(id='9e16a9fc-782f-438d-80f4-73777fa404ea', code='Medi-Care Discount ', status='ACTIVE', type='DISCOUNT', description='Medi-Care Discount ', participant_id='mst')
```

@o-ram Is it ok that this product is linked to the group, or should we unlink it?

**Comment by o-ram** [comment]
Yeah, this is a duplicate because we edited the discount product after it was initially created, so Littlepay did that duplicate thing it still does.

If it's quick/simple to unlink that product ID, that would be nice to make the group clean, but it's not a must-have.

**Comment by angela-tran** [comment]
Working on config changes for prod Benefits.

Notes:
 
- Configure remaining fields on the flow created in #2510 ✅ 
   - Set its "Claims extra claims" to `disabled` as discussed in dev standup this morning
   - Set its "Group id" to `2c869e5b-6ad7-444a-802e-f97861766954`
   - Set its "Enrollment success template" to `enrollment/success--mst.html`
   - Saved (not connected to transit agency yet, so not live yet)

- Unlinking unnecessary product from group 👀

**Comment by angela-tran** [comment]
![Image](https://github.com/user-attachments/assets/39cf3288-218b-4faf-b482-530317817f48)
