### ISSUE TITLE
Styles in Benefits Administrator show regression

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#2551]
## To Reproduce

1. Go to `/admin`
   - The logo and header text is not centered
   - Seems like there's a lot of extra space in between the buttons
2. Login with a transit agency staff user (e.g. `cst-user`) 
   - Style regressions
3. Log out
   - More style regressions

## Expected behavior

Styling from initial release of Benefits Administrator with in-person enrollment is still intact.

## Screenshots

<details>

### Login screen
![Image](https://github.com/user-attachments/assets/75ce5da7-4ce8-4ffb-8cf4-10ff83f84306)

### Main screen
![Image](https://github.com/user-attachments/assets/33f7390c-f8e4-4385-858c-535a4569ab7e)

### Logout screen
![Image](https://github.com/user-attachments/assets/0a980d18-fb06-40d1-bcea-5e04f714c43f)

</details>

## Desktop 

- OS: Pop!_OS 22.04 LTS x86_64
- Browser: Firefox 
- Version: 132.0.2 (64-bit)

## Smartphone

N/A

## Additional context

I haven't looked into what change might've caused these regressions. I thought we weren't using the CA Web Template in Benefits Administrator, so I wouldn't have thought that #2526 would cause this, but that was a recent refactor.

**Comment by thekaveman** [comment]
Looks like we are including Bootstrap in two different places?

In #2526, @machikoyasuda updated Bootstrap to `5.3.3` in the main template and CSP settings. Is Admin including its own version?

**Comment by angela-tran** [comment]
Ah, I see. Yeah, Admin is including Bootstrap using its own include: https://github.com/cal-itp/benefits/blob/main/benefits/templates/admin/agency-base.html#L13, which wasn't updated to use 5.3.3.

Seems like it'd be good to consolidate how Bootstrap is brought in so that there's only one place to update.

**Comment by machikoyasuda** [comment]
Assigning myself!
