### ISSUE TITLE
Create new agency configuration checklist

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#309]
acceptance criteria

- [ ] Developer documentation created and deployed to docs.calitp.org
- [x] One-page write-up for a non-technical audience that can be shared with a transit agency interested in participating in the demonstration. 

**Resources**
- [SacRT Gantt Chart](https://docs.google.com/spreadsheets/d/1DV_nN8cI2Odp0xTIjPihqVObhdQ_-Ii7/edit#gid=1422500350)

**Deliverable**
- [Cal-ITP Benefits Transit Provider Onboarding: Seniors](https://docs.google.com/document/d/1D6li-i8ScY3D1-P-0qyh_9-UHwD6JGRyvf77V7LZncM/edit#)

**Comment by angela-tran** [comment]
Things we need from transit agencies:
 - their logo -- make sure to let them know what we need in terms of width, height, format, transparency, etc.
 - the URL and phone number that users should use if having trouble with Benefits app

**Comment by angela-tran** [comment]
@thekaveman For the dev docs to be published on [docs.calitp.org/benefits](https://docs.calitp.org/benefits), I'm thinking I'll add a section to the [Configuration](https://docs.calitp.org/benefits/configuration/) docs, named something like "Adding a transit agency". It'll basically document the process outlined in #1194. I'll also document more context around discount products and groups - e.g. who creates what (transit agency vs. Cal-ITP, product vs. group) and which environments need the product <> group association.

Should I avoid naming any specific payment processor even though the current process is very specific to the one we're working with?

**Comment by vykster** [comment]
I think it's totally find to reference the vendor! We might want to phrase it more like "For transit providers using Littlepay as their payment processor..." (and maybe even sneak a link into the mobility marketplace). 

Imply at least that we expect/ it's possible that this can be/ will be used to support integration with other processors.
