### ISSUE TITLE
Update Help Pages for better User Experience

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#315]
Based on feedback from MST staff, changes to help pages to improve user experience

Todo:

- [ ] Review draft help page with staff (Olivia, MST)
- [x] Update Help page content with new sections / paragraphs, using existing `core/help.html` template
- [x] Make new sub-sections anchor links e.g. `#payment-options`
- [x] Remove/ delete any links to `core:payment_options`
- [x] on Footer, remove link to "Payment Options"
- [ ] on Eligibility Start page, change link "How do I know if I have a contactless card" to /help
- [ ] on Eligibility Start page, change link "what if I don't have a bank card" to /help
- [x] on Enrollment Start page, change link "What if I don't have a bank card" /help
- [x] update UI tests for Help page, incorporate UI tests for removed Payment Options

Resources

 - ~[Large_SupportingPage_Help V2](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2004%3A6408)~
- [Desktop Help](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10895)

**Comment by thekaveman** [comment]
Co-opting this issue for part of #363 since we need a new Help page and it hits most of these marks. Adding a few extra items to the list.

Here's the Figma mock of the new consolidated help page: https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10895
