### ISSUE TITLE
Update EligiblityVerifier model to support custom text content

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#319]
## Background

In #317, we identified a number of user-facing text elements on various pages during the Eligibility Verification process that must be configurable based on how the user is verifying their eligibility.

A straightforward way to represent these variable text elements is store them with the `EligibilityVerifier` model instances. We'll store the text that represents the `msgid` in a `.po` language file instead of storing the actual text content directly, to maintain the app's internationalization (see also #318).

While the lines of ownership for some text content can be blurred between `EligibilityType` and `EligibilityVerifier`, for now we'll store everything with the verifier for ease of management.

## Attributes to add

Consider this list to be a starting point based on an initial read of the new UI designs. Each of these should be added as a `TextField` to the [model class](https://github.com/cal-itp/benefits/blob/dev/benefits/core/models.py#L56), and we can just update the [initial migration](https://github.com/cal-itp/benefits/blob/dev/benefits/core/migrations/0001_initial.py) since most of the new fields can't be null and we'll just rebuild the database from scratch anyway.

* [x] `selection_label`: Shown when the user is selecting from a list of verifiers
* [x] `selection_label_description`: (optional) Additional helper text shown under the main label
* [x] `instructions_content_title`: The title shown on the instructions page for the verifier
* [x] `instructions_item_name`: The name given to the verification item needed
* [x] `instructions_item_description`: The description given to the verification item needed
* [x] `instructions_blurb`: The main text blurb shown on the instructions page
* [x] `form_title`: The title of the form page
* [x] `form_content_title`: The title of the form page's content
* [x] `form_blurb`: The main text blurb shown above the form
* [x] `form_sub_label`: The label for the `sub` field on the form
* [x] `form_sub_placeholder`: The placeholder for the `sub` field on the form
* [x] `form_name_label`: The label for the `name` field on the form
* [x] `form_name_placeholder`: The placeholder for the `name` field on the form
* [x] `unverified_title`: The title of the unverified page
* [x] `unverified_content_title`: The title of the unverified page's content
* [x] `unverified_blurb`: The main text blurb shown on the unverified page

## Additional tasks

* [x] Update fixtures with new model attributes, and copy in the corresponding `msgid` from the `*.po` files

**Comment by angela-tran** [comment]
While updating the fixtures as a part of my PR #331, I noticed that the Form page has a page title reading "Confirm your age". This is coming from the `eligibility.pages.confirm.title` entry in our .po files. I think two options we have to resolve this are:
 - Option 1: change the wording to something generic like "Confirm your eligibility"
 - Option 2: add a field to `EligibilityVerifier` to provide a verifier-specific page title

![image](https://user-images.githubusercontent.com/25497886/159051607-e560caac-8d32-4811-a0bc-9fe7fd913dbf.png)

**Comment by angela-tran** [comment]
RE: the section of #317 that says

> ### Success page
> 
> *Investigate if this needs to vary?*
> 
> ### Failure page
> 
> *Investigate if this needs to vary?*

Currently the failure page is worded specifically to the verifier:   

![image](https://user-images.githubusercontent.com/25497886/159059334-e0cbdc6e-75cc-4d66-8e28-1cc77d9ac887.png)


https://github.com/cal-itp/benefits/blob/5c824f67d6a400d0f3dbd71d2ad05304f2318c26/benefits/locale/en/LC_MESSAGES/django.po#L314-L319

https://github.com/cal-itp/benefits/blob/5c824f67d6a400d0f3dbd71d2ad05304f2318c26/benefits/locale/en/LC_MESSAGES/django.po#L327-L330

The success page doesn't seem to need any changes.

![image](https://user-images.githubusercontent.com/25497886/159059459-4f8e7314-d504-4de7-ad68-0678b6d0f5b4.png)

**Comment by thekaveman** [comment]
@angela-tran nice catches!

RE `eligibility.pages.confirm.title`: let's go with Option 2 (get that in the model too please)

RE the failure page, yeah looks like we need to model at least the title and initial blurb. The "Reach out to your transit provider..." line can probably be reused so no need to model.
