### ISSUE TITLE
Enable SQLite database exploration in devcontainer

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#341]
[`datasette`](https://github.com/simonw/datasette) ([datasette.io](https://datasette.io/)) is a "tool for exploring and publishing data" from Simon Willison. It can be used to quickly spin up a web-based environment for looking at / querying e.g. a SQLite database file.

Check out the [datasette docs site](https://docs.datasette.io/), in particular the section on [Installation using Docker](https://docs.datasette.io/en/stable/installation.html#using-docker).

Let's get a Docker image running within the devcontainer setup, pointing to the app's `django.db` database file. Add some light docs for how to access the `datasette` interface and link out to their more comprehensive usage docs.

This will help with debugging and verifying local app configuration, migrations status, etc.

**Comment by thekaveman** [comment]
@angela-tran you showed us something a few weeks ago where you opened a SQLite database directly in VS Code... can you remind me what it was that you did?

I'd like to implement either that or get `datasette` installed for exploring our local Django database in Benefits.

**Comment by angela-tran** [comment]
@thekaveman Sure. It was when I was working on https://github.com/cal-itp/eligibility-server/pull/148. If the SQLite database file is named with a `.sqlite` extension, then VS Code will open it with a nice viewer.

I think all we'd need to do is rename `django.db` to `django.sqlite` and update our [settings](https://github.com/cal-itp/benefits/blob/dev/benefits/settings.py#L171).

**Comment by thekaveman** [comment]
@angela-tran I'm not sure this works out of the box (to view a SQLite file)? Was there a specific extension you used in VSCode?

**Comment by angela-tran** [comment]
I just noticed I do have a SQLite Viewer extension installed locally! The id is `qwtel.sqlite-viewer`. 

My guess is that I was trying out extensions when I first installed VS Code on my work computer last year. 🤔

**Comment by thekaveman** [comment]
Nice! I'll work on adding that so we can close this! Thank you
