### ISSUE TITLE
Eligibility index does not reset eligibility types

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#346]
## Steps to Reproduce
1. Once #344 is merged, follow the steps under **Testing** in #338 (copied here for convenience):

> * [x] Remove your local db and local compiled language files, then run `bin/init.sh`
>   * [x] Observe that the migrations run correctly, the fixture data is loaded, and the language files are compiled
> * [x] Open the app locally and select the agency configured above with multiple verifiers
>   * [x] Observe the `eligibility:index` view with different verifier selections
> * [x] Select one of the verifiers
>   * [x] Observe the verifier-specific `eligibility:start` view
>   * [x] Confirm verification of a test user
> * [x] Go back to `eligibility:index` and select the other verifier
>   * [x] Observe the verifier-specific `eligibility:start` view
>   * [x] Confirm verification of a test user

## Expected Result
For the last step, you should see a verifier-specific `eligibility:confirm` view / form and fill that out to then see the success page.

## Actual Result
You go straight from the second verifier's `eligibility:start` view to the success page due to your previous successful verification with the other verifier.

**Comment by thekaveman** [comment]
@angela-tran hmm, [`eligibility:index` does reset the eligibility types](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/views.py#L20):

```python
@decorator_from_middleware(middleware.AgencySessionRequired)
def index(request):
    """View handler for the eligibility verifier selection form."""

    session.update(request, eligibility_types=[], origin=reverse("eligibility:index"))

    # ...
```

But looking closer at the [`session.update()` for the `eligibility_types` parameter](https://github.com/cal-itp/benefits/blob/dev/benefits/core/session.py#L203), I think that is the problem:

```python
if eligibility_types is not None and isinstance(eligibility_types, list):
    logger.debug(f"Update session {_ELIGIBILITY}")
    if len(eligibility_types) > 1:
        raise NotImplementedError("Multiple eligibilities are not supported at this time.")
    elif len(eligibility_types) == 1:
        # get the eligibility corresponding to the session's agency
        a = models.TransitAgency.by_id(request.session[_AGENCY])
        t = str(eligibility_types[0]).strip()
        request.session[_ELIGIBILITY] = a.get_type_id(t)
```

We aren't actually clearing the eligibility from session!
