### ISSUE TITLE
Update informational pages

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#355]
As a transit rider I want to know what to expect so I can be prepared to sign up quickly. 

Todo:
- Update transit agency select page
- Update direct entry screen text
- Update getting started screen to include login.gov content

Resources:
- Figma File [Desktop_Indirect_Entry](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2133%3A10112)
- Figma File [Desktop_Direct_Entry_Screen00](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2133%3A10163)
- Figma File [Desktop_Screen01_GetStarted](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2133%3A10407)

**Comment by thekaveman** [comment]
This is finished.

See #315
See #365
