### ISSUE TITLE
Log-out of login.gov

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#356]
As a transit rider I want to be able to log-out at any point of the process if I decide not to continue. 

Todo: 
- Logout button is on all pages after login (screens 02/03, 04)
- User redirected to home if they logout

Resources:
- Figma file [Desktop_Screen02_DMVForm](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10517)
- Figma file [Desktop_Screen04](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10752)

**Comment by thekaveman** [comment]
This is finished. See #368.
