### ISSUE TITLE
Auto log-out on browser close

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#357]
As a transit rider I want to be auto logged out of login.gov when I close the browser so that I know my account information is secure. 

Todo:
- User logged out if they close the browser window
- Update text on success screen

Resources: 
- Figma file [Desktop_Screen06_Success](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10828)

**Comment by afeld** [comment]
The Benefits session gets deleted on browser close; [we can't log them out of Login.gov without a redirect](https://github.com/cal-itp/benefits/issues/381#issuecomment-1102993355). Considering this complete.
