### ISSUE TITLE
Learn more about login.gov

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#358]
As a transit rider who has never used login.gov before I want to learn more about this new service. 

Todo:
- update help pages text. 

Resources:
- Figma File [Desktop_Screen06_Success](https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Courtesy-Cards)?node-id=2148%3A10828)

**Comment by afeld** [comment]
Is this complete? Seeing info about Login.gov on [the Eligibility Start page](https://dev-benefits.calitp.org/eligibility/start) and [the Help page](https://dev-benefits.calitp.org/help).

**Comment by thekaveman** [comment]
Yep!
