### ISSUE TITLE
Simplify application index page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#366]
## Background

We expect most users to come in to the app through a direct link to their agency's entry page, In other words, via [`core:agency_index`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/views.py#L61) rather than [`core:index`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/views.py#L39). Since every user has to eventually go through the agency entry page and will read the content, we'd like to simplify the view on the application index to help avoid confusion and direct the user into the main flow. 

### New look

![image](https://user-images.githubusercontent.com/1783439/160696055-78f3fd3b-6200-4024-8dbb-7720b1d978c5.png)

## Tasks

* [x] #433
* [ ] #432
* [ ] #431

**Comment by angela-tran** [comment]
Closing this issue since it was broken out into 3 separate issues.
