### ISSUE TITLE
Research ITIN coverage in US

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#384]
Find research papers, user research studies, and data to understand and support a case for a feature request to support ITINs in addition to SSNs for riders who do not have SSNs.

**Comment by vykster** [comment]
@Indiajar @srhhnry this is a request for assistance from the identity team, I'm also going to ask a few of my contacts -- but for now the IAL2 identity proofing requires a SSN and we are guessing this is not sufficient to serve our target populations. Let me know if you have more questions --- but maybe time box this to 8 hours?

**Comment by vykster** [comment]
Examples in Homelessness and HMIS systems: (not that we are likely to integrate with an HMIS system any time soon)

- [service providers are not allowed to refuse service to an individual who does have or refuses to provide an SSN ](https://www.hudexchange.info/faqs/reporting-systems/hmis/data/data-standards/if-a-person-does-not-have-a-social-security-number-ssn-or-refuses-to/)
- unless they are a veteran/ entering via VA service programs (via [VA guidelines p20](https://www.va.gov/HOMELESS/ssvf/docs/SSVF_VA_Data_Guide.pdf))
- _There's a white paper I am unable to locate that found approximately 90% of SSNs in HMIS systems were missing or inaccurate_

**Comment by afeld** [comment]
- [ ] Touch base with Greg and Jarrett

**Comment by afeld** [comment]
[Discussion about ITINs with other teams](https://civicunion.slack.com/archives/C92F939K6/p1648755283441319)

**Comment by srhhnry** [comment]
Research completed and deck available here: https://docs.google.com/presentation/d/1F8buH7_vHQcVUdub_EtJ6KXpw43Xaws0IShG76rrkzQ/edit
