### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#410]
@machikoyasuda, @thekaveman, and I discussed how doing things like including screenshots, specifying what's changed, etc. is helpful to reviewers of PRs. We can make this easier to remember by creating a PR template with these types of items.

Here is the initial list we came up with:
- [ ] Did you start the app locally?
- [ ] Did the database/models/fixtures/PO files change? Run `bin/init.sh` to get new database and translations.
- [ ] Did you add or modify environment variables change? Remember to update `.env.sample` and `.env.test`
- [ ] Add this PR to a milestone.

For PRs that include front-end changes:
- [ ] Include a screenshot of the app / page before and after the PR's changes
- [ ] Include a screenshot of UI tests passing locally

- Prefer rebasing `dev` (rather than merge)

**Comment by thekaveman** [comment]
We have good issue templates, and decided against a PR template for now.
