### ISSUE TITLE
Security: protect against open redirects

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#415]
The `origin` set in `session.py` is used for history and (as of https://github.com/cal-itp/benefits/pull/414) redirection after login.

https://github.com/cal-itp/benefits/blob/c8689c6d9830671837520f6e0e706348923b838b/benefits/core/session.py#L237-L239

Currently, all cases where the `origin` are set are "trusted", but I could imagine a case where we take that path from a query parameter, leaving ourselves vulnerable to an open redirect vulnerability. We should validate the URL/path being passed.

Info about open redirects:

- https://affinity-it-security.com/what-is-an-open-redirect/
- https://dzone.com/articles/what-is-an-open-redirection-vulnerability-and-how
- https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

**Comment by thekaveman** [comment]
A straightforward way to implement this protection might be to move the usage of [Django's `reverse()` helper](https://docs.djangoproject.com/en/3.2/topics/http/urls/#reverse-resolution-of-urls) from the callers of `update()` into the function itself.

That would embed and enforce the assumption that the `origin` is a safe identifier for a known Django application route. A call to `reverse()` with an invalid route name or a random external URL would fail, causing the update to fail.

**Comment by afeld** [comment]
How Django does it:

https://github.com/django/django/blob/13a9cde133ac82e33dd091ca9bb9c677804afbe1/django/contrib/auth/views.py#L74-L84

**Comment by afeld** [comment]
Looked through the app and we don't have any redirects coming from parameters, so not going to worry about this for now.
