### ISSUE TITLE
Security: add tests

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#418]
This might make sense to split up into smaller issues; capturing here (and will continue adding) in the meantime.

- [ ] Check session [cookie security settings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#security)
- [ ] [Open redirects](https://github.com/cal-itp/benefits/issues/415)
- [ ] Accessing pages that require auth, following https://github.com/cal-itp/benefits/issues/371
- [ ] OpenID Connect (OIDC) / OAuth 2.0 token verification

cc https://github.com/cal-itp/benefits/issues/413

**Comment by thekaveman** [comment]
See #226 and #413 too

**Comment by thekaveman** [comment]
Combining this with the list we had started in #413, which is now more built out. Let's keep that one up to date.
