### ISSUE TITLE
Get added to Login.gov partner support channel

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#419]
Want some feedback about [our integration approach](https://docs.google.com/document/d/13EWBeCQtVUIYMnUOKiIsPPN-P83YHbDKjSEJxq292Hc/edit#).

**Comment by afeld** [comment]
Requested via Oren; waiting to be added.

**Comment by thekaveman** [comment]
Closing, we all have access now via a Connected Channel in the Cal-ITP Slack! Thank you @afeld.
