### ISSUE TITLE
Remove all paragraph content from the viewmodel in `core:index`

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#432]
From https://github.com/cal-itp/benefits/issues/366
<img width="832" alt="image" src="https://user-images.githubusercontent.com/3673236/163299119-7b8c7696-05b5-4ade-9bc2-c5b784707a66.png">

**Comment by angela-tran** [comment]
@MattRenda Are you currently working on this, or does it need to be assigned to someone else?

**Comment by angela-tran** [comment]
Talked with @machikoyasuda and @thekaveman, and one of us will pick this up so we can get the change in today.
