### ISSUE TITLE
Design CSS Recommendations

### ISSUE THREAD

**Issue by Jorden1420** [cal-itp/benefits#438]
Just a few recommendations to make styling more consistent.

These changes would optimally be apart of #435

Change H1 to have consistent margin-top and margin-bottom to be same value of either 20px or 30px for consistent repetitive flow.

![image](https://user-images.githubusercontent.com/44067420/163490425-46f89937-62fc-4fe0-91d8-2227fa5878f3.png)

2) remove .container.content h1 ~ p:nth-last-of-type(1) margin-bottom of 2rem; altogether and instead add margin-top to the action button instead so that all paragraphs keep consistent padding.

3) replace all paragraphs in the stylesheet of margin-bottom: 1rem; to padding-bottom:1rem;

4) remove height of 60px on all buttons as it's currently making the text inside of it uneven. In addition, it wouldnt be optimal to add height on buttons if you have more text otherwise it would be truncated.

Screenshot: 
![image](https://user-images.githubusercontent.com/44067420/163492491-2a127b00-aab6-42da-a59c-238af83b67ad.png)

**Comment by machikoyasuda** [comment]
Closed with #450
