### ISSUE TITLE
Fix styles on Help page: button width

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#456]
We got feedback from @srhhnry and @Indiajar in our meeting on 2022-04-15. This ticket is for:
 - Go back button should match Figma mockup (needs to be not so wide)

**Comment by machikoyasuda** [comment]
This issue's fix will/should also fix the current Enrollment page form bug:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3673236/164109404-9cc87dd5-4a21-4631-a0ad-c0ecb69c6da8.png">

**Comment by angela-tran** [comment]
Split out some work from this ticket to #473 so that #463 does close all of this one.
