### ISSUE TITLE
Try simplifying origin setting

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#475]
Currently, we are setting the `origin` in various places to handle redirects after login (and with https://github.com/cal-itp/benefits/pull/436, after logout). I worry that this leaves room for error, we could forget it in some places, etc. Ideas for handling it more robustly:

- Set based on the [referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) to `/login` and `/logout`
- When logged in, automatically set to the current path on every pageview, then let the middleware handle redirecting elsewhere if necessary

May take some trial and error to see what's simplest and most reliable.

**Comment by thekaveman** [comment]
Note that `origin` was around before the auth stuff - it is used elsewhere in the app, e.g. to get users back to where they started if they go to the Help page (or the soon-to-be-defunct Payment Options page)

**Comment by afeld** [comment]
https://github.com/cal-itp/benefits/issues/494 may end up addressing this from another angle.

**Comment by afeld** [comment]
Going to close in favor of that issue.
