### ISSUE TITLE
Create mark/fixture to mock analytics

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#503]
_Originally mentioned in https://github.com/cal-itp/benefits/pull/452#discussion_r859311459_

> Similar to whatever the `@pytest.mark.django_db` is doing to signal that we "need the db" - can we have something like `@pytest.mark.mock_analytics`?

We'd like to mark the test instead of crowding the test body since mocking analytics isn't actually a part of the test logic, but rather is to separate it out as irrelevant to the test.

**Comment by afeld** [comment]
Might be a good use case for [autoused fixtures](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#autouse-fixtures-fixtures-you-don-t-have-to-request).
