### ISSUE TITLE
Write up hosting overview

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#510]
Greg F asked for some information about our hosting environment, current and future needs.

- [x] Create [writeup](https://docs.google.com/document/d/1DXBB3sw8tOtp0jdLDzjEQq-hkUx0DRPyIZU9PfnrztI/edit#)
- [x] Move content to [deployment documentation](https://docs.calitp.org/benefits/deployment/) - https://github.com/cal-itp/benefits/pull/536

**Comment by afeld** [comment]
Made some suggested edits to the [existing architecture docs](https://docs.google.com/document/d/1rwYcp2ps_JNn9WmjqUfYpPeuMoj1FZu5DTUloQEQ5iQ/edit#) — someone mind reviewing when you get a couple minutes?

**Comment by thekaveman** [comment]
@afeld changes look good, accepted them all. Thank you!

**Comment by afeld** [comment]
[Doc](https://docs.google.com/document/d/1DXBB3sw8tOtp0jdLDzjEQq-hkUx0DRPyIZU9PfnrztI/edit#) — confirming with Greg that's what he's looking for.

**Comment by afeld** [comment]
Considering this "done enough"… Will make tweaks as comments come in.
