### ISSUE TITLE
Write up penetration testing agreement

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#521]
"Agreement", "directions", … whatever the right word is. This should describe the scope, exclusions, etc. Resources to pull from:

- [DMV shared assets](https://drive.google.com/drive/folders/11m096_ZpYYa5-cqkJyVVLZvwC_3LjObR?usp=sharing)
- [TTS Bug Bounty policy](https://hackerone.com/tts)

**Comment by afeld** [comment]
[Write-up](https://docs.google.com/document/d/1MDtGR01OkdEi9kOQVNM0dsHfYgvOoEiDqVZ2JHYbNng/edit#) — would love feedback!

**Comment by thekaveman** [comment]
The write up looks great, thank you @afeld!

**Comment by afeld** [comment]
Jarrett sent to John in the CDT CISO's office and Larsen at BugCrowd in advance of the meeting Monday.
