### ISSUE TITLE
convert diagrams to code

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#537]
We have [a number of diagrams in Diagrams.net](https://viewer.diagrams.net/?highlight=0000ff&layers=1&nav=1&title=Eligibility%20Verification%20MVP.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1qzCH5jtCtPhvpKeuPw6vAjYEtUQUNA8-%26export%3Ddownload), and [others in Mermaid in this repository](https://github.com/cal-itp/benefits/search?q=mermaid). Doing more in code would:

- Allow changes to be made through pull requests
- Make it easier to embed in the docs site

[Mermaid](https://mermaid-js.github.io/mermaid/#/) seems like a good choice since we are using it already, though there are a number of [alternatives](https://cal-itp.slack.com/archives/C014FK7ECN5/p1651275353825809).

Negotiable how many we want this issue to encompass… Maybe just one or two major ones, maybe more.

## Tasks

- [x] [Architecture diagram](https://docs.calitp.org/benefits/deployment/infrastructure/#architecture)

**Comment by thekaveman** [comment]
Closing as we have migrated the majority of diagrams into code in the docs site:

* [App infrastructure / architecture](https://docs.calitp.org/benefits/deployment/infrastructure/#architecture)
* [College process](https://docs.calitp.org/benefits/use-cases/college/#process)
* [Courtesy Cards architecture](https://docs.calitp.org/benefits/use-cases/courtesy-cards/#architecture)
* [Seniors process](https://docs.calitp.org/benefits/use-cases/seniors/#process)
