### ISSUE TITLE
Ensure pageviews are being registered on all relevant pages

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#552]
Noticed while poking around the code that [`pageview_decorator()` is only used on a subset of the views](https://github.com/cal-itp/benefits/search?q=pageview_decorator). Is that intentional? Is there a reason we wouldn't want to turn on the middleware for all requests?

**Comment by afeld** [comment]
@thekaveman clarified that this isn't meant to be everywhere, just where other events aren't being fired. May be worth a comment in there with clarification, at least.

**Comment by thekaveman** [comment]
Amplitude is receiving the correct events.
