### ISSUE TITLE
Mobile First Design Brief

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#561]
Draft a design brief that outlines the problem/question how we are going to answer it. 

ie: what does it mean to be mobile first in this context? what user analytics should we track and how often? what breakpoints are we using (the state templates) are they sufficient for our users? as needed- schedule a internal mini-kickoff to talk about mobile.

**Comment by srhhnry** [comment]
Closing this issue as the concern for how we can be more mobile-first is more broadly reflected in the work for #583
