### ISSUE TITLE
User Research Summary

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#562]
Sarah and India have completed four user interviews and a synthesis of those learnings. See [slack convo](https://cal-itp.slack.com/files/U032BKMAHA9/F03E6CZ7B8V/login). 

- [x] schedule internal meeting to [present slides](https://docs.google.com/presentation/d/1O11jiZGa7CtF8v8zLxmCKPcqxuBkINWm2EzY4mTevuU/edit#slide=id.p), discuss feedback
- [ ] create 5 min summary video for sharing with broader stakeholder group and for archival purposes. [example video](https://drive.google.com/file/d/1Ef9BEfjKzd5zPI28hFlqh6EH0K_qs4Km/view).

**Comment by srhhnry** [comment]
video and deck will be posted to Slack on monday morning. Deck also sent to GSA.

**Comment by thekaveman** [comment]
Deck: https://docs.google.com/presentation/d/1O11jiZGa7CtF8v8zLxmCKPcqxuBkINWm2EzY4mTevuU/edit?usp=sharing

Video: https://www.loom.com/share/93bba997ff744d2f9df2c552143d2209
