### ISSUE TITLE
automating sharing of benefits app metrics with MST team

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#563]
- first update existing dashboard labels (since launch of Courtesy Cards)
- reach out to payments/data-infra team to adding viz to MST Tableau.

**Comment by machikoyasuda** [comment]
@o-ram discussed this with @MarikoLochridge and @mrose914 

May be a good idea to integrate this data with the Tableau/Payments data that the MST team already checks.

**Comment by machikoyasuda** [comment]
Currently @o-ram is sending screenshots of Metabase, and you lose a lot of information like tooltips

**Comment by thekaveman** [comment]
See #1183 for possible pre-requisite to this work, to get the latest data from Amplitude to Metabase.

**Comment by o-ram** [comment]
MST is able to get their data into Tableau via direct access to the Cal-ITP internal data (BigQuery) warehouse. 

Currently in discussions with Jameelah about incorporating the Benefits data into the existing workflow for automating the sharing of data with MST.

**Comment by MarikoLochridge** [comment]
@o-ram met with MST and they clarified their request: 
- Payments Ridership Data to be updated in Metabase, once it is updated the MST team will ingest the Metbase data into their Tableau
- Important clarification on earlier understanding of process. They will recreate data viz on their own inside of Tableau. 

RESOURCES: 
Olivia/Mariko Meeting Notes

**Comment by MarikoLochridge** [comment]
Sharing of benefits app metrics is automated with MST Team from Metabase for Payments Ride Data
Next steps is to [Update Benefits Metabase dashboard #1246](https://github.com/cal-itp/benefits/issues/1246)

Amplitude data is not currently being ingested and will be handled in this ticket 
[Use an Amplitude Data Destination for BigQuery #1183](https://github.com/cal-itp/benefits/issues/1183)
