### ISSUE TITLE
Enrollment: Success (signed out): Use the full-screen with no image

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#565]
![image](https://user-images.githubusercontent.com/3673236/167704977-ba0cd831-ae56-488c-b720-cceeaba6707f.png)

Use the fullscreen view instead

**Comment by machikoyasuda** [comment]
This ticket could be paired with this refactor ticket for this same page: https://github.com/cal-itp/benefits/issues/513

**Comment by thekaveman** [comment]
@machikoyasuda I updated the description of #513. Yes still something we want to do (though very minor)
