### ISSUE TITLE
Design/mock for "Service is down" page

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#567]
Create a design for the 500 "Service is Down" and 404 "Page Not Found" pages. The current pages looks like this:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/167744616-1a1c8bb4-600b-4936-b877-89789e417154.png">
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/3673236/167744662-546fab05-512c-4da6-9207-3065de2a7eee.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/3673236/167744730-4fc061a2-113c-4d67-8c2c-aef78e6b1982.png">
<img width="451" alt="image" src="https://user-images.githubusercontent.com/3673236/167744780-fc0cf4bb-0788-453f-abd3-50db093738a8.png">

Both pages have the same design with the broken bus icon, an H1, two paragraphs of text and the `Return home` button.

You can get to the pages by:
- 404: Going to a random URL like https://dev-benefits.calitp.org/asf
- 500: Going to https://dev-benefits.calitp.org/enrollment/ without having first chosen an agency and gone through the flow

**Comment by srhhnry** [comment]
Updated the comps for 404 and 500 error pages on XXL containers. Working on mobile next

![Screen Shot 2022-05-17 at 2 00 18 PM](https://user-images.githubusercontent.com/5394204/168879753-e0243916-8275-45ff-aa07-d3983a50a882.png)

![Screen Shot 2022-05-17 at 2 01 25 PM](https://user-images.githubusercontent.com/5394204/168879813-133c4505-bfd7-4b2f-b82f-4dd10c037f44.png)

**Comment by srhhnry** [comment]
And here we have mobile/small container

![Screen Shot 2022-05-17 at 2 11 30 PM](https://user-images.githubusercontent.com/5394204/168881675-f24d4fac-028e-4140-8505-e3a9bd84cb73.png)

Figma board here: https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Login.gov)?node-id=0%3A1
