### ISSUE TITLE
Meta description is using old msgid

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#597]
### Steps to Reproduce
 - Do something that causes the [meta description](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#active_learning_the_descriptions_use_in_search_engines) to be rendered (e.g. post a link to our app in Slack)

### Expected Result
A human-readable description is displayed.

### Actual Result
A msgid is shown.

![image](https://user-images.githubusercontent.com/25497886/169138519-183cb64b-4adb-428d-a3fd-16239afbc73b.png)

**Comment by machikoyasuda** [comment]
Great catch! Changing `core.pages.help.p[0]` to `core.pages.help.about.p[0]` should fix.
