### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#604]
* [x] User Story - does not get closed until code is live
* [x] Bug Report - something is broken
* [x] Task - a unit of work for a developer, will end as a PR
* [x] Deliverable - a unit of work that ends with a non-code deliverable
  * [x] Add a label for `deliverable`
* [x] Epic/ADR - larger set of User Stories and Tasks, background info, reasons we are implementing the way we are

**Comment by machikoyasuda** [comment]
https://github.com/usds/justice40-tool/tree/main/.github/ISSUE_TEMPLATE
