### ISSUE TITLE
Redesign Screens

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#609]
_Mini-Design Kickoff Schedule for 2022.05.25_

**Depends on hosting decision.** 

Kickoff Agenda:
- What screen or container sizes are we designing for? How many total? In what priority?
- How closely should we adhere to the new [State of CA Design System](https://designsystem.webstandards.ca.gov/)? ie: specified fonts
- What are our design deliverables, ie: what "paths" and screens are needed?
- What is the "flow", specifically regarding login.gov and hosting decisions?

Related / depends on: #583

**Comment by srhhnry** [comment]
I took a look at USWDS and they're using a system that doesn't make a ton of sense to me. For more detail here's the direct page: https://designsystem.digital.gov/utilities/layout-grid/

They use a grid, are mobile first, and are based on 12 columns (which, if I recall, is Bootstrap-y).

HOWEVER, the breakpoints they use for responsive seem crazy:
- 0px
- 480px
- 640px
- 1024px

480 isn't useful for the smallest contemporary phones and 1024 is very, very small for a desktop device. Most desktop sized devices are closer to 1366 or 1440.  

I'm still diving into how resolution corresponds to designing screens, but so far I don't think I'd recommend USWDS screen sizes.

**Comment by machikoyasuda** [comment]
https://github.com/uswds/uswds/blob/1db0e68d7e5cf21ae52f2d8a29d5963c7aa1b681/packages/uswds-core/src/styles/settings/_settings-utilities.scss#L31

### USDWS's breakpoints:
```scss
$theme-utility-breakpoints: (
  // 160px:
  "card": false,
  // 240px:
  "card-lg": false,
  // 320px:
  "mobile": false,
  // 480px:
  "mobile-lg": true,
  // 640px:
  "tablet": true,
  // 880px:
  "tablet-lg": false,
  // 1024px:
  "desktop": true,
  // 1200px:
  "desktop-lg": false,
  // 1400px:
  "widescreen": false
) !default;
```

### Bootstrap 4.0 / CA Digital Web Standards:

```css
// Extra small devices (portrait phones, less than 576px)
// No media query for `xs` since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```


### Our app

Our main breakpoints in the app now:

```
- 320px (Only used for 2 style declarations, so basically, not that much)
- 768px (Used 2nd most)
- 992px (Used most)
- 1200px (Used for 2 style declarations)
```

The only difference between ours and Bootstrap/CA DWS is that we have an added extra small (320px) width. Partially that's a bias I have. I use a iPhone SE (2nd gen) and the width of that is 375px.

**Comment by srhhnry** [comment]
Thank you @machikoyasuda! I didn't realize their theme breakpoints were different (should have kept reading down the page).

So based on USWDS, I've bolded the screen sizes I _think_ the design team should create on a regular, ongoing basis. However, I am not entirely sure about tablet sizes yet, as they are sooo soo variable (there are a ton of devices out there). And 1024 is now considered a tablet size by some. 
  **'mobile':          // 320px**
  'mobile-lg':      // 480px
  **'tablet':            // 640px**
  'tablet-lg':        // 880px
  'desktop':         // 1024px
  **'desktop-lg':     // 1200px**
  'widescreen':    // 1400px

Regarding how our current system works, @machikoyasuda what do you mean by 768 and 992 used most and second most? Also, I'm fine using 768px in place of 640px if that's more in line with your current process.

**Comment by machikoyasuda** [comment]
@srhhnry The 3 numbers you bolded sounds good!

By most "used", I am referring to how many times we have to write code specific for that breakpoint.

**Comment by srhhnry** [comment]
Hooray! So I'll plan on 3 "screen" sizes for design from here on out, and we'll do ad-hoc page by page design for other breakpoints if testing them shows anything off. I still think we need a bit more research on priority for our users specifically, but I can see a general order of priority being: 320/mobile then 1200/desktop then 640/tablet.
