### ISSUE TITLE
Spanish: Translate new copy and upload translations for Courtesy Cards

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#611]
Current status `09/26/22`

Copy document: https://docs.google.com/document/d/11s3oFXwpRykFoRSpOeQ3MBLLIq2CXQjI/edit

----

What else is missing from that doc that needs to be translated:

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/3673236/189770427-631f50b7-45c0-4701-90ca-4e76c8b95ece.png">

**Comment by thekaveman** [comment]
Closing for more specific tasks when we have copy etc.

**Comment by thekaveman** [comment]
Keeping as a placeholder.

**Comment by machikoyasuda** [comment]
Linking this ticket here: https://github.com/cal-itp/benefits/issues/206

Copy for Courtesy Cards feature has already been translated into Spanish by MST as of April 4 2022: https://github.com/cal-itp/benefits/issues/206#issuecomment-1087992783

https://docs.google.com/document/d/1uzGaFF73CKoC7nftYhQ5329obHcz9SJj/edit
