### ISSUE TITLE
Update customer service documentation for Courtesy Cards

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#616]
[MST customer service documentation](https://docs.google.com/document/d/1RFQMY0KOdjn0P6Cqd_4Dv2redzCmKLT3Ww8ADfcBmYQ/edit#)

## Acceptance Criteria

- [ ] One or more Google docs with customer service oriented information for the Courtesy Cards verification feature in Benefits
- [ ] Updated screenshots of the flow
- [ ] Updated instructions of the flow
- [ ] Updated FAQs

## What is the definition of done?

The doc(s) are finalized and handed-off to the MST Customer Service team.

**Comment by machikoyasuda** [comment]
https://docs.google.com/document/d/11s3oFXwpRykFoRSpOeQ3MBLLIq2CXQjI/edit

**Comment by o-ram** [comment]
I'm going to close this issue - customer service docs have been [updated](https://docs.google.com/document/d/1RFQMY0KOdjn0P6Cqd_4Dv2redzCmKLT3Ww8ADfcBmYQ/edit?usp=share_link) for Courtesy Cards and MST has both a word doc version and the updated version in Zavanta, their internal document system.
