### ISSUE TITLE
Use production Login.gov

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#621]
## Acceptance Criteria

- [x] On the production site, when a user clicks the sign in button, they get directed to https://secure.login.gov.

## Additional context

There is currently only a development authorization server, which uses the Login.gov sandbox for authentication.

## What is the definition of done?

- [x] CDT gets contract signed
- [x] Production configuration for authorization server is complete with Login.gov
- [x] Production authorization server available
  - [x] Production Benefits app configured to point to it

**Comment by thekaveman** [comment]
This is complete on https://benefits.calitp.org.

Leaving open until the rest of cal-itp/benefits-secrets#13 is complete, as we may need to swap back and forth for other testing.

**Comment by thekaveman** [comment]
We did it!
