### ISSUE TITLE
Docker Compose requires local .env file to start app/devcontainer

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#626]
For brand new clones (or when you do not have a local `.env` file), the [Getting Started](https://docs.calitp.org/benefits/getting-started/) guide is now broken and the app cannot be started locally.

## To Reproduce

1. Delete your local `.env` file or clone the repo into a new directory
2. Follow the [Getting Started](https://docs.calitp.org/benefits/getting-started/) guide, and do not create an `.env` file
3. `docker compose build client`
4. See error: `open /local/path/to/.devcontainer/.env: The system cannot find the file specified.`

## Expected behavior

Running a fresh clone locally should Just Work ™️ 

## Additional context

Things changed in #598 to remove the `.env.sample` and update guidance that overriding the environment is only necessary for additional features and deployments.

**Comment by thekaveman** [comment]
Somehow we keep running into these _hot button issues_ of the day! This is actively being discussed in both the Docker Compose repo and the Compose file spec repo:

* docker/compose#3560
* docker/compose#9181
* compose-spec/compose-spec#240

The TLDR that I can surmise is: this is a widely requested feature, but of course has implications and seems to rub some folks the wrong way. Guidance is essentially:

1. `touch .env` right away before any `docker compose` commands, to create an empty file; or
2. use gitignore magic to commit an empty file in the repo and then subsequently ignore any changes to it

**Comment by afeld** [comment]
Option 1 sounds good to me!
