### ISSUE TITLE
Get traffic logs to appear for Azure apps

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#631]
User story: _As a developer on the Benefits app, I need to see logs appear for the Benefits app to help with troubleshooting._

## To Reproduce

There are various places to see (and various ways to configure?) logs in Azure. Click into each of the following:

- [Log Analytics workspaces](https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.OperationalInsights%2Fworkspaces)
- [Log stream](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourceGroups/RG-CDT-PUB-VIP-CALITP-D-001/providers/Microsoft.Web/sites/AS-CDT-CALITP-D-001/logStream)
- [(Diagnostic?) logs](https://portal.azure.com/#@digitalca.onmicrosoft.com/resource/subscriptions/9bdb8e29-156f-4fc9-a1fe-1bb6a915a4f0/resourceGroups/RG-CDT-PUB-VIP-CALITP-D-001/providers/Microsoft.Web/sites/AS-CDT-CALITP-D-001/analytics)

All seem to be empty, or at least not showing as much as I would expect.

## Expected behavior

I expect to see logs similar to what appears locally when running the server, e.g.

```
[01/Jun/2022 00:07:43] INFO django.server:161 "GET /abc HTTP/1.1" 200 9414
```

## Additional context

- Possible there are Azure permissions issues at play here.
- One solution may be to send application logs the same way we send errors for https://github.com/cal-itp/benefits/issues/448: [through OpenCensus to Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python)

**Comment by thekaveman** [comment]
I don't have permissions to run this command. Sent to @cal-itp/cdt-devsecops team to see if they can run it.
