### ISSUE TITLE
Front-end: Mobile - Set all buttons to be 250x72

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#632]
Buttons on the app should have a set size of 250 x 72.

## Acceptance Criteria

All buttons on app should be set to 250 x 72 px size for mobile.

- [x] Audit that this sizing will work on all buttons across the site
- [x] Make the size happen
- Check what this looks like on mobile at various widths on the enrollment page _with_ the recaptcha square.

## Additional context

From Figma:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/3673236/171477916-ad06c430-a8ec-4545-8407-1b83196b6a0b.png">
https://www.figma.com/file/5IabSdY0xDzwL4gyXhbQ9G/Benefits-(Login.gov)?node-id=3830%3A9841#201683899

**Comment by srhhnry** [comment]
Hmm. Is this on desktop? I have to dig into this more, but the 72 height was intended for mobile. I'm not sure we want to adjust button size on desktop-sized screens (1200+). They've also all passed user testing. I'll verify desktop button size tomorrow and get back to you on that though.

**Comment by srhhnry** [comment]
Just to verify--yes, the 72px height is for mobile only. On desktop we can have smaller buttons as they are still easy enough to select with a mouse and generally have a bit of white space/padding around them. The action buttons are 60px high and the Login.gov button is 40px high on the Get Started page. I do want to redesign the text links on the Get Started page, as these are too cramped together--but that's another issue.
