### ISSUE TITLE
Restrict egress

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#637]
[General information.](https://en.wikipedia.org/wiki/Egress_filtering)

## Acceptance Criteria

- [ ] A request from the application to a non-allowed hostname fails

## Additional context

Relevant Azure resources:

- https://docs.microsoft.com/en-us/azure/app-service/environment/firewall-integration
- https://docs.microsoft.com/en-us/azure/firewall/fqdn-filtering-network-rules

**Comment by angela-tran** [comment]
This feels shaped enough, just not sure if we need to do it soon

**Comment by thekaveman** [comment]
This isn't something we're looking to implement right now.
