### ISSUE TITLE
Ensure relevant analytics events are fired for Login.gov IAL2 flow

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#644]
Design to collaborate with Dev to ensure the behaviors they are interested in understanding are defined in Amplitude. 

- [x] `cancel_sign_in`

**Comment by angela-tran** [comment]
@srhhnry or @indiajar --

The Benefits code is currently set up to send these auth-related analytics events[^1]:
 - **"started sign in"** - the user clicks "Get Started with Login.gov"
 - **"finished sign in"** - the user signed in successfully
 - **"clicked link"** - the user clicks an anchor link URL
 - **"canceled sign in"** - the user cancels out of either the initial Login.gov screen or the identity proofing part
 - **"started sign out"** - the user clicks "Sign out of Login.gov"
 - **"finished sign out"** - the user signed out successfully

Is there anything missing from this list? Any other drop-off points we'd be interested in?

[^1]: Code changes for all these were done in #488, #452, and #755.

**Comment by srhhnry** [comment]
Sorry for the delay! This issue became an open tab in a forest of open tabs. 

This list looks great. I would also be interested in drop off at "Connect your Card" and any instance where the user clicks Help. Those are probably included in the anchor link analytics, but calling them out specifically would be helpful.
