### ISSUE TITLE
Update customer service documentation for Login.gov IAL2

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#645]
Documents for Customer Service team need to be updated to remove references to the CA DMV, and instead reference Login.gov id-proofed accounts for age verification with helpful links to the login.gov pages. 

- [x] Remove DMV from Customer Service Docs
- [x] Add Information for Login.gov account creation of "proofed" accounts
- [x] Add information for Login.gov age verification
- [x] Update Benefits Incident Management Plan to include appropriate contact information for CDT D-ID and Login.gov
- [x] Update service model chart
  - [x] swap DMV for Login.gov
  - [x] add Cal-ITP branding (logo)
  - [ ] use to schedule a discussion/ mortem on a recent issue (for example 3G) and discuss how we might (a) track issues in a single interface such as teamwork (b) where we might consider adding additional logging. 

Resources:
- [Customer Service Docs for Cal-ITP Benefits (living document)](https://docs.google.com/document/d/1RFQMY0KOdjn0P6Cqd_4Dv2redzCmKLT3Ww8ADfcBmYQ/edit)
- [Cal-ITP Benefits Incident Management](https://docs.google.com/document/d/1qtev8qItPiTB4Tp9FQ87XsLtWZ4HlNXqoe9vF2VuGcY/edit#heading=h.enrx9qtt9lka)
- [MST Phase 1 Demo Service Model](https://app.diagrams.net/#G1ACSlko56UvROCiswylA7-15S5w-hi3we)

**Comment by vykster** [comment]
@o-ram to review and resolve comments.

**Comment by afeld** [comment]
@o-ram @esquared415 Per @thekaveman, the Incident Management Plan and Service Model diagram were created per the DMV's request. Given they aren't involved anymore (for now), should I still update them, or just mark as deprecated? Is / should that information be captured anywhere else?

**Comment by esquared415** [comment]
@afeld I didn't work on this doc, so I'm not able to advise. Sorry about that!

**Comment by o-ram** [comment]
hm, I also did not work on this @afeld (at least I don't recall doing so, but maybe I did!) so I don't have a strong opinion either way. I'd imagine this may be a handy resource to have though, so leaning towards we should update it? Even if just because the DMV is planned to get back involved and we can say we still have this and it's current.

**Comment by vykster** [comment]
Adding to sprint planning for 9/6.

**Comment by afeld** [comment]
Updated the [Incident Management Plan](https://docs.google.com/document/d/1qtev8qItPiTB4Tp9FQ87XsLtWZ4HlNXqoe9vF2VuGcY/edit#heading=h.enrx9qtt9lka) and [Service Model](https://app.diagrams.net/#G1ACSlko56UvROCiswylA7-15S5w-hi3we). The former I did as suggested edits; who should resolve?

**Comment by afeld** [comment]
> schedule a discussion/ mortem on a recent issue

@vykster Ok with saving this for https://github.com/cal-itp/benefits/issues/905?

**Comment by machikoyasuda** [comment]
@vykster @afeld Is this issue done? Can someone close it? It's the last issue remaining in the Login.gov IAL2 Milestone

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/3673236/199624616-79a01c39-6a77-43d4-a96e-00d44f8be43c.png">

**Comment by vykster** [comment]
yep, sounds great. Closing out issue.
