### ISSUE TITLE
Fix pytest runs in GH Actions

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#648]
`pytest` is currently failing in GH Actions on `dev` (and elsewhere):

* Last know good run on `dev`: https://github.com/cal-itp/benefits/actions/runs/2418089818
* Most recent run (failure) on `dev`: https://github.com/cal-itp/benefits/actions/runs/2449795228

## To Reproduce

Push new commits to a PR/branch to trigger `pytest`, see:

* #647 and the check run: https://github.com/cal-itp/benefits/runs/6763507049?check_suite_focus=true
* #638 and a recent check from from a rebase/push: https://github.com/cal-itp/benefits/runs/6762605601?check_suite_focus=true

## Expected behavior

These tests should pass in CI, especially as nothing is changing with Python code or the Python testing environment/dependencies.

## Additional context

Tests are passing locally in the devcontainer for @thekaveman and @angela-tran

**Comment by thekaveman** [comment]
On the last run that worked on `dev`:

* [Resolved to use Commit `01b35d9`](https://github.com/cal-itp/benefits/runs/6679612653?check_suite_focus=true#step:5:11) from `eligibility-api`
* [Commit `01b35d9`](https://github.com/cal-itp/eligibility-api/commit/e27a2160)

On the first run that failed on `dev`:

* [Resolved to use Commit `404697e`](https://github.com/cal-itp/benefits/runs/6762724922?check_suite_focus=true#step:5:11) from `eligibility-api`
* [Commit `404697e`](https://github.com/cal-itp/eligibility-api/commit/404697e)

The [diff between them](https://github.com/cal-itp/eligibility-api/compare/01b35d9...404697e) gives no indication that this would have anything to do with the failure here.

**Comment by angela-tran** [comment]
### Confusion
It's very mysterious to me why this started failing. We have definitely been able to import `test.pytests.conftest` and run/pass the tests in GitHub Actions before (see [#551](https://github.com/cal-itp/benefits/pull/551/files#diff-f8ccc2fda1961589005f584e16af44101a4e7fa344ab0bcf5e73ba9c3a131451R5) as an example -- notice the [directory structure/presence of `__init__.py` files](https://github.com/cal-itp/benefits/tree/ceff8bc87b9769e63af86acef8fd0a98fc227f38/tests/pytest) is not any different from [what we have now at `9fe9faef`](https://github.com/cal-itp/benefits/tree/9fe9faef0dd2c77381a5212e14146d1aebd29231/tests/pytest).)

### Workaround
As a way of just getting it to work again, we could pass `--import-mode=importlib` when issuing the `pytest` command. 
I observed in my fork that this works: https://github.com/angela-tran/benefits/actions/runs/2450796821 (corresponding commit: https://github.com/angela-tran/benefits/commit/21278a061f89eada80804a8ab555b12bce8fee23)

Just to document: prior to that, another workaround I tried was adding an `__init__.py` file to `tests/pytests`, and it did not work: https://github.com/angela-tran/benefits/actions/runs/2450710304.

`--import-mode=importlib` is a newer import mechanism in pytest that avoids modifying `sys.path` and `sys.modules` -- read more in the [pytest docs](https://docs.pytest.org/en/6.2.x/pythonpath.html#import-modes).

### Other notes
The Pytest docs on "Import modes" mentions:
> We intend to make `importlib` the default in future releases.

Another section of the docs, [Good Integration Practices > Choosing a test layout](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#choosing-a-test-layout-import-rules), notes how different test layouts affect how modules are imported and that `--import-mode=importlib` avoids many of the drawbacks from other import modes:
> The --import-mode=importlib option (see [Import modes](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#import-modes)) does not have any of the drawbacks above because sys.path is not changed when importing test modules

**Comment by angela-tran** [comment]
I found a GitHub issue documenting a very similar problem (maybe?): https://github.com/pytest-dev/pytest/issues/7408

**Comment by angela-tran** [comment]
I just noticed the Python versions were different between the last known successful run and most recent failure. Oh well. Not going to spend any more time on this 😑 

```
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
django: settings: benefits.settings (from ini)
rootdir: /home/runner/work/benefits/benefits, configfile: pyproject.toml
plugins: django-4.5.2, cov-3.0.0, socket-0.5.1, mock-3.7.0
collected 84 items
```

vs.

```
============================= test session starts ==============================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
django: settings: benefits.settings (from ini)
rootdir: /home/runner/work/benefits/benefits, configfile: pyproject.toml
plugins: mock-3.7.0, django-4.5.2, socket-0.5.1, cov-3.0.0
collected 64 items / 3 errors
```
