### ISSUE TITLE
Engineering: Front-end / Mobile - Redesign the Enrollment, Enrollment Success, Eligibility pages to a no-image / single-column design.

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#655]
- Redesign the Enrollment, Enrollment Success, Eligibility pages to a no-image / single-column design
- Make sure to check the design with and without the Sign out button. 
- For Desktop, no changes are necessary.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/3673236/172735631-3f158904-212b-4c95-8143-408cea7ef832.png">

**Comment by thekaveman** [comment]
Closed by #685
