### ISSUE TITLE
Joint user testing session of the IAL2 flow with Login.gov planning

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#658]
Loosely, the testing session could be conducted in July, post-launch, on a live site. Facilitation and test plan duties could be split between the two orgs.

**Comment by srhhnry** [comment]
Early rough draft here: https://docs.google.com/document/d/1pV4qHbZ3CABBTZ7OGIIiSQLE_BInyvRl9hxJ2JqLtfs/edit?usp=sharing

**Comment by srhhnry** [comment]
Questions from Login team:

Questions:

1. Do we need a translator for the bilingual tests?
2. Do you have a sense of how much prep the users have? For IdV, users will need to be able to take a photo of their state-issued ID (with a mobile phone or have them preloaded on their computer) and have their SSN (not the card, just the number) ready. It would also be helpful to know the kinds of devices folks will be using for the test (desktop, mobile, tablet, etc.) It would be really helpful to know if any of the tests are taking place in a public setting like a library. We need to think about if/how that might limit the user's ability to complete the test from a privacy/security perspective.
3. In the event that a user fails, we might need to determine what the next course of action is. If they fail, we will have a few things scripted for possible failures on our end. With a failure a user cannot proceed in the flow and get to the next step of adding their bank card. For example, if the image upload fails or any of their credential checks fail, they have to wait 6 hours to try again. Would we want to reschedule them, or count it as a failure?

**Comment by srhhnry** [comment]
Meeting with Login team on 7/21

**Comment by srhhnry** [comment]
@vykster what's out budget for user testing? We're thinking we'll need between $500 and $600 dollars in compensation ($50 per participant). The Login team is up for taking on some of that budget but they'll need a longer lead time, so info from our side is useful in helping them figure out budget.

**Comment by vykster** [comment]
It's the same process as usual, write up a user testing plan and share with
Jeremy for approval. You can go ahead and share a partially completed one
now -- to speed up the approval process, focus on the summary info. I
believe there are still sufficient funds in the budget for a test of that
size.

**Comment by srhhnry** [comment]
Rad, thanks. @vykster second question: Are we able to use otter.ai or grain for user testing transcription? What I mean there is are there any privacy or security concerns to be aware of?

**Comment by vykster** [comment]
we don't currently have a process or formal budget for this, if you'll get
a cost estimate for me and put together a bit of process, ie: how to notify
users, ie: during the initial recording consent you can also mention the
transcript and who can/will have access to the transcript. I'll take those
items to the PMO for approval.

**Comment by srhhnry** [comment]
Closing out this extended planning stage and opening a ticket for testing (which will include prep)
