### ISSUE TITLE
Engineering/Design: Need to get a much higher res version of the contactless pay photo @machikoyasuda

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#674]
We need a larger version of the transit pay photo photoshopped and cropped. The current photo dimensions are not wide enough for the new one-column design: https://dev-benefits.calitp.org/static/img/ridertappingbank

Here is the original photo file, without any cropping or the Tap to ride photoshopped out. 

![Photo Mar 01, 3 21 12 PM](https://user-images.githubusercontent.com/3673236/173408103-a6c6ea44-e95a-4285-adbd-55a88a164c87.jpg)

What we'll need is:
- Photo to be cropped and resized to at least ~1400ish pixels wide
- The `Tap to ride` to be photoshopped out

**Comment by srhhnry** [comment]
Does anyone know where the original photo came from? As in who or what group provided the asset? I'm curious if there's another file aside from a jpg.

**Comment by machikoyasuda** [comment]
@srhhnry I shared the Google Drive folders with you. It looks like there's only JPG

**Comment by srhhnry** [comment]
- [ ] Create screens without Tap to Ride text
- [ ] Create a basic vertical crop (leave the sides)
- [ ] Create an ideal crop (left side is cropped more closely)

**Comment by srhhnry** [comment]
PNG and JPG of full size image without text

![Image](https://user-images.githubusercontent.com/5394204/173463376-171b2b48-01e4-4b7a-a56b-c78d523e8f47.jpeg)
![Image](https://user-images.githubusercontent.com/5394204/173463377-02f9e020-1e97-4c5f-b6b1-15151d56160e.jpg)

**Comment by machikoyasuda** [comment]
@srhhnry thank you for these! i saved them to Google Drive so we have these blank card photos for the future.

**Comment by srhhnry** [comment]
I added more cropped photos to the folder: https://drive.google.com/drive/folders/1a94hVd_MzFVZgruK2jG0_6eQ_vcIxT_n
