### ISSUE TITLE
Write product release notes for IAL2 release

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#702]
- [Past release notes](https://github.com/cal-itp/benefits/releases)
- [Automatically generating them](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

## Acceptance Criteria

- [ ] Create GIF of success path

**Comment by afeld** [comment]
Started a [draft release](https://github.com/cal-itp/benefits/releases/tag/untagged-d0a5e38a53c7557d70b4), adapting the copy from the recent [status update](https://calitp.teamwork.com/#/messages/100128). @vykster Thoughts?

**Comment by afeld** [comment]
> Is this a full success path through Login.gov?

Yeah, I think showing signing up for a new Login.gov account would be good, since that's presumably what most users will experience.

**Comment by afeld** [comment]
In case you weren't aware, [GMail supports adding suffixes to your email address](https://support.google.com/a/users/answer/9308648), which _should_ be usable for creating distinct accounts in Login.gov.

**Comment by vykster** [comment]
@afeld I can't open the draft release notes link, I'm getting a 404 error.

**Comment by afeld** [comment]
Oops, fixed link above.

**Comment by vykster** [comment]
looks great!

**Comment by afeld** [comment]
Closing; we'll drop in the GIF as part of https://github.com/cal-itp/benefits/issues/754.
