### ISSUE TITLE
Switch (back) to static OAuth client config

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#707]
In https://github.com/cal-itp/benefits/pull/698, we switched from having the `scope` specified under `AUTHLIB_OAUTH_CLIENTS` in settings to specifying it in the client after creation. I worry this could lead to some subtle bug, where Authlib is doing something special with the scope on client initialization.

An approach that would be more in line with Authlib's recommended setup would be to specify multiple clients in settings: one for each (verifier) use case, I guess? That would be something like `ial1` and `ial2_age`.

## Acceptance Criteria

- [ ] `scope` is specified in settings, rather than at runtime

**Comment by thekaveman** [comment]
Update: this is getting kind of weird... splitting up some of the OAuth config in fixtures, some in env variables, and some hardcoded in settings.

New idea is to move our scope to the fixture/model (and not hardcode in settings), register the client using the fields from the fixture (model). This is a supported [Authlib configuration](https://docs.authlib.org/en/latest/client/django.html#configuration):

> Authlib Django OAuth registry can load the configuration from your Django application settings automatically. Every key value pair can be omitted.

Further down in the [OpenID Connect config](https://docs.authlib.org/en/latest/client/django.html#django-openid-connect-client) they have this example code:

```python
oauth.register(
    'google',
    ...
    server_metadata_url='https://accounts.google.com/.well-known/openid-configuration',
    client_kwargs={'scope': 'openid profile email'}
)
```

So any of these values can be _either_ hardcoded in settings (/ read from environment) OR passed in at registration time. The key is Authlib will merge the two at registration time for matching client names.

Definitely will clean up the weird [overriding of `client_kwargs` we are doing](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/client.py#L34).
