### ISSUE TITLE
Helper text for login.gov account creation and forgot password

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#720]
_Team is adding to next round of user testing_

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/175094984-caf4509e-4fd1-4438-b901-3707189ad22e.png)



![Image](https://user-images.githubusercontent.com/5394204/175095001-881b45ca-e439-4f19-91de-aa36bfdad20d.png)



![Image](https://user-images.githubusercontent.com/5394204/175095014-4df29f7f-23d4-4a16-9e30-f4ae1dfa5307.png)

**Comment by srhhnry** [comment]
User research found this additional context wasn't necessary
