### ISSUE TITLE
Set up external request tracking

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#729]
In order to better understand availability/failures between components connected to Benefits, [dependency tracking](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python-dependency) would be useful for understanding where failures occur.

## Acceptance Criteria

- [ ] The various components of the system (e.g. Benefits and the Eligibility Server) appear on the [Application Map](https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-map?tabs=net)

## Definition of done

- [ ] Dependency data being sent to Azure

**Comment by thekaveman** [comment]
Deprioritizing for now.
