### ISSUE TITLE
CSS Refactor: Refactor H1, H2, H3, H4, <a>, button styles

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#751]
A clear and concise description of the task.

## Acceptance Criteria

- [ ] Go through Figma designs in Zeplin and decide what text should be what `<h>` element
- [ ] Write CSS styles in style.css to match the styles as defined in Figma and Zeplin
- [ ] Figure out how to correctly style the `<h>` styles in terms of sizing the `font size`, `letter-spacing`, `line-height` (rems/ems/px)
- [ ] Style the `<h>` styles with responsive media-query styles as well
- [ ] Make sure each page has 1 <h1>
- [ ] Settle differences between California State Template and our design in H style sizing
- [ ] Buttons: Remove border radius from all buttons
- [ ] Links: Underlined all the time; purple on Visited

**Comment by machikoyasuda** [comment]
related to #778

**Comment by machikoyasuda** [comment]
- [ ] Use CSS variables for colors and use those same CSS variable color names on Figma and Zeplin

**Comment by srhhnry** [comment]
I'm about 80% finished with updating all the type in Figma and pairing down excessive styling. Still investigating REMs and how they relate to our current design choices. Also still puzzling out the desktop headers. Final tasks are to ensure all heights and widths are consistent across boards.

Let me know if anyone needs a primer on how to find and use type styles on Figma

More info here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=2%3A11

![Image](https://user-images.githubusercontent.com/5394204/178588131-83a80608-ee7a-4429-86f0-bac3a2af059b.png)

**Comment by machikoyasuda** [comment]
Thank you @srhhnry - this looks great.

**Comment by srhhnry** [comment]
![image](https://user-images.githubusercontent.com/5394204/178595367-6d5e19a3-05cb-4257-84de-83c119b3e798.png)


Digging into REMs!

**Comment by machikoyasuda** [comment]
Closed - Duplicate to #968 #970
