### ISSUE TITLE
Meet Login.gov security requirements

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#752]
[**Draft**](https://docs.google.com/document/d/1qnRG-GhTNM-6hnv0157PU9E_t-uJMP5uEopxPgEP-kE/edit#heading=h.gdx6dheiu0i3)

Prerequisite for https://github.com/cal-itp/benefits/issues/621.

## Acceptance Criteria

[Per Login.gov](https://cal-itp.slack.com/archives/CG64NU5C7/p1656358796423899?thread_ts=1656353709.300479&amp;cid=CG64NU5C7), they need attestation that:

- [x] We have a set of security standards in place
- [x] We followed/implemented those standards for the system
- [x] https://github.com/cal-itp/benefits/issues/856

**Comment by afeld** [comment]
[Draft attestation](https://docs.google.com/document/d/1qnRG-GhTNM-6hnv0157PU9E_t-uJMP5uEopxPgEP-kE/edit#heading=h.u59my3prfozc) sent to CDT CISO; waiting on response from them.

**Comment by afeld** [comment]
We have narrowed scope to just doing attestation for the auth server, _not_ Benefits. Created a [new draft attestation](https://docs.google.com/document/d/1qnRG-GhTNM-6hnv0157PU9E_t-uJMP5uEopxPgEP-kE/edit#heading=h.u59my3prfozc).

**Comment by thekaveman** [comment]
@jarrettkrumrei sent ATO from CDT CISO to Login.gov yesterday Aug 10, 2022

**Comment by afeld** [comment]
From @orenyk at Login.gov:

> it looks great from our end (and we may borrow the structure for future state and local partners)

🎉 🚀
