### ISSUE TITLE
Create GIF of Success path

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#754]
@vykster To confirm, you prefer a GIF to a video with audio talking people through it?

@srhhnry Is that something you'd be interested in making, or want me to? I'm on a Mac so would do a [recording in Quicktime](https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac) and then convert, but recording in Zoom or Loom or something else would also work.

_Originally posted by @afeld in https://github.com/cal-itp/benefits/issues/702#issuecomment-1167498256_

**Comment by afeld** [comment]
[Test data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit)

**Comment by srhhnry** [comment]
Mobile prototype here: https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=4551%3A4180&scaling=scale-down&page-id=4551%3A4111&starting-point-node-id=4551%3A4180

Making a video/gif of clickthrough next

**Comment by srhhnry** [comment]
Video w/ audio is here: https://www.loom.com/share/81e3d64636b84115aa28ed75cc40c7d1

**Comment by srhhnry** [comment]
![▶_Mobile_Demo_-_Benefits_with_Login_gov_-_30_June_2022__1__AdobeExpress](https://user-images.githubusercontent.com/5394204/176773895-f17868a6-20d2-459d-a424-847061755156.gif)


And I'm less certain about this GIF, but let's see if it works

**Comment by srhhnry** [comment]
The size did seem a little small! That was what Adobe express spit out, and it seems not great. Happy to take another crack at it, with a shortened flow. Any tips on non-ant-sized GIF factories?

**Comment by afeld** [comment]
[The Adobe Express page](https://www.adobe.com/express/feature/video/convert/video-to-gif) suggests you can "Choose the size of your GIF" — did you see that option? Alternatives I'm aware of:

- [CloudConvert](https://cloudconvert.com/mov-to-gif)
- [gifify](https://github.com/jclem/gifify/) (happy to do this for you, if helpful)

**Comment by srhhnry** [comment]
I did not, but will revisit today with a shorter flow

**Comment by srhhnry** [comment]
Hmm, so this is largest file size, which I might have done already now that I'm looking at the interface:

![Screen_Recording_2022-07-05_at_3_28_45_PM_AdobeExpress](https://user-images.githubusercontent.com/5394204/177402990-a1fc07ed-491e-4a88-9773-4ab4b96bf00c.gif)

**Comment by afeld** [comment]
@vykster What do you think? My gut tells me we should make it _much_ more abbreviated, like under ten frames. That would help with the file size too.

**Comment by vykster** [comment]
Can we have one of both? I think we'll definitely want a version that's
super easy to share.

**Comment by srhhnry** [comment]
Here's a much shorter version--down to 15 screens and 1080p

https://drive.google.com/file/d/1KVznH8AhZ-hym0cTSgeu2Qs1PfNZw14L/view?usp=sharing

**Comment by srhhnry** [comment]
@afeld I think I will need your help for getting this to a different state

**Comment by srhhnry** [comment]
Need to replace GIF here: https://docs.google.com/presentation/d/1Vawi8d70jtKfL-u5lwM05CcDyQ5zB764/edit#slide=id.gcd07a00814_0_16

**Comment by srhhnry** [comment]
Do any of these need to be redone? Thoughts?

**Comment by afeld** [comment]
I think we want to try creating a GIF from images (the screens in the prototype) with delays between each rather than from video frames, which will give us more control over what's shown and make the file size much smaller. Some options:

- https://www.nytimes.com/2022/01/12/technology/personaltech/how-to-make-gifs.html
- https://imgflip.com/gif-maker
- https://www.adobe.com/creativecloud/photography/discover/animated-gif.html
- https://motionplugin.com/
- https://gifmock.com/

**Comment by afeld** [comment]
Unless using one that integrates with Figma, the steps will be:

1. Export (some of?) the screens from the prototype as images
2. Throw them into one of the programs above
3. Tweak settings:
   - Frame delay
   - Looping
   - Dimensions — this will affect the GIF file size
4. Generate

**Comment by afeld** [comment]
Created!

![success flow GIF](https://user-images.githubusercontent.com/86842/189648604-c03b7024-1770-4c56-baa3-3f5060b673d3.gif)

The file, along with the supporting screenshots and Photoshop file are available [in Drive](https://drive.google.com/drive/folders/1LnMdC9idMvpf95-eUG_wJ7-fHHW7SZ8c). This probably wasn't the most efficient way to do it, but it used tools I already had, and worked fine:

1. Opened [the Figma prototype](<https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=4551%3A4180&scaling=scale-down&page-id=4551%3A4111&starting-point-node-id=4551%3A4180>)
1. Used [the Screenshot utility on macOS](https://support.apple.com/guide/mac-help/take-a-screenshot-or-screen-recording-mh26782/mac) to take screenshots that were consistently positioned and sized
   - The frames are different sizes, and I wasn't sure how to easily export/create consistently-sized screenshots with the mobile device frame. Someone more experienced with Figma/Photoshop could probably do that easily.
1. Followed [the Photoshop GIF tutorial](https://www.adobe.com/creativecloud/photography/discover/animated-gif.html)
   1. Dropped the screenshots in as Layers

Some design decisions I made, which can easily be altered if anyone has strong feelings:

- Excluded some of the click-through screens from Login.gov to make the GIF loop shorter
- Made the start and end frame delays (two and three seconds, respectively) longer than the middle ones (one second) to emphasize the "speeding through"
  - One second seemed like the right duration to allow people to read the title and get a sense of each frame/page, without leaving time to get lost in the fine print
- Didn't bother showing anything "below the fold" of any page
- Only showed the form fields filled-in

Closing this as done, but happy to tweak based on feedback.

**Comment by vykster** [comment]
@afeld would you also please make a version of this with the short-flow -- presuming someone already has a login.gov account?

**Comment by afeld** [comment]
@srhhnry @Indiajar Do we have the screens for @vykster's request in Figma, by chance?

**Comment by srhhnry** [comment]
Yup, it's a prototype (so under the prototype section) entitled "Senior Mobile Current Login User Prototype" and found here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=5414%3A21915

Not sure this is helpful, but I made a video walkthrough of that prototype for Olivia, which can be found here: https://cal-itp.slack.com/files/U032BKMAHA9/F03VCRWCYLB/benefitsdemo_currentloginaccount.mov
