### ISSUE TITLE
Project Triage GitHub Actions are failing

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#769]
Recent runs for the [Project Triage workflows](https://github.com/cal-itp/benefits/actions?query=workflow%3A%22Project+triage%22) (that add issues and certain PRs to the [Digital Service project](https://github.com/orgs/cal-itp/projects/8/views/1)) are failing with the message:

> Request failed due to following response errors:
> - Your token has not been granted the required scopes to execute this query. The 'projectV2' field requires one of the following scopes: `['read:project']`, but your token has only been granted the: `['repo', 'write:org']` scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> - Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: `['read:project']`, but your token has only been granted the: `['repo', 'write:org']` scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

## Additional context

The token is from the Cal-ITP org-wide `GH_PROJECTS_TOKEN` secret

**Comment by angela-tran** [comment]
FYI, there _may_ be one more error after fixing the one about `['read:project']`.

See https://github.com/actions/add-to-project/issues/139

**Comment by thekaveman** [comment]
Added the necessary scopes to the token, and [re-ran a failed action](https://github.com/cal-itp/benefits/actions/runs/2631932270): it succeeded!
