### ISSUE TITLE
Limit to secure cipher suites

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#771]
Jemurai found that [we are using insecure cipher suites](https://docs.google.com/spreadsheets/d/12BIe2hmxGIFsq8_rdpbeiemdyVz0qYld/edit#gid=1303467638).

## To Reproduce

1. [Scan with SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=test-benefits.calitp.org)
2. Click on one of the IPs
3. Under `Cipher Suites`, see `TLS_DHE_RSA_WITH_AES_*`

## Expected behavior

Following steps above, `TLS_DHE_RSA_WITH_AES_*` _shouldn't_ appear.

## Screenshots

n/a

## Additional context

- https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-app-service-environment-custom-settings#change-tls-cipher-suite-order
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3

Possible there's an existing environment that needs to be [imported](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3#import).

**Comment by thekaveman** [comment]
I either don't have permissions to see the Environments or none exists? 

![image](https://user-images.githubusercontent.com/1783439/178070430-ea616f62-63cc-4aa8-93fb-ac9673a3c4c8.png)

It seems like we would need a few other resources to create an environment via terraform, namely an `azurerm_virtual_network` and `azurerm_subnet`. Putting this on pause until we can pair again.

**Comment by afeld** [comment]
Looks like we may need to create one. The virtual network (and presumably subnet) exist, though we don't have permissions to view them (see error in https://github.com/cal-itp/benefits/issues/686). Worst case, we could try providing the `subnet_id` as a string.

**Comment by thekaveman** [comment]
@afeld I feel like you asked me about this somewhere... but I can't find the thread now. In any case, I haven't had a chance to come back to it yet.

**Comment by afeld** [comment]
Reopening until we confirm the fix is working.

**Comment by afeld** [comment]
Moving back to Backlog to reinvestigate later.

**Comment by afeld** [comment]
Blocked by https://github.com/cal-itp/benefits/issues/830.

**Comment by afeld** [comment]
We more recently determined that TLS termination is happening in Front Door, and ["Front Door doesn’t support configuring specific cipher suites."](https://learn.microsoft.com/en-us/azure/frontdoor/end-to-end-tls#supported-cipher-suites) Considering this an accepted risk.
