### ISSUE TITLE
Use minified version of CA State Web Template, possibly upgrade

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#777]
## Acceptance Criteria

- [ ] Use minified version of CA State Web Template
- [ ] Investigate using the upgraded jQuery-less version of the CA State Web Template

## Additional Context
https://github.com/cal-itp/benefits/issues/767#issuecomment-1176786102

**Comment by angela-tran** [comment]
I wonder if it would better to be on the ["latest release"](https://webstandards.ca.gov/state-template/), which is 5.6, instead of a beta version. The [template example site](https://template.webstandards.ca.gov/) is all based on 5.6. 

![latest_release](https://user-images.githubusercontent.com/25497886/178544597-5bb43f53-0063-431c-bda8-db62dcec6714.gif)

Being on the same version would make it easier to use components from the CA Web Template. (We currently use their [alert bar](https://github.com/cal-itp/benefits/blob/dev/benefits/core/templates/core/includes/alert.html), and it took some trial-and-error to get it to work with the 6.0.2 CSS/JS.)

**Comment by angela-tran** [comment]
@machikoyasuda showed me that the Web Template repo actually has [updated examples](https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/tree/v6.0.7/sample), so we can just clone it locally if we ever need to reference their samples!

I'm good with upgrading to minified 6.0.7 👍

**Comment by machikoyasuda** [comment]
Knowing exactly what version of Bootstrap the latest CA Web template uses will be helpful and necessary for the Page refactor/grid ticket.

**Comment by thekaveman** [comment]
`6.0.8` has been released since we created this ticket. Going for that!

**Comment by thekaveman** [comment]
> Knowing exactly what version of Bootstrap the latest CA Web template uses will be helpful and necessary for the Page refactor/grid ticket.

Looks like State Template `6.0.8` uses Bootstrap `5.1.3`: https://github.com/Office-of-Digital-Services/California-State-Web-Template/blob/6.0.8/src/scss/bootstrap/scss/bootstrap.scss#L2

**Comment by thekaveman** [comment]
@angela-tran @machikoyasuda I am questioning if we even need to keep the `cagov.core.min.js`? I think the only possible thing we used from there was the "Back to Top" arrow?

Loading the new version is throwing a bunch of console errors that I'd rather not deal with, and rather not the user see. Any thoughts?

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran Yea, I think we can remove `cagov.core.min.js` - as long as we ensure there are no regressions on all the places we use jQuery (the forms).

**Comment by angela-tran** [comment]
> @angela-tran @machikoyasuda I am questioning if we even need to keep the `cagov.core.min.js`? I think the only possible thing we used from there was the "Back to Top" arrow?
> 
> Loading the new version is throwing a bunch of console errors that I'd rather not deal with, and rather not the user see. Any thoughts?

So we had removed `cagov.core.min.js` in... (still looking for the PR). It was needed / added back in https://github.com/cal-itp/benefits/pull/294/commits/6b771c48d206726b00ca7a31a80969cf80c50f9c so we could show an alert banner if reCAPTCHA failed... if it's causing more trouble than it's worth, maybe we should just take out the alert banner?

**Comment by thekaveman** [comment]
That's right, thank you for the reminder @angela-tran!

I vote we take it out and/or use something more Bootstrap native. Maybe we just include Bootstrap's JS instead of CA Gov?

**Comment by thekaveman** [comment]
I have mistaken on `6.0.8` being _released_ -- there is [currently a branch](https://github.com/Office-of-Digital-Services/California-State-Web-Template/tree/6.0.8) for that work, but not a tag/release.

Will base on the the [latest tag/release: `v6.0.7`](https://github.com/Office-of-Digital-Services/California-State-Web-Template/releases/tag/v6.0.7)

**Comment by thekaveman** [comment]
Having a problem processing the new CSS file with `bin/init.sh`.

Error message:

```bash
Post-processing 'css/cagov.core.v6.0.7.min.css' failed!

...

ValueError: The file 'css/fonts/ca-gov-icon.woff' could not be found with  
<django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f29be12d960>.
```

This file is referenced ultimately from [`source/scss/cagov/icon-font.scss`](https://github.com/Office-of-Digital-Services/California-State-Web-Template/blob/v6.0.7/source/scss/cagov/icon-font.scss#L7):

```scss
@font-face {
  font-family: "CaGov";
  src: url("../fonts/CaGov.ttf?ocljyw") format("truetype"), url("fonts/ca-gov-icon.woff?t3czrh") format("woff"),
    url("../fonts/CaGov.woff2?ocljyw") format("woff2"), url("../fonts/CaGov.svg??ocljyw#CaGov") format("svg");
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```

But it is nowhere to be found in the repo... I've search through multiple branches, tags...
