### ISSUE TITLE
Wireframe students

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#779]
[Teamwork task](https://calitp.teamwork.com/#/tasks/26336523)

**Comment by afeld** [comment]
@srhhnry put together [a prototype in Figma](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=4688%3A16407&scaling=scale-down&page-id=4684%3A15737&starting-point-node-id=4688%3A16407) of the LMS flow … Is there more we want here, or should we call this "done"?

**Comment by srhhnry** [comment]
Seconding @afeld here. @vykster is there anything else to add?

**Comment by vykster** [comment]
Maybe showing the LMS login screen? Otherwise no comments.

**Comment by srhhnry** [comment]
This completely slipped through the cracks for me. (Thanks for the nudge, @afeld!)  Finding these LMS screens is pretty touch, so I just created a generic version based on what I saw on a search for Canvas login screens and added it to the prototype. 



![Image](https://user-images.githubusercontent.com/5394204/184445735-607644a3-d0a7-43d1-afd8-5584231977ab.png)

**Comment by afeld** [comment]
Nice, thanks @srhhnry!
