### ISSUE TITLE
Wireframe calfresh

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#781]
Need more direction here @vykster

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/184195591-a0f13085-a7e6-4556-9335-9f92fbbbb486.png)

**Comment by srhhnry** [comment]
https://docs.google.com/document/d/1Q9GMYzjOTaRdybA6M0p52jn3qCxWQ5Qbm9TBFocB1A4/edit?usp=sharing

**Comment by srhhnry** [comment]
Done by end of first week of September
