### ISSUE TITLE
Design Decision: Courtesy Card Flow

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#782]
Determine what the flow should look like for Courtesy Cards: What should the experience be for a courtesy card holder? Don't necessarily need screens, but wireframes and architecture might be useful.

**Comment by srhhnry** [comment]
- [ ] Speak with Olivia to get MST perspective
- [ ] Speak with CDT-ID team to get their perspective
- [ ] Speak with dev team on previous CC work
- [ ] Research on best practices
- [ ] Write brief on decision

**Comment by srhhnry** [comment]
Need to reschedule time with Greg

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/180327451-bd583253-898c-4ef9-b289-6f79043b2e77.png)

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/180493262-fcdd1892-fdf2-4eea-8b81-29c5b615840d.png)

**Comment by srhhnry** [comment]
https://www.uxmatters.com/mt/archives/2014/05/designing-solutions-for-unpleasant-tasks.php

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/180517412-7739df5a-d4e6-491d-a234-19e0266ebcb0.png)

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/180517487-bd6e2eba-b09a-42d8-bfea-7f7f8fdc9371.png)

**Comment by srhhnry** [comment]
![Image](https://user-images.githubusercontent.com/5394204/180517577-a6089ef6-1f6a-4fb9-8749-a7f428e552f2.png)

Thinking about adding an explanatory page on what Benefits is, contactless payment, etc. Then dropping the user into the first question (transit agency? What type of discount are they eligible for?)

**Comment by srhhnry** [comment]
https://docs.google.com/presentation/d/1JMR5F26O8SZBU2I3sKUif52YVgwN1EiwjIQ6XUqnHnw/edit?usp=sharing

**Comment by srhhnry** [comment]
https://docs.google.com/presentation/d/1JMR5F26O8SZBU2I3sKUif52YVgwN1EiwjIQ6XUqnHnw/edit?usp=sharing
