### ISSUE TITLE
Header: Use new Cal-ITP Benefits logo in Header, remove animation

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#783]
A clear and concise description of the task.

## Acceptance Criteria

- [x] Use new Cal-ITP Benefits logo in Header
- [x] Define width/height for both Mobile and Desktop (this increases web perf)
- [x] Remove header animation

## Additional context

Part of #767

**Comment by srhhnry** [comment]
Logos have been updated in Figma and can be found here: https://www.figma.com/file/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=2%3A11

To export, go to the bottom right in the file and select options under Export, which looks like this:


![Image](https://user-images.githubusercontent.com/5394204/178588874-08e72e27-91a7-482c-a1c0-b127ab3635ec.png)
