### ISSUE TITLE
run smoke tests against live system

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#813]
We've had a handful of issues with misconfiguration that have broken redirects and whatnot. May be useful to confirm that the success path continues to work by automating that check with code.

Various parts of the flow/interfaces (Login.gov, Littlepay) are out of our control, and thus can change without notice. This can make tests (which look for specific text/selectors) fragile. I suggest:

- Timeboxing this effort
- Using a throwaway test Login.gov account
- Getting rid of the tests if they end up being flaky

## Acceptance Criteria

- [ ] We are notified if the success path no longer works in test/production environment

## Additional context

[Cypress](https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Step-1-Start-your-server) may be a good option, since we use it already.

> Many of our users … reserve a smaller set of smoke tests that run only against a deployed production app.

[Another blog post about it.](https://code.joejag.com/2021/synthetic-monitoring-with-cypress.html)

**Comment by angela-tran** [comment]
This feels shaped enough, but we probably won't ever be able to get a Login.gov account for the success path.
