### ISSUE TITLE
write an incident report for downtime 7/21/22

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#826]
https://docs.google.com/document/d/14XFpJonXmrNKDt98g8vML3RimbZha0UJiIeUVclXYGs/edit

## Acceptance Criteria

- [x] We have shared a written [incident report](https://blog.softwarerisk.com/what-is-an-incident-report-and-why-it-is-needed) with relevant stakeholders

**Comment by afeld** [comment]
@thekaveman Finished the full draft; mind giving it a look when you get a few minutes?

**Comment by thekaveman** [comment]
Yep looks good @afeld thank you for putting that together.

**Comment by afeld** [comment]
[Posted in Slack](https://cal-itp.slack.com/archives/C037Y3UE71P/p1658927226170749?thread_ts=1658440076.744149&cid=C037Y3UE71P) and emailed to ISO and DevSecOps.
