### ISSUE TITLE
Simplify pytest.mark.django_db usage across test modules

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#828]
In #812 @angela-tran mentions:

> I noticed in the [`pytest-django` docs](https://pytest-django.readthedocs.io/en/latest/database.html#enabling-database-access-in-tests) that we can apply a marker to the entire module by setting a top-level variable like
`pytestmark = pytest.mark.django_db`...

Let's simplify our tests by removing the repeated mark and applying a file/module-level mark instead.

## Acceptance Criteria

- [ ] Each test file/module with tests needing database access uses a top-level variable mark like `pytestmark = pytest.mark.django_db`
- [ ] No test has the `pytest.mark.django_db` decorator

**Comment by angela-tran** [comment]
I think a caveat to this is that we wouldn't want `pytest.mark.django_db` to be blindly applied to tests it shouldn't be applied to - i.e. if the thing being tested shouldn't interact with the database, it shouldn't have the marker. This can probably be achieved without too much effort if we are good about organizing our tests such that there isn't a mix of tests that need database access vs. not.

**Comment by thekaveman** [comment]
Deprioritizing this.
