### ISSUE TITLE
make downtime alerts louder

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#832]
As [described in the 7/21 downtime report](https://docs.google.com/document/d/14XFpJonXmrNKDt98g8vML3RimbZha0UJiIeUVclXYGs/edit#heading=h.tbfsxvwjhk7u),

> We should get “loud” alerts about downtime, but right now there’s just [a message posted to a high-volume channel](https://cal-itp.slack.com/archives/C022HHSEE3F/p1658439759753709).

## To Reproduce

1. Make the production environment unavailable.
   - At time of writing, the monitoring for `dev` and `test` are the same as `prod` will be.
   - Some ways to do this:
      - [Disable traffic](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#route-production-traffic-automatically)
      - Deploy a code change that prevents the container from starting
      - Delete the hostname binding
3. Wait for alert

## Expected behavior

For production downtime, engineer(s) should get a ping, ideally something that needs to be acknowledged.

## Additional context

none

**Comment by afeld** [comment]
@angela-tran pointed out that the alerts could be clearer as well: "alert activated" is really saying "the site is down."

**Comment by afeld** [comment]
[The team wasn't seeing alerts for a scheduled GitHub Action failure](https://compilerla.slack.com/archives/C02GQ7AJXQE/p1669071788447239?thread_ts=1669050796.660269&cid=C02GQ7AJXQE); may be worth [sending those to Slack](https://www.ravsam.in/blog/send-slack-notification-when-github-actions-fails/).

**Comment by afeld** [comment]
https://github.com/cal-itp/benefits/issues/733 is the same thing as this issue, but for exceptions rather than downtime.

**Comment by angela-tran** [comment]
The email alerts to our Slack channel are working. It was more of a process improvement that was needed, and we've done that by updating our Incident Response procedures.
