### ISSUE TITLE
Add CSS Linter

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#836]
A clear and concise description of the task.

## Acceptance Criteria

- [ ] Add a CSS linter
- [ ] Choose a CSS linter: https://stylelint.io/?

**Comment by thekaveman** [comment]
Let's try and find a linter that works in both a `pre-commit` context and within the devcontainer.

**Comment by thekaveman** [comment]
I think we can close this @machikoyasuda @angela-tran? 

We have the prettier VSCode extension _and_ `pre-commit` hook checking JS and CSS (and also formatting via the extension).

**Comment by machikoyasuda** [comment]
Sounds good to me!
