### ISSUE TITLE
update pitch deck

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#857]
https://docs.google.com/presentation/d/1RmBrbGVADkn0hDp17PBnaewIA7C1IjXh9I2jiONMl7A/edit

## Acceptance Criteria

- [ ] Deck reflects current flows/integrations of Benefits app

## Additional context

Per @vykster [in Slack](https://cal-itp.slack.com/archives/D03D5MQ4Q3S/p1660166190537579):

> there’s two audiences (1) operators interested in signing up to use benefits (2) policy makers. might get split into two decks for those audiences.

**Comment by MarikoLochridge** [comment]
There were two decks in the Google Drive, upon closer examination it was determined that this deck [Update Benefits slide deck #1288](https://github.com/cal-itp/benefits/issues/1246) is the more recently updated deck and will be used moving forward. Closing this ticket and requesting future notes about the Benefits Deck to be updated on ticket #1288
