### ISSUE TITLE
Use Amplitude's Python SDK

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#865]
As of June 29, 2022 - Amplitude has released version [1.0.0 of `amplitude-analytics`](https://pypi.org/project/amplitude-analytics/), a Python package for sending event data. 

Rather than keeping up with changes to the Amplitude API, we should use their official package to abstract those details and allow us to stay focused on the meaningful events for our app.

Needs more investigation to determine how to convert our code and if any custom events/properties would get left behind.

## Acceptance Criteria

- [ ] All of our Python-based events are sent via `amplitude-analytics` instead of direct `requests` to the API

## Additional context

See:

* [`benefits/core/analytics.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/core/analytics.py)
* [`benefits/eligibility/analytics.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/eligibility/analytics.py)
* [`benefits/oauth/analytics.py`](https://github.com/cal-itp/benefits/blob/dev/benefits/oauth/analytics.py)

**Comment by indexing** [comment]
@thekaveman @machikoyasuda Have we completed the work on this issue to meet the acceptance criteria?

**Comment by thekaveman** [comment]
@indexing - no, we have not even started this work.

**Comment by thekaveman** [comment]
This hasn't been relevant in 2 years and doesn't seem worth the effort right now.
