### ISSUE TITLE
Add verifier property to Events

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#875]
Soon users will have multiple pathways to verify eligibility, and it would be useful to know how many users are taking which pathway(s) in our analytics. We can get ahead of this now by adding an event property with the user's selected verifier (if any).

Let's add this to the base Event definition so that we can later filter any event type by this property, similar to the Transit Agency information attached to each event.

Linking this Amplitude reference again: https://help.amplitude.com/hc/en-us/articles/115002380567-User-properties-and-event-properties

## Acceptance Criteria

- [ ] The base Event has an `eligibility_verifier` event property that gets its value from the user's `session.verifier()`
- [ ] The Amplitude Tracking Plan is updated to accept this event property
- [ ] The Amplitude --> Warehouse --> Metabase pipeline is updated to ingest this property

## Additional context

This task was broken out from #342 and is focused on adding the verifier information to _existing_ events. #342 is now focused on introducing _new_ events for some forthcoming UI.

**Comment by angela-tran** [comment]
I noticed that `transit_agency` is also being sent as a user property, so I did the same with `eligibility_verifier`.
