### ISSUE TITLE
Add new login.gov details to customer service documentation

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#899]
## Acceptance Criteria

- [ ] MST has contact information for the login.gov customer service team and/or knows how to escalate an issue to them.
- [ ] All of the information from the initial slack message is captured in relevant documents. 

## Additional context

- [slack message](https://cal-itp.slack.com/archives/C037Y3UE71P/p1662061573989469)
- [customer service documentation](https://docs.google.com/document/d/1RFQMY0KOdjn0P6Cqd_4Dv2redzCmKLT3Ww8ADfcBmYQ/edit)

## What is the definition of done?
- [ ] Doc approved by Product Manager and shared with MST Customer Service team.

**Comment by afeld** [comment]
This is a duplicate of https://github.com/cal-itp/benefits/issues/645, yeah?

**Comment by vykster** [comment]
yes
