### ISSUE TITLE
Move all 404/500/error pages to the One Column Layout

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#914]
## Acceptance Criteria

- [x] 404, 500 pages move to 1 column layout
- [x] Use the “Enrollment redirect” error mock for 404s and 500s resulting from the user not entering the app at the correct phase, e.g. no agency selected, no verifier selected, not verified as eligible yet

## Additional context

See Figma

Related to #913 https://github.com/cal-itp/benefits/issues/757

**Comment by angela-tran** [comment]
@thekaveman Oops, I didn't realize you were assigned to #757 and that it had so much overlap. Let me know if you had any changes that you'd like incorporated here 🙏
