### ISSUE TITLE
Update docs site with details about debugging with `Debug=False`

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#929]
## Acceptance Criteria
- [ ] The Development section of https://docs.calitp.org/benefits has details about debugging with `Debug=False`

## Additional context
#925 added the configuration we'd like to document.

**Comment by machikoyasuda** [comment]
Documentation on using Debug=False and recaptcha envs https://github.com/cal-itp/benefits/pull/1071

**Comment by thekaveman** [comment]
@thekaveman will add this month.
