### ISSUE TITLE
Asset upload: Cal-ITP Benefits Gif

### ISSUE THREAD

**Issue by esquared415** [cal-itp/benefits#930]
Hello @thekaveman, @angela-tran & @machikoyasuda! 

As we've been discussing in [this slack thread](https://cal-itp.slack.com/archives/C037Y3UE71P/p1662984338244379), I need Docs (or Cal-ITP website) hosting of [this gif](https://drive.google.com/file/d/1-3wYK3wc_N0XNF1xwWy_hx-fl4m4fo-I/view?usp=sharing).

I'll include a link to it in the Cal-ITP Benefits Press Release PDF that I'm also prepping a ticket for.

Please let me know if you have any Qs, and thank you!

**Comment by thekaveman** [comment]
The GIF is now live on this page: https://docs.calitp.org/benefits/use-cases/seniors/

Direct link: https://docs.calitp.org/benefits/use-cases/img/senior-success.gif
