### ISSUE TITLE
Add documentation on working with Django language files

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/benefits#954]
The Development section of the Benefits docs site should have docs on how to work with Django language files (especially since #814 introduced a specific workflow).

## Acceptance Criteria

- [ ] Development section includes docs on how translations are handled and the workflow that is recommended when modifying the language files

## Additional context
#814

**Comment by thekaveman** [comment]
@angela-tran can these docs be added this month?

**Comment by angela-tran** [comment]
@thekaveman Yep
