### ISSUE TITLE
Add docs on clearing Terraform state lock

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#960]
Starting yesterday, the `terraform plan` pipeline for `dev` started failing due to inability to acquire the state lock.

Affected PRs:

* #951 
* #956
* #959

The error message is as follows:

```bash
╷
│ Error: Error acquiring the state lock
│ 
│ Error message: state blob is already locked
│ Lock Info:
│   ID:        UUID
│   Path:      tfstate/terraform.tfstate
│   Operation: OperationTypePlan
│   Who:       sombody
│   Version:   1.2.4
│   Created:   2022-09-26 23:16:15.022646317 +0000 UTC
│   Info:      
│ 
│ 
│ Terraform acquires a state lock to protect the state from being written
│ by multiple users at the same time. Please resolve the issue above and try
│ again. For most commands, you can disable locking with the "-lock=false"
│ flag, but this is not recommended.
╵
```

The docs should include a section in [`Infrastructure`]() that shows an example of this error message and the command to force the release of the lock:

```bash
terraform force-unlock <UUID>
```

## Acceptance Criteria

- [ ] The docs describe how to release the lock to clear this error

## Additional context

https://www.terraform.io/cli/commands/force-unlock

Prior work to deal with this issue in #876

**Comment by afeld** [comment]
If a Terraform command is running, it's important to let it exit gracefully so it can release the lock. Locally, this means doing a CONTROL-C once rather than a bunch of times. In theory, cancelling a Pipeline run should do so, but I'm not positive.

**Comment by thekaveman** [comment]
@afeld can we add this docs update this month?
