### ISSUE TITLE
Terraform pipeline failing to connect to storage account

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#965]
Error message from a recent pipeline run:

```console
Failed to get existing workspaces: Error retrieving keys for Storage Account "[REDACTED]": autorest/Client#Do:

Preparing request failed: StatusCode=0 -- Original Error: clientCredentialsToken: received HTTP status 401 with response:

"error": "invalid_client",
"error_description": "AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the
request is the client secret value, not the client secret ID, for a secret added to app '***'.\r\nTrace ID: [REDACTED]\r\nCorrelation
ID: [REDACTED]\r\nTimestamp: 2022-09-27 21:38:30Z",
"error_codes": [7000215],
"timestamp": "2022-09-27 21:38:30Z",
"trace_id": "REDACTED]",
"correlation_id": "[REDACTED]",
"error_uri": "[https://login.microsoftonline.com/error?code=7000215"}]https://login.microsoftonline.com/error?code=7000215%22})
```

## To Reproduce

Open a PR against `dev`, observe the Terraform pipeline check in GitHub fail, observe the Terraform pipeline in Azure fail.

## Expected behavior

The pipeline can connect to the storage account, where Terraform state is maintained.

## Additional context

* #876 
* https://github.com/cal-itp/benefits/pull/876#issuecomment-1259797812
* #960

**Comment by thekaveman** [comment]
@afeld do you have some time to look into these recent Terraform pipeline issues?

**Comment by afeld** [comment]
Argh. Is looking into it by the end of the week ok, or is it a blocker?

**Comment by thekaveman** [comment]
End of the week is fine! Not a blocker until we need to make an infra change 😄

**Comment by afeld** [comment]
I think we need DevSecOps team support on this, as I don't have permissions to look at the Service Principal; emailed them with details.

**Comment by afeld** [comment]
The client secret was expired; once @sureshtekyentra replaced it, pipeline runs started working. Asking about how to avoid this problem in the future.
