### ISSUE TITLE
CSS: Refactor Button includes, CSS and alignment + 404 page/Help button

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#972]
A clear and concise description of the task.

## Acceptance Criteria

- [x] I believe Button LABEL can be deleted now
- [x] Refactor btn-lg
- [x] Btn width should be 3 grid width for Desktop and different for mobile, centered on mobile
- [x] Button alignment to the right, and centered on mobile
- [x] Btn-outline-light should not have manual width
- [x] Btn-primary capitalize
- [x] Btn-lg
- [x] Btn-link: Remove?
- [x] Button Back
- [x] Button Previous
- [x] Sign Out link

**Comment by machikoyasuda** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/194446814-ee5cc13c-341b-4888-a0a3-1be236a7c194.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/194446853-055fec4d-9c36-453d-b7fc-f8681aaf8352.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/194446866-e6e0be83-11da-40eb-9dee-bd38a96eddb4.png">

**Comment by angela-tran** [comment]
@machikoyasuda Will this task cover setting buttons to `width: 100%`? My pages in #1013 are looking ok, except for the buttons... I was wondering if I should just ignore the buttons in my PR.
