### ISSUE TITLE
User Testing of Older Adult Flow

### ISSUE THREAD

**Issue by srhhnry** [cal-itp/benefits#975]
- [x] User test with one participant on the live site
- [x] User test with 2+ participants on Figma prototype (with updated screens, reflecting CC)
- [x] User test with MST support staff
- [x] Create report of live site results
- [x] User testing panel with 5 users on mobile
- [x] Analysis of mobile tests
- [x] Analysis of MST staff interview
- [x] Analysis of prototype participants 
- [x] Create report of prototype results
- [x] Edit and finalize report of prototype results

**Comment by srhhnry** [comment]
Might be able to test with another user on the live site

**Comment by srhhnry** [comment]
All testing for this round is complete

**Comment by thekaveman** [comment]
@srhhnry if testing is complete, can you please close this issue?

**Comment by srhhnry** [comment]
I'm 100% cool with not attaching testing to milestones (or, for consistency having some sort of milestone for design process). At the very least I think it's going to take several more months to bring testing in line with the cadence of feature releases. Also agreed on non-feature tasks (other than testing) having a different home. For example I have a few in the backlog around copy and page design that are more like iterations than new features.

**Comment by thekaveman** [comment]
Yeah we can definitely create as many Milestones as we want! A `Seniors User Testing` milestone, or a `Copy Updates` milestone, etc.

We also don't necessarily _need_ to attach issues to milestones -- particularly if there are only 1 or 2 related issues for a topic, sometimes the milestone overhead isn't worth it. We still have labels and the Project Board for various levels of tracking.

**Comment by srhhnry** [comment]
Report is live here: https://docs.google.com/presentation/d/1w0d6TG4FdNMLgSjfwQAN4WXUwCleGDzWyXcJK1ddE3Y/edit?usp=sharing

Next steps are to meet with product/appropriate parties and to determine next steps
