### ISSUE TITLE
Define User Acceptance Testing criteria for Courtesy Cards

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#981]
## Acceptance Criteria

- [ ] Define devices, browsers, a11y flows should be tested. 
- [ ] Developers to teach Product how to test in a11y - keyboards flows
- [ ] Developers responsible for getting Product all the credentials needed
- [ ] Define what the role of Product should be in UAT
- [ ] Product/Developers define what exact flows should be tested, Developers to ensure all screens are covered

## Additional context
- Meeting scheduled for 10/6

## What is the definition of done?
- [ ] Update test credentials (Eng)
- [ ] Get the server up on dev (Eng)
- [ ] Make a list of all browsers/devices/screen sizes we want to test (prod)
- [ ] Create a mini-checklist of items that non functional test scenarios ie: form is not case sensitive (prod)
- [ ] Create a UAT ticket on GitHub, assigned to Mariko/Marissa (prod)
- [ ] Screenreaders – explore best software options for testing in windows and mac. (prod)
 - [ ] Most commonly used free screenreaders
 - [ ] Completing process without a mouse. (prod with help from Machiko)
- [ ] Create your own login.gov test credentials (see doc for details), play with/explore the dev-benefits.calitp.org env using the [Benefits Test Data](https://docs.google.com/document/d/1bFynuiLy9POXYEYnLVEQJpAm1TVqlappN9lU9ev3Bvg/edit#)(prod)
- [ ] Add UAT to the [Benefits: Product Testing Glossary & Guide](https://docs.google.com/document/d/1Td0eIqRXbCYScaVlz61DW0c2htotSXPKYAfa3gGysKA/edit#heading=h.jfhpiyfqxtdw) (might just be under a different name) - provide links to any example test documentation ie: CC user stories or list of devices for testing. (prod)

**Comment by vykster** [comment]
mtg scheduled for Thursday 10/6.

**Comment by machikoyasuda** [comment]
In progress now with https://github.com/cal-itp/benefits/issues/1034
