### ISSUE TITLE
Draft proposal for additional outreach to transit riders

### ISSUE THREAD

**Issue by vykster** [cal-itp/benefits#982]
## Acceptance Criteria

- [x] Outreach Strategy Drafted 

## Additional context
Given enrollment has been slow, review existing materials, and draft a proposal for outreach to more riders to increase enrollment and use of the program. Enrollment and transactions are key numbers for determining success in 2022. 

## What is the definition of done?
- [ ] Draft document is ready to share with stakeholders

**Comment by vykster** [comment]
Kickoff call scheduled with @o-ram and @MarikoLochridge for November 15th.

**Comment by machikoyasuda** [comment]
This is the website and program https://www.go831.org/ by Transportation Agency for Monterey County (TAMC) that I saw advertised and written up in Monterey County Weekly https://www.montereycountyweekly.com/

**Comment by machikoyasuda** [comment]
The main Monterey County bike advocacy group blog is very up to date and trilingual: https://bikemonterey.org/

**Comment by MarikoLochridge** [comment]
Resource: [Cal-ITP Benefits Launch Comms Plan ](https://docs.google.com/document/d/11wfslytJJ02zb-u8fsY4D92CiG8EU9DXWUENeqnPMtY/edit)

**Comment by vykster** [comment]
new mtg schedule for Monday February 13th

**Comment by MarikoLochridge** [comment]
Resources: 
[Outreach Proposal to Transit Riders](https://docs.google.com/document/d/1DDt94BgnegJu_hC-SHtTplb5gELT0JM9fxbe5XrPkM4/edit)

**Comment by MarikoLochridge** [comment]
Meeting with @vykster @o-ram to complete first draft of outreach proposal. Identified outreach audience, present barriers to outreach and next steps to improve outreach support for local transit providers. 

### Problem: Likely some friction in the signup process, but for now assuming the primary problem is that folks don't know the program exists. 

**Who are they?**

Older adults, who live in the MST service area. Assumptions: Likely have limited access to digital communications, less dexterity, less digital literacy. 

_Assumptions:_ 

- Financially conservative, cost conscious, fixed-income, a significant portion of older adults are living below the poverty line. 
- In MST, a significant of our population in monolingual Spanish
- These folks are likely not very online! Probably do a lot of things via mail, in-person, or telephone. 

Categories of Transit Users
1. Older adults who depend on the bus

**Assumptions:** 
- Do not own cars
- Might live in an supportive community for older adults
- Might travel to senior centers
- Might travel for medical care
- Might travel for groceries (grocery stores that accept EBT) 
- Might travel for errands such as post office, bank (would not do these things online)

2. Older adults who might ride the bus
_Assumptions:_ 

- Residing in a facility that provides transportation
- Family support for transportation/ caretaker drive
- Can drive, but prefer not to

What relationships do they already have/ trust?
- Their local transit provide 
- AARP
- Senior Living Facilities
- Ethnic or local media in primary language (prioritize Spanish in MST)
- Government Service Providers
- > CalFresh (EBT provider)
- > Medicare
- > Social Security Administration
- > Login.gov

Next Steps: 
Inventory of existing organizations focused on 65+ population who can better distill the message for their community. #1267
[Draft inform/ask messages to send to new and existing partners regarding Benefits #1268  ]((https://github.com/cal-itp/benefits/issues/1268))

Resources:
[Outreach Proposal to Transit Riders](https://docs.google.com/document/d/1DDt94BgnegJu_hC-SHtTplb5gELT0JM9fxbe5XrPkM4/edit)
