### ISSUE TITLE
Every page has a unique ID

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#986]
Each page should set a unique `id` attribute on a high-level element, e.g. `<html>` or `<body>` , to allow for easier CSS targeting and overrides.

## Acceptance Criteria

- [ ] Every page has a unique `id` attribute on a high-level wrapping element

## Additional context

We already have a [content block on the `<html>` element](https://github.com/cal-itp/benefits/blob/dev/benefits/core/templates/core/base.html#L6) for adding custom CSS classes. This `id` feature could be accomplished in a similar way.

**Comment by machikoyasuda** [comment]
Closing this ticket from this milestone at this time. It is not needed for any customizations for CC. If we need it in the future, we can re-open the ticket.
