### ISSUE TITLE
Make it clear which terminology to use

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#987]
There have been some discussions that have come up around terminology within the Benefits project:

- "Benefit" and "discount" - cc https://github.com/cal-itp/mobility-marketplace/issues/370
   - What are [the different things the user selects between](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=5957%3A23559&scaling=scale-down&page-id=5450%3A21241&starting-point-node-id=5902%3A24813)?
   - Is there / should there be a catch-all term that encompasses both?
   - The model in the app is `EligibilityType`.
   - This one might be large/important enough to create a (non-architectural) [decision record](https://18f.gsa.gov/2021/07/06/architecture_decision_records_helpful_now_invaluable_later/) around.
- [Identity "verification" and "proofing"](https://cal-itp.slack.com/archives/CG64NU5C7/p1663020296383499)

I could see a Glossary/Terminology section of the [style guide](https://www.figma.com/proto/SeSd3LaLd6WkbEYhmtKpO3/Benefits-(IAL2-Login.gov)?node-id=4942%3A17385&scaling=scale-down&page-id=4890%3A17182) or the [docs site](https://docs.calitp.org/benefits/).

## Acceptance Criteria

- [ ] For some "core terms" (listed above), it is clear when to use one versus another

**Comment by afeld** [comment]
Just learned the [Editorial Style Guide](https://docs.google.com/document/d/1yG2jc_aMPSGc2wqvazKGgFIeV-aDDDsJIuONhUg0MOI/edit#) exists, which is probably the right place for this.

**Comment by machikoyasuda** [comment]
"Courtesy Card-like card" - Maybe Agency Card, In-Person Card or Membership Card

**Comment by afeld** [comment]
Another potential home: [Language Matters](https://docs.google.com/document/d/1ud73Qaa7k6I5l8MwlQrZd8iOo7_3shZHy_gCxfAe0eY/edit)

**Comment by machikoyasuda** [comment]
The style guide for words should also have a column for what is the official term for Spanish. For example, `contactless` is `sin contacto`.

**Comment by machikoyasuda** [comment]
This also exists https://www.camobilitymarketplace.org/glossary-of-key-terms but does not have all key terms used in the app and is also only in English.

**Comment by afeld** [comment]
I think we should probably refine/update/consolidate/share the existing ones, but yes, terminology seems to trip us up enough that I think investing the time sooner than later will pay for itself.

**Comment by srhhnry** [comment]
Oh, per what @machikoyasuda mentioned during the mobimart review, I think it would be helpful to build in a step (or an item to be checked off) for reviewing any new copy against a style guide.

**Comment by machikoyasuda** [comment]
I started a Google Spreadsheet of terms in English and Spanish from benefits.calitp.org that are already approved, copy edited and translated for the Login.gov milestone, and a new tab for new terms we need for Courtesy Cards milestone: https://docs.google.com/spreadsheets/d/15aKUPv6gl-Y_j6XV2aiFnJ2wQlQobyfjBCUaSbQHelM/edit#gid=0

**Comment by vykster** [comment]
Closing this issue, see notes from copy retro in [sprint planning notes doc](https://docs.google.com/document/d/1EGLplnM3FFU7zJY3Bsb0CLjlbepxK0r1te1uPoFOlMc/edit#).
