### ISSUE TITLE
Add direct URLs for benefits

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#988]
_As a rider reaching Benefits from a targeted communication, I want to skip steps where the answer is implied._

Once we have multiple benefit/discount options, it might be useful to have a direct link to a specific one. Examples:

- Targeted outreach from MST to older adults could link directly to MST senior fare eligibility verification
- Schools can link directly to their college discount

Might be useful to confirm with stakeholders that this would be useful, and with users that it doesn't add confusion. Would need to be careful that the relevant context is given, even if some pages are skipped.

## Acceptance Criteria

- [ ] There are URLs that select the agency and benefit/discount

## Additional context

We already have direct URLs for agencies, e.g. `/mst`.

**Comment by vykster** [comment]
Closing as does not related to a documented problem in enrollments.
