### ISSUE TITLE
As a developer on Benefits, I want an efficient process for copy edits, so that text stay up to date.

### ISSUE THREAD

**Issue by afeld** [cal-itp/benefits#993]
## Background information

_To be revised as more is learned_

The current theoretical process for copy updates:

1. English text gets updated in Figma
1. There is back and forth about it in Slack, meetings, etc.
1. English text gets copied from Figma into a Google Doc
1. That Google Doc is sent to stakeholders for review
1. Those edits are copied back into:
   - [The English locale file](https://github.com/cal-itp/benefits/blob/dev/benefits/locale/en/LC_MESSAGES/django.po)
   - Figma
1. The Google Doc is sent to MST for translation into Spanish
1. The Spanish text is copied into [the Spanish locale file](https://github.com/cal-itp/benefits/blob/dev/benefits/locale/es/LC_MESSAGES/django.po)

The team has expressed some pain points around this:

- Unused text gets left in the locale files - cc https://github.com/cal-itp/benefits/issues/776
- It's hard to track which English text has been changed, and thus what needs to be translated
- Keeping Figma, Google Docs, and the locale files in sync is tedious and error-prone

## Acceptance criteria

- [ ] It's clear what text needs to be (re)translated

## Definition of "Done"

A clear and concise description of what "Done" means for this User Story.

**Comment by vykster** [comment]
New copy process was executed in November, notes from the copy process retro are in the [running sprint notes doc](https://docs.google.com/document/d/1EGLplnM3FFU7zJY3Bsb0CLjlbepxK0r1te1uPoFOlMc/edit#). Marking this issue closed.
