### ISSUE TITLE
Create viewmodel for the media item list include

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#994]
#967 refactors the media list from the Eligibility Start template into a reusable include for use in the Enrollment flow as well. However we maintained the existing `dict` context for simplicity and to ensure no breakages.

This ticket is to refactor the `dict` context into a `viewmodel` class like the others, with the necessary properties to capture data for a media list item.

**Comment by machikoyasuda** [comment]
Media Item component options:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/3673236/193664503-a44bf2d2-34cb-43f0-9005-cc7ef9aa0ecd.png">
